### PR TITLE
[#3834] Keep root path in new user url

### LINKED ISSUE #3834: Registering a new account redirects to an unprefixed url
### CKAN Version if known (or site URL)
2.7.0 and master

### Please describe the expected behaviour
Upon registering a new account, the user should be redirected to a url starting with the root path

### Please describe the actual behaviour
The url to which a new user is redirected should include the root path

### What steps can be taken to reproduce the issue? 
On an installation that uses `ckan.root_path`, register a new account.

### PR DESCRIPTION
**Pull request by alexbrault**
Fixes #3834

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by amercader** [comment]
@wardi this reverts a change made in a recent PR that has been backported https://github.com/ckan/ckan/pull/3749. Should we backport this as well?

**Comment by wardi** [comment]
@amercader does it? the `__ckan_no_root=True` part that is being removed was added in 4936c7c2ceb0987f80446ae69128281757f8e69e

IIUC this fix is required because we removed some url_for magic that we used to have when passed a plain string

**Comment by amercader** [comment]
@wardi sorry, you are right this does not revert any change. Too many redirects in the user controller.

But I stand corrected as removing `__ckan_no_root=True` in other redirects was part of #3749 so IIUC this should be backported as well for consistency in all user redirects. Does this make sense?

**Comment by amercader** [comment]
I'm pretty sure this needs to go into 2.6 and 2.7 as #3749 was backported there so I'll backport it too. @wardi @Zharktas let me know if you think otherwise

**Comment by wardi** [comment]
@amercader ok, I understand now. Sounds good.

**Comment by Zharktas** [comment]
Looks like that commit removed the last one of the "ckan_no_root" magics, at least according to the search https://github.com/ckan/ckan/search?utf8=%E2%9C%93&q=__ckan_no_root&type=, the logic should be removed from the helper too since it just complicates unnecessarily?

**Comment by amercader** [comment]
@Zharktas absolutely

**Pull request merged**
