### PR TITLE
[#3588] Fix for Upload Log time at resource Datastore tab

### PR DESCRIPTION
**Pull request by Engerrs**
Added a fix for the time that display at Upload Log, it seems that **job_detail** at datapusher_status action gives already the time with +3 hours.
I've changed the variable that template uses for the display to the one that used in the table as the Upload Log will be match to the value in the table.

### CODE REVIEW

**Comment by smotornyuk** [comment]
@Engerrs , as i understand, you suggesting to use time of last status change, that is the same for each [log record](https://github.com/Engerrs/ckan/blob/83b7c2dbf02501400bc27ab35cbb65f48b5f13d4/ckanext/datapusher/templates/datapusher/resource_data.html#L64). In that case information for tasks that are executing for a while, becomes irrelevant. It would be much better to use item's timestamp as it was before, but use `datetime.utcnow` it the point of item creation

**Comment by Engerrs** [comment]
Hi @smotornyuk , I've add a small fix for timestamp, rather then change the item used in template, but I couldn't change the timestamp, because the info that it gets for display is set in [**ckanserviceprovider**
package](https://github.com/ckan/ckan-service-provider/blob/master/ckanserviceprovider/util.py#L53) and save if in our **job_store.db** file. So I've found another way to deal with the timestamp for logs by converting it to UTC format from it's current.

**Comment by smotornyuk** [comment]
As i understand, you can use `time.strptime` instead of `datetime.strptime`. It's not critical, but more obvious

**Comment by Engerrs** [comment]
Hi @smotornyuk, changed that one.

**Comment by smotornyuk** [comment]
@Engerrs , thanks)

**Pull request merged**
