### PR TITLE
Filter by group type

### PR DESCRIPTION
**Pull request by njall**
We can create our own custom groups easily in CKAN as an extension but when loading the index page of our new group using the Group Controller, we do not include type in our request. 
This fix adds group_type to data_dict['type'] which will be the name of our custom group if using it. If it is the default group it will be None so ignores it.

### CODE REVIEW

**Comment by wardi** [comment]
This change doesn't have any test coverage. Would you add an example extension that implements a custom group type something like the other ckanext/example_* directories so we can be confident this works and won't break in the future?

**Comment by njall** [comment]
I've added an example_igroupform plugin and controller. I can't spare the time to write a full UI or a test suite for it though. Is this enough? Could it be made a bug for someone else to enhance in the future?

**Comment by wardi** [comment]
Is this complementary to or superceeded by #2354 ?

Also is removing the 404 in the controller correct? Shouldn't we always be using the right controller for the group_type?

**Comment by wardi** [comment]
Closing as duplicate of #2354

**Pull request closed without merging**
