### PR TITLE
4483 remove legacy search

### LINKED ISSUE #4483: Remove legacy Search API
### CKAN Version if known (or site URL)

Can we officially deprecate the legacy [Search API and Utils APIs](https://docs.ckan.org/en/latest/api/legacy-api.html)?

These was described as "legacy API"s since CKAN 2.3 (here)[https://github.com/ckan/ckan/commit/254fca2d43ccacbe674df2da42aba83897dcdb96#diff-b4e5718590c95267775a87dafc922c76). However they have not been marked as deprecated in the changelog.

These are the APIs:
* `/api/search/dataset` / `/api/search/package` (replaced by `package_search`)
* `/api/search/resource` (replaced by `resource_search`)
* `/api/search/revision` (revisions are deprecated)
* `/api/tag_counts` (can be done with `package_search facet.field='tags'`)
* `/api/util/dataset/autocomplete` (replaced by `package_autocomplete`)
* `/api/util/tag/autocomplete` (replaced by `tag_autocomplete`)
* `/api/util/resource/format_autocomplete` (replaced by `format_autocomplete`)
* `/api/util/dataset/munge_name`
* `/api/util/dataset/munge_title_to_name`
* `/api/util/tag/munge`

I can't see any replacements for the munge functions and I suspect they are still useful to anyone replacing the CKAN front-end. Should we turn these into action funcs?

(We [got rid of the REST API `/api/rest/*` in 2.8](https://github.com/ckan/ckan/pull/4069), having been marked as deprecated in the 2.7 changelog)

### PR DESCRIPTION
**Pull request by ZoranPandovski**
Fixes #4483

### Proposed fixes:
This PR removes old search legacy API, as mentioned in the issue. I will add munge functions as actions and remove the legacy code in the next PR. Legacy api/search tests are removed, and new package_search tests are fixed.

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [x] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by amiedes** [comment]
Hey, I think you've removed the old API but are still trying to use it from the code [here](https://github.com/ckan/ckan/blob/master/ckan/templates/package/snippets/package_basic_fields.html#L23).

**Comment by amercader** [comment]
@amiedes The util API was migrated to the new Flask blueprint (here)[https://github.com/ckan/ckan/blob/master/ckan/views/api.py#L500]. Did you find any problem using the tag field?

**Comment by amiedes** [comment]
> The util API was migrated to the new Flask blueprint

Oh! So you're redirecting the old routes to the new actions, right?

> Did you find any problem using the tag field?

I was trying to integrate autocomplete in a tag field for a vocabulary (CKAN 2.8.2). I'm able to obtain suggestions making requests like `/api/3/action/tag_autocomplete?vocabulary_id=example123&query=?`, but the autocomplete is not showing them. I'm suspecting of the response format, which seems to have changed between versions 2 and 3:

```json
{
  "ResultSet":  {
    "Result": ["tag1", "tag2"]
  }
}
```

vs

```json
{
  "help": "http://ckan.test/api/3/action/help_show?name=tag_autocomplete",
  "success": true,
  "result": ["tag1", "tag2"]
}
```

The javascript code that parses suggestions seems to be expecting a `ResultSet` [here](https://github.com/ckan/ckan/blob/ckan-2.8.2/ckan/public/base/javascript/client.js#L163)

Thanks for your help @amercader!

**Comment by howff** [comment]
I made a patch to solve your problem in pull 5071  https://github.com/ckan/ckan/pull/5071
It works, although tags from a specific vocabulary added to a dataset end up in the tag string properly but are also added as free tags i.e. missing the vocabulary id.
I made a new issue in  ckanext-scheming https://github.com/ckan/ckanext-scheming/issues/224

**Pull request merged**
