### PR TITLE
Switching from schema.xml to ManagedSchema

### PR DESCRIPTION
**Pull request by frafra**
Needed for #4535.

### Proposed fixes:

This patch allows to use Solr API to add fields, instead having to modify the schema.xml file directly.

### Features:

- [ ] includes tests covering changes
- [x] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

### CODE REVIEW

**Comment by frafra** [comment]
I am pretty sure that circleci is failing because the test are run against the old Solr configuration.
On my PC everything seems to work as usual, but I am not able to run the tests.

**Comment by wardi** [comment]
This isn't a small change or something that we can do just in the docker images.

We'll need to update the source install instructions and add a command that will create and populate a solr core for use by ckan. Then we need a way for extensions to hook in to that command to add their own fields, languages and anything else they currently set up by customizing the solr schema.

@frafra the tests are very useful for development! Maybe set up a source install so you can run the tests locally?

**Comment by frafra** [comment]
@wardi I will try to setup properly now that I am trying to do more complex commits.

Are you proposing to drop entirely the CKAN schema and just use the new API? I was thinking just to add the new capabilities related to managed schema without breaking compatibility at the moment, so no documentation change would be needed at the beginning.

The default schema.xml URL seems the only change that would break backwards compatibility; I do not know if the best way to handle it would be to check  both URLs by default or if there is a way to do a request to detect if the new schema factory is in use.

I am not sure how/when the `solrconfig.xml` located in the CKAN repository was generated and if it needs to be updated. I suppose that it is something shipped with the Sorl by the Linux distribution we should change it in order to change the parameter (I do not think that it is generated on-the-fly, because Solr documentation says that recent 6.6 releases use the new managed schema).

**Comment by wardi** [comment]
I thought solr was either-or. You can't start with a schema.xml but also have solr managing the schema can you?

**Comment by TkTech** [comment]
> 
> 
> I thought solr was either-or. You can't start with a schema.xml but also have solr managing the schema can you?

You can, solr will copy the schema.xml on startup to managed-schema by default and start using it instead.

**Comment by frafra** [comment]
Ok, managed schema is used by default, but it uses the old one if it is not found. This should avoid breaking backwards compatibility. It is up to the system administrator or solr packager to choose between one of them, CKAN supports both.

We can extend and update the documentation in a successive pull request, if we want to go in this direction. It could be a feature to showcase for the next minor release (CKAN 2.9.0) I suppose.

**Comment by torfsen** [comment]
+1 for an easy way for extensions to dynamically update the Solr schema. That would be very useful for ckanext-extractor.

**Comment by frafra** [comment]
It seems to work as expected. Here is what I am using inside my plugin (that is an example):

```
    def update_config(self, config_):
        toolkit.add_template_directory(config_, 'templates')
        toolkit.add_public_directory(config_, 'public')
        toolkit.add_resource('fanstatic', 'coat')
        self._custom_schema()

    def _custom_schema(self):
        response = requests.get(CKAN_SCHEMA+'/copyfields')
        copyfields = response.json()['copyFields']
        if {"dest": "version_i", "source": "version"} in copyfields:
           return
        requests.post(CKAN_SCHEMA, json={
            "add-field":{
                "name": "version_i",
                "type": "int",
                "stored": True,
            }
        })
        requests.post(CKAN_SCHEMA, json={
            "add-copy-field":{
                "source": "version",
                "dest": ["version_i"],
            }
        })
```

It would be nice to have some helpers for such kind of requests and checks in the future.

**Comment by frafra** [comment]
Proposal: accept the patch, which provide additional flexibility without breaking compatibility; after that a more inclusive discussion about managed schema could be started.

**Comment by wardi** [comment]
@TkTech what do you think about this change as-is?

**Comment by TkTech** [comment]
Certainly in favor, as long as we ensure dynamic fields are disabled. I can't recall what the default behaviour of managedindexfactory is.

We tend to send a lot more to solr than what is actually needed by the schema. If we allow dynamic fields it'll just be a mess.

**Pull request merged**
