### PR TITLE
Docker using python3

### PR DESCRIPTION
**Pull request by kowh-ai**
Definitely fixes: https://github.com/ckan/ckan/issues/5896 https://github.com/ckan/ckan/issues/5724 https://github.com/ckan/ckan/issues/5572

Perhaps fixes: https://github.com/ckan/ckan/issues/5874

### Proposed fixes:

- Uses ubuntu:focal-20210119 as the Docker base image for the CKAN container
- Installs Python3 system packages
- Uses Python3 rather than Python2 in the CKAN container

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by kowh-ai** [comment]
- Tested creating a SysAdmin user
- Logging in to CKAN with that user
- Creating a new Organisation
- Uploading a dataset

**Comment by chobeat** [comment]
Hello. If I do `docker-compose up --build -d` from a clean situation, it build correctly but fails at runtime with

```➜ docker logs ckan
db:5432 - accepting connections
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "/usr/lib/ckan/venv/bin/ckan", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 18, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__
```
Is it my problem? It doesn't seem very python-3 to me

**Comment by kowh-ai** [comment]
Just ran a fresh build after removing/pruning all containers, images, networks and volumes - all good

Screen Shot 2021-03-04 at 1 22 52 pm

**Comment by chobeat** [comment]
ok sorry, I will try again. It's likely my problem then

**Comment by chobeat** [comment]
Hello. I've been digging a lot into the problem because I would like to make this work but I'm observing the following: 

* after cleaning my docker completely the previous error is still there
* the python3 stuff is correctly installed into the container
* there's python2 and python3 installation in the same container
* the python version that runs in the shell of the container is python3
* the ckan command is in a virtualenv in python3
* BUT when I run the entrypoint, it tries to import from a python3 venv the pkg_resources in this python2.7 space: 

> "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py"

Where does this stuff come from?

**Comment by kowh-ai** [comment]
I assume the CKAN container still doesn't run successfully and you are running a shell based off the `docker_ckan` image (rather than letting `ckan-entrypoint.sh` run)...I just checked my running CKAN container and I don't have a `/usr/lib/ckan/venv/local/` directory at all and have no Python2 libraries installed...Did you remove all Docker volumes (both local and docker mounts)?

**Comment by chobeat** [comment]
today I learned: "docker system prune -a" doesn't prune volumes. I think it's doing something now

**Comment by chobeat** [comment]
one last thing: may I ask you how you created the admin account? the "paster" executable is not in the venv/bin folder. There's a symlink but the destination file is missing

**Comment by kowh-ai** [comment]
Get shell access onto the running container...activate the python virtual environment and then run `. /usr/lib/ckan/venv/bin/activate`

**Comment by kowh-ai** [comment]
After getting a shell session on the CKAN container try this:

```
ckan@d6383dea7fd3:/$ . /usr/lib/ckan/venv/bin/activate
(venv) ckan@d6383dea7fd3:/$ ckan -c /etc/ckan/production.ini sysadmin add mradmin email=mradmin@localhost name=mradmin
2021-03-05 15:22:42,867 INFO  [ckan.cli] Using configuration file /etc/ckan/production.ini
2021-03-05 15:22:42,867 INFO  [ckan.config.environment] Loading static files from public
2021-03-05 15:22:42,979 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
2021-03-05 15:22:43,228 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
User "mradmin" not found
Create new user: mradmin? [Y/n]: Y
Password :
Repeat for confirmation:
Successfully created user: mradmin
Added mradmin as sysadmin
```

**Comment by kowh-ai** [comment]
@Zharktas - Hey Jari - could you please review/merge this PR. Installing CKAN with Docker is broken at the moment. This PR will fix this - thanks!

**Review by Zharktas — APPROVED** [review]

**Comment by frafra** [comment]
Shouldn't this be backported to 2.9?

**Pull request merged**
