### PR TITLE
Filtered Datatables Downloads

### PR DESCRIPTION
**Pull request by wardi**
Add a Download button to the datatables view to download filtered data based on view filters, user filters and datatables query string and sort order.

### CODE REVIEW

**Comment by wardi** [comment]
**FLASK fix included**: I needed to change `request.params` to `request.args` in the snippet now that the dataset views are served with Flask. This likely affects other views, can we improve backwards compatibility for external plugins by aliasing `request.params` to `request.args`?

**Comment by wardi** [comment]
should be complete now. Only the visible columns are downloaded

**Comment by wardi** [comment]
@smotornyuk like 6bc233e ?

**Comment by smotornyuk** [comment]
Yes, exactly

**Pull request merged**
