### PR TITLE
Update dashboard_organizations.html

### PR DESCRIPTION
**Pull request by gsueur**
Fixes #

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [X] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

Add the permission parameter set to 'read' in order to retrieve organization people are members of and not only the ones the have edit rights on.

### CODE REVIEW

**Comment by amercader** [comment]
Thanks for the patch @gsueur. This change is part of a bigger patch I started working ages ago and didn't   manage to finish (I think there are only tests missing). I'll try to find some time this week to get it ready for reviewing.

https://github.com/ckan/ckan/pull/2457

**Comment by gsueur** [comment]
Hi Adria,

No problem. It was just a quick fix needed for the users. 
We have been funding the upgrade for the dataproxy extension too ! 

Best regards

Guillaume

**Comment by TkTech** [comment]
@amercader should we close this then in favour of #2457?

**Comment by amercader** [comment]
Closed in favour of #2457

**Pull request closed without merging**
