### PR TITLE
 Hardcoded references to db host and users removed

### LINKED ISSUE #4845: Docker container dd container name hardcoded in startup.
### CKAN Version if known (or site URL)
master branch

### Please describe the expected behaviour
Initializing CKAN container should connect to the database container regardless of the database container name. Also should be able to connect to an external DB server. 

### Please describe the actual behaviour
CKAN container tries to see if a server named "db" is live, simply returning "no attempt". This is is because this server name is hardcoded in `ckan-entrypoint.sh` @ line 44, rather than taking an environment variable. This also prevents using an external or existing DB.

### What steps can be taken to reproduce the issue? 
Spin up your docker compose with a different container name, or with external server name in connection URLS.

### PR DESCRIPTION
**Pull request by Gauravp-NEC**
Fixes #4845 

### Proposed fixes:
 Hardcoded references to db host and users are removed.

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Review by kowh-ai — COMMENTED** [review]
I have looked at this change and I tested it (with problems). Could you please let me know what testing you have carried out - thanks

**Comment by Gauravp-NEC** [comment]
@kowh-ai , I have tried to test the same in my local setup of Ubuntu 16.04. As Ubuntu 16.04 have reached to EOL. in April 30 2021 so I am not sure about the testing. Does this PR looks good?

**Comment by kowh-ai** [comment]
It shouldn't really matter if the testing was done on a Ubuntu 16.04 server however I would recommend to use **at least** Ubuntu 18.04 for all PR testing. What testing have you done? Did you change the database hostname to be something other than `db`? Which file(s) did you make the change(s) to?

**Comment by Gauravp-NEC** [comment]
@kowh-ai ,I have tried to test it with pg_isready check. Does this PR looks good to be merged?

**Comment by kowh-ai** [comment]
You mean the `pg_isready` check in the `ckan-entrypoint.sh` file? Wouldn't you change the **database server name** somewhere else to test a new name other than using "`db`" ? The `pg_isready` check  just uses environment variables so this should never be changed to test - Maybe changing the `POSTGRES_HOST` variable in the `.env` file?

**Comment by Gauravp-NEC** [comment]
@kowh-ai , I have not change the database server name somewhere else to test it.

**Comment by kowh-ai** [comment]
You say this PR fixes this issue:  https://github.com/ckan/ckan/issues/4845

This issue specifies the following:

**What steps can be taken to reproduce the issue?**
- Spin up your docker compose with a different container name, or with external server name in connection URLS.

This is what you need to do to see if your PR fixes the issue

**Comment by Gauravp-NEC** [comment]
@kowh-ai , The author ErroneousBosch has confirm my understanding that hardcoded reference to db host and users should be removed in comment https://github.com/ckan/ckan/issues/4845#issuecomment-875699315) plus more clarification was provided to me here: https://github.com/ckan/ckan/issues/4845#issuecomment-876386557

**Comment by Gauravp-NEC** [comment]
@kowh-ai , The author ErroneousBosch has confirm my understanding that hardcoded reference to db host and users should be removed in comment https://github.com/ckan/ckan/issues/4845#issuecomment-875699315) plus more clarification was provided to me here: https://github.com/ckan/ckan/issues/4845#issuecomment-876386557

**Comment by Gauravp-NEC** [comment]
@kowh-ai , Did hard-coded reference to db host and users is required in CKAN?

**Comment by Gauravp-NEC** [comment]
@kowh-ai , Did hard-coded reference to db host and users should be removed in CKAN?

**Comment by kowh-ai** [comment]
If _any_ of the service hostnames are to be changed then the database name (db) would be the best candidate however you could argue all of the hostnames _could_ be changed. Remember, hostnames in docker equate to container names so you need to test this PR by changing the container name. I think the best way to test would be to change the `POSTGRES_HOST` environment variable in the **.env** file as this is where the database server name (hostname) is set.

**Review by kowh-ai — CHANGES_REQUESTED** [review]
This PR needs to be tested by changing the database server hostname to see if it still works

**Comment by Gauravp-NEC** [comment]
@kowh-ai , I have tested this PR by changing the POSTGRES_HOST environment variable in the .env file. It works fine in my environment. This PR is ready to merged.

**Comment by Gauravp-NEC** [comment]
@kowh-ai ,I have tested this PR by changing the POSTGRES_HOST environment variable in the .env file. It works fine in my environment. This PR is ready to merged.

**Comment by kowh-ai** [comment]
I had failures during my testing -  I changed the .env to be **POSTGRES_HOST=db3** (rather than POSTGRES_HOST=db) and rebuilt the docker containers - Seems the CKAN container is stuck trying to come up…it’s in the while loop Line 45 of the `ckan-entrypoint.sh` file. It looks like the ${POSTGRES_USER} environment variable is not set for this container and needs to be. Here is a snippet of the CKAN Docker log files

…
`Try "pg_isready --help" for more information.`
`/usr/lib/postgresql/12/bin/pg_isready: option requires an argument -- 'U'`
`Try "pg_isready --help" for more information.`
`/usr/lib/postgresql/12/bin/pg_isready: option requires an argument -- 'U'`
`Try "pg_isready --help" for more information.`
`/usr/lib/postgresql/12/bin/pg_isready: option requires an argument -- 'U'`
`Try "pg_isready --help" for more information.`
`/usr/lib/postgresql/12/bin/pg_isready: option requires an argument -- 'U'`
…

**Comment by Gauravp-NEC** [comment]
@kowh-ai , In my environment containers are running well.

Capture

**Comment by kowh-ai** [comment]
Did you log into CKAN? Did you check the logs of the CKAN container? My containers all have a status of **up**, however the CKAN container is effectively hung

**Comment by Gauravp-NEC** [comment]
@kowh-ai , I have done the rework in commit https://github.com/ckan/ckan/pull/6244/commits/91c0d1a68d8ed6a6f86640a26a7ac0065adf9a22. Now  CKAN container is not getting stuck. Please review it. Thanks:)

**Comment by Gauravp-NEC** [comment]
@kowh-ai , I have done the rework in commit https://github.com/ckan/ckan/pull/6244/commits/91c0d1a68d8ed6a6f86640a26a7ac0065adf9a22. Now  CKAN container is not getting stuck. Please review it. Thanks:)

**Comment by kowh-ai** [comment]
Nope, still not working…I changed the to POSTGRES_HOST=**db4** in the **.env** file and the CKAN container still hangs with the following messages:
`...`
`db4:5432 - no response`
`db4:5432 - no response`
`db4:5432 - no response`
`db4:5432 - no response`
`db4:5432 - no response`
`db4:5432 - no response`
`db4:5432 - no response`
`<etc>`

**Comment by Gauravp-NEC** [comment]
@kowh-ai , Any suggestion can you provide me to making it working?

**Comment by Gauravp-NEC** [comment]
@kowh-ai , Any suggestion could you provide me to solve the "no response"?

**Comment by kowh-ai** [comment]
The **container_name** entry in the docker-compose.yml file specifies the name of the container itself which will be used within Docker as the hostname for container to container network access…Please read: https://docs.docker.com/compose/networking/

**Comment by Gauravp-NEC** [comment]
@kowh-ai , Thanks I have read the doc: https://docs.docker.com/compose/networking/ and found the same that hostname is identical to the container name.

**Comment by kowh-ai** [comment]
You have hard-coded your **container_name** entry in your `docker-compose.yml` file which means your hostname will always be **db** for your database container!

**Review by kowh-ai — CHANGES_REQUESTED** [review]
@Gauravp-NEC - It looks like you haven't changed anything in this PR  (other than merging master) since my last comment. **You need to test this by changing the database container hostname to something other than db!!!** - leaving the database contain name / hostname at "db" works but changing it (in the .env file) doesn't work. The whole point of this PR is to get rid of the hardcoded references to "db"

**Comment by kowh-ai** [comment]
Could you change the db service **container_name:** to be ${POSTGRES_HOST} please and then test with a different name other than **db** - thanks

Screenshot 2022-02-15 at 3 17 53 pm

**Comment by kowh-ai** [comment]
Also, I think some additional documentation on this would be a good idea ie: what to do to change container names and how it affects hostnames on the docker network

**Comment by Gauravp-NEC** [comment]
@kowh-ai , Based on your comment https://github.com/ckan/ckan/pull/6244#issuecomment-1040331471 above I have changed the db service container_name to ${POSTGRES_HOST} and tested the same  with a different name other than db. It works successfully.

**Comment by kowh-ai** [comment]
Great! Nice work and if you could update the documentation then this change will be good to merge

**Comment by kowh-ai** [comment]
> Documentation which needs to be updated will be done here: https://docs.ckan.org/en/2.9/maintaining/installing/install-from-docker-compose.html? Please confirm

Yes, just mention what needs to change when wanting to use environment variables rather than hard coding docker container names / host names - put the changes you made to "db" to get this done - thanks

**Comment by Gauravp-NEC** [comment]
@kowh-ai , I have updated the documentation in commit https://github.com/ckan/ckan/pull/6244/commits/146298bbfa6554cba9208c45b334361a6ab2df2f

**Comment by Gauravp-NEC** [comment]
@kowh-ai , I have updated the documentation in commit https://github.com/ckan/ckan/pull/6244/commits/146298bbfa6554cba9208c45b334361a6ab2df2f. Please review the PR. Thanks :)

**Review by kowh-ai — CHANGES_REQUESTED** [review]
This reads better:

`You have the option of using environment variables rather than hard coding the actual docker container name. For example, if you want to remove the "db" container name replace "db" with name of your environment variable in docker-compose.yml:'

**Comment by Gauravp-NEC** [comment]
> This reads better:
> 
> `You have the option of using environment variables rather than hard coding the actual docker container name. For example, if you want to remove the "db" container name replace "db" with name of your environment variable in docker-compose.yml:'

@kowh-ai , Based on your suggestion I have commit the changes but 1 test case is failing in ci/circleci: test-python-3. I think failing test case is nothing to do with commit https://github.com/ckan/ckan/pull/6244/commits/35fbb1993f32b65ab2d027271f93794672aa4991. Can you please have a look. Thanks

**Comment by Gauravp-NEC** [comment]
> This reads better:
> 
> `You have the option of using environment variables rather than hard coding the actual docker container name. For example, if you want to remove the "db" container name replace "db" with name of your environment variable in docker-compose.yml:'

@kowh-ai , Based on your suggestion I have commit the changes but 1 test case is failing in ci/circleci: test-python-3. I think failing test case is nothing to do with commit https://github.com/ckan/ckan/pull/6244/commits/35fbb1993f32b65ab2d027271f93794672aa4991. Can you please have a look. Thanks

**Comment by Gauravp-NEC** [comment]
@kowh-ai , Below failed test case is nothing related to this PR. I think this PR read to merge.

image

**Comment by Gauravp-NEC** [comment]
@kowh-ai , Below failed test case is nothing related to this PR. I think this PR read to merge.

image

**Review by kowh-ai — APPROVED** [review]
Looks good

**Comment by Gauravp-NEC** [comment]
> Looks good

@kowh-ai @amercader , As this PR looks good now. Please merge this PR. Thanks :)

**Comment by Gauravp-NEC** [comment]
> Looks good

@kowh-ai @amercader , As this PR looks good now. Please merge this PR. Thanks :)

**Comment by Gauravp-NEC** [comment]
> Looks good

@kowh-ai @amercader , As this PR looks good now. Please merge this PR. Thanks :)

**Comment by Gauravp-NEC** [comment]
> Looks good

@kowh-ai, As this PR looks good now. Please merge this PR. Thanks :)

**Comment by Gauravp-NEC** [comment]
> Looks good

@kowh-ai @amercader , As this PR looks good now. Please merge this PR. Thanks :)

**Pull request merged**
