### PR TITLE
Dockerfile Update

### PR DESCRIPTION
**Pull request by deinok**
-Upgrade of base image
-Not repository Independent (Now its not required to Docker source be in the same git)
-Pinned by default to 2.5.2
-Overriding CKAN_GIT_BRANCH gives the feature to install any branch in the main GitHub. Overriding to master gives an easy way to develop

### CODE REVIEW

**Comment by wardi** [comment]
I'm not sure what's up with the circleci failure. Is your circle configured to use a different base image or something?

Also, do you mind squashing all your empty merge commits?

**Comment by deinok** [comment]
@wardi CicleCi is using the dockerfile?
I only nodified the dockerfile.

If CircleCi uses the dockerfile, by default it gets the release-v2.5.2 and not the branch trying to test

**Comment by wardi** [comment]
No, our tests don't depend on any of our docker images. Your circle CI configuration might be using a different base image than ours for running the tests, though. Would you check that?

**Comment by deinok** [comment]
I will take a look and see what why is failing the solr

**Pull request closed without merging**
