### PR TITLE
Backport PR 7839 to v2.9 (DataStore Dump Streaming)

### PR DESCRIPTION
**Pull request by JVickery-TBS**
backport(datastore): 7839 for 2.9;

- Backport code from PR 7839 for v2.9.

https://github.com/ckan/ckan/pull/7839

CC: @amercader

### CODE REVIEW

**Comment by amercader** [comment]
Sorry @JVickery-TBS, there are some failures in the datastore `test_dump.py` tests

**Comment by JVickery-TBS** [comment]
@amercader sorry! Okay I had to fix up the string vs bytes stuff, namely with the BOMs and the XML writer. The tests should pass now.

And I manually tested locally on a CKAN 2.9 python2 install, and a python3 install. And the code works in both.

**Comment by JVickery-TBS** [comment]
@amercader the only test not passing is `test_building_the_docs`, not sure if that is related to this code or not.

**Comment by wardi** [comment]
@JVickery-TBS try building them yourself with `sphinx-build doc build/sphinx` to see what the error was

**Comment by amercader** [comment]
Thanks @JVickery-TBS ,I'll take care of the docs failures, these are unrelated

**Pull request merged**
