### PR TITLE
Pep8 - BugFixing

### PR DESCRIPTION
**Pull request by deinok**
Changes PEP8 dependency to PyCodeStyle and fix PEP8 issues

### CODE REVIEW

**Comment by deinok** [comment]
Closes #3312

**Comment by wardi** [comment]
not sure why circleci isn't running the test on this one

**Comment by amercader** [comment]
@deinok can you merge latest master to fix the conflicts and update this branch to see if this triggers the circleci build again?

**Comment by wardi** [comment]
@amercader oh? I wonder if circle builds only the result of the merge then? That would make sense.

**Comment by deinok** [comment]
@amercader @wardi Merged

**Pull request merged**
