### PR TITLE
Update nodejs/less versions for frontend. 

### PR DESCRIPTION
**Pull request by davidread**
### Proposed fixes:

* Specify newer NodeJS (v4 -> v10. v4 is not being maintained)
* Specify newest `less` version
    * shorthand colors remain shorthand, e.g. `#fff`
* Rebuilt the frontend (i.e. ran 'less')

### Features:

- [ ] includes tests covering changes
- [x] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by davidread** [comment]
@gocemitevski you were last in this area - are you happy with this change?

**Comment by gocemitevski** [comment]
@davidread yes, even though I would probably pick the LTS Node.js release - v. 8.x, as it is more stable. It is supported by April 2019. https://github.com/nodejs/Release#release-schedule

Nothing to add about the LESS version. Looks good to me.

**Comment by davidread** [comment]
@johnglover thanks for this. Yeah, both NodeJS 8 and 10 work fine for this, but tbh we don't update this version very often, so next year will come around rather soon. 10.x is 'current' and is good til 2021 which I think is a better bet.

**Comment by johnglover** [comment]
@davidread: I _could_ take credit, but it seems unfair :)

**Comment by smotornyuk** [comment]
Yes, I agree with David - every even node version is LTS and as far as I know, by the end of the year v10 will replace v8 on current active LTS position. So it quite sensible to switch directly to  v10.

**Comment by davidread** [comment]
Sorry @johnglover, but hello again! :)

**Comment by johnglover** [comment]
👋

**Pull request merged**
