### PR TITLE
[#4194] Fix the "From" field with UTF-8 name and ASCII address in mail

### LINKED ISSUE #4194: lib/mailer: The header "From" with UTF-8 name and ASCII address
### CKAN Version if known (or site URL)

2.6.5

### Please describe the expected behaviour

The "From" field (with UTF-8 name) in the header of emails sent by CKAN should be decoded and displayed by recipient's email client like:

From: "跨領域區域研究資料集" \<no-reply@data.depositar.io\>

### Please describe the actual behaviour

The "From" field shows:

From: "跨領域區域研究資料集 \<no-reply@d"ata.depositar.io\>

Note that the latter double quote is in the wrong place, which ruins the field and brakes some email authentication methods, such as DKIM.

### What steps can be taken to reproduce the issue? 

1. Set a site title with UTF-8 characters in SITE_URL/ckan-admin/config.
2. Let CKAN send a mail (invite someone via email, for example).

P.S. According the discussion in [this thread](https://stackoverflow.com/questions/41908883/how-to-add-an-utf-8-from-address-to-a-mail-mesage), we should assign the encoding to the name part and the address part respectively. I will submit a workable PR later.

### PR DESCRIPTION
**Pull request by u10313335**
Fixes #4194

### Proposed fixes:

According the discussion in [this thread](https://stackoverflow.com/questions/41908883/how-to-add-an-utf-8-from-address-to-a-mail-mesage), we should assign the encoding to the name part and the address part respectively.

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [X] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by u10313335** [comment]
Oops, it seems that some tests were failed. I will try to fix them.

**Comment by wardi** [comment]
I think email headers are ascii-only. Unicode addresses are encoded like https://tools.ietf.org/html/rfc5234 (from https://tools.ietf.org/html/rfc6532#section-3.1 ) There should be a module that handles this for us we can use?

**Comment by u10313335** [comment]
Thanks @wardi. But I think the [email.header.Header](https://docs.python.org/2/library/email.header.html#email.header.Header) class I am using encodes the from address well?

**Comment by wardi** [comment]
@u10313335 you're right, I didn't read the change properly.

I'm confused now, though.. why were we using gettext on `_("%s <%s>")`? Let's get rid of that.

Why not change the From line to match the recipient one below instead?
```python
    from_ = u"%s <%s>" % (sender_name, mail_from)
    msg['From'] = Header(from_, 'utf-8')
```

According to the email.header.Header docs passing `'utf-8'` as the second argument does nothing (Header tries to encode unicode strings as us-ascii first regardless) but it's consistent with the rest of the code in the same function.

**Comment by u10313335** [comment]
@wardi It seems that the problem is that the misplaced quotes put by recipient's email client. If we encode the all From line `%s <%s>`, email.header.Header will try to encode the whole line as utf-8 using [RFC2047 rules](https://tools.ietf.org/html/rfc2047.html#section-2) as long as possible. For example,

* The sender with shorter name `我是中文寄件者 <no-reply@localhost>` will be encoded as a single line `=?utf-8?b?5oiR5piv5Lit5paH5a+E5Lu26ICFIDxuby1yZXBseUBsb2NhbGhvc3Q+?=`. Then the recipient's email client will decode it as `"我是中文寄件者 <no-reply@localhost>"`

* The sender with longer name `我是比較長的中文寄件者 <no-reply@localhost>` will be encoded into two lines:
`=?utf-8?b?5oiR5piv5q+U6LyD6ZW355qE5Lit5paH5a+E5Lu26ICFIDxuby1yZXBseUBs?=`
`=?utf-8?q?ocalhost=3E?=`
Then the recipient's email client will decode it as `"我是比較長的中文寄件者 <no-reply@l"ocalhost>`. The quoted part is just the first line.

Note that **both situations produce the wrong From line** in recipient's email client. The correct From line should be `"我是中文寄件者" <no-reply@localhost>` and `"我是比較長的中文寄件者" <no-reply@localhost>`. Only the sender's name needs to be quoted.

The proposed PR (force the sender's address not to be encoded as utf-8 according to the [docs](https://docs.python.org/2/library/email.header.html#email.header.Header.append)) is the only workaround to bypass this problem as far as I know. The encoded From line of the first example will be `=?utf-8?b?5oiR5piv5Lit5paH5a+E5Lu26ICF?= <no-reply@localhost>`

P.S. 

1. I agree that we should remove the gettext function though. Like this:

  ```python
  msg['From'] = Header("%s" % sender_name, 'utf-8')
  msg['From'].append("<%s>" % mail_from, 'ascii')
  ```

2. It seems that the `msg['To']` line has the same issue.

**Comment by tino097** [comment]
as the #4194 is closed as completed, this PR will be closed too

**Pull request closed without merging**
