### PR TITLE
Run tests using docker-compose [WIP]

### LINKED ISSUE #4644: Run tests using docker-compose
It would be useful to be able to run CKAN's tests using docker-compose. This would need no dependencies or set-up, helping people who suffer difficulty with this.

It would work by mount your local ckan code in a docker container, which includes solr, postgres etc and run all the tests, just like this: https://github.com/ministryofjustice/analytics-platform-control-panel#running-tests-with-docker

### PR DESCRIPTION
**Pull request by davidread**
Fixes #4644 

This work is related to https://github.com/ckan/ckan/pull/4635

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by mroutis** [comment]
Not from the community, but my 2 cents would be to create a separate `Dockerfile.dev` image with development specific environment, instead of having a single one with _moving parts_, maintaining two Dockerfiles is not that hard.

**Comment by davidread** [comment]
@mroutis thanks for the tip! Yes that will help simplify things, and I see this is a common thing to do.

**Comment by davidread** [comment]
Got to here:
```
$ cd contrib/docker
$ docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
...
ERROR: for ckan  Cannot start service ckan: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/usr/lib/ckan/venv/bin/nosetests --ckan --with-pylons=/usr/lib/ckan/venv/src/ckan/test-core.ini /usr/lib/ckan/venv/src/ckan/ckan /usr/lib/ckan/venv/src/ckan/ckanext\": stat /usr/lib/ckan/venv/bin/nosetests --ckan --with-pylons=/usr/lib/ckan/venv/src/ckan/test-core.ini /usr/lib/ckan/venv/src/ckan/ckan /usr/lib/ckan/venv/src/ckan/ckanext: no such file or directory": unknown
```
Not sure yet why it's not finding nosetests. It's there if I simply exec into the docker container. 🤔

**Comment by frafra** [comment]
> Not sure yet why it's not finding nosetests. It's there if I simply exec into the docker container. 🤔

`command` cannot be a list of commands; try to remove `-`

**Comment by davidread** [comment]
@frafra that's it! thank you 🙇

**Comment by frafra** [comment]
`Dockerfile.dev` should probably be rebased on the new `Dockerfile` that CKAN master uses, based on Python 3.

**Comment by EricSoroos** [comment]
Superseceeded by #4635

**Pull request closed without merging**
