### PR TITLE
Old style exceptions --> new style exceptions (en masse)

### LINKED ISSUE #3309: Python 3 support (OLD)
Add Python 3 support.

[Python 2.7 support will end in 2 years](https://pythonclock.org/).

- [x] add Python 3 support to [ofs](https://pypi.python.org/pypi/ofs) and [pairtree](https://pypi.python.org/pypi/Pairtree): ~https://github.com/okfn/ofs/pull/14~, ~https://github.com/benosteen/pairtree/pull/2~
- [ ] remove [ofs](https://pypi.python.org/pypi/ofs) and [pairtree](https://pypi.python.org/pypi/Pairtree), they were needed by the old Filestore.
- [ ] replace Pylons with Flask: ckan/ckan#3119
- [x] remove [ordereddict](https://pypi.python.org/pypi/ordereddict)
- [ ] remove [ofs](https://pypi.python.org/pypi/ofs) and [pairtree](https://pypi.python.org/pypi/Pairtree) dependencies as they are no longer used
- [ ] migrate away from vdm or add Python 3 support to vdm since getting rid of vdm seems like a not an easy task, okfn/vdm#13
- [ ] replace [webhelpers](https://pypi.python.org/pypi/WebHelpers) with a modern alternative
- [ ] replace [repoze.who-friendlyform](https://pypi.python.org/pypi/repoze.who-friendlyform) with a modern alternative
- [ ] add Python 3 support to the ckan own code base
- [ ] Replace Paste with Click #4639

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #3309 (partial fix)

### Proposed fixes:
* Convert old style exceptions --> new style exceptions (en masse)
    * __except Exception, e__ --> __except Exception as e__
    * __raise Exception, msg__ --> __raise Exception(msg)__

As explained in [PEP 3109](https://www.python.org/dev/peps/pep-3109/), old style exceptions are ambiguous and are Syntax Errors in Python 3.  New style exceptions work in both Python 2 and 3.

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by wardi** [comment]
LGTM

**Comment by amercader** [comment]
Thanks @cclauss!

**Comment by wardi** [comment]
@cclauss don't write "Fixes #xxxx" unless it's a complete fix, please :-)

**Comment by cclauss** [comment]
OK

**Pull request merged**
