### PR TITLE
[#7710] add datastore and datapusher templates-bs3

### PR DESCRIPTION
**Pull request by mutantsan**
Fix for https://github.com/ckan/ckan/issues/7710

I've added `templates-bs3` from latest 2.9, instead of removing `ckan.base_templates_folder` usage, because new templates don't support bs3 public. (e.g `data-*` vs `data-bs-*`). 

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [X] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by mutantsan** [comment]
as for unsafe external links, I think it's fine
as for tests, someone broke it and merged.

**Comment by pdelboca** [comment]
@smotornyuk shouldn't this have been backported into the 2.10 branch? Master no longer has support for Bootstrap 3.

**Comment by smotornyuk** [comment]
Yes, good point.

**Comment by markstuart** [comment]
Can we reopen this and target the dev-2.10 branch? Since this was merged and the issue closed it look like it's fixed, but I don't think it is? Just wanting to make sure it doesn't get lost. Thanks @mutantsan and @smotornyuk for sorting this :1st_place_medal:

**Comment by smotornyuk** [comment]
I [merged it into dev-v2.10](https://github.com/ckan/ckan/commit/2333629e5e57e541bfed2dc399d5eb0c9937b9cf) when reverted this PR. 
We are usually using [**Backport pending** label](https://github.com/ckan/ckan/pulls?q=is%3Apr+is%3Aopen+label%3A%22Backport+pending%22) for PRs that are not yet backported.

**Comment by markstuart** [comment]
Thanks @smotornyuk :tada:

**Pull request merged**
