### PR TITLE
Rewrite ckan.logic.converters.convert_to_extras 

### LINKED ISSUE #2150: Custom dataset fields causes IndexError when arbitrary other "extra" fields are used.
Hi,

I followed the instructions here:

http://docs.ckan.org/en/latest/extensions/adding-custom-fields.html#customizing-dataset-and-resource-metadata-fields-using-idatasetform

Unfortunately, when adding new datasets to the catalogue that have further "extra" fields I get the following error:

```
File '/home/vagrant/ckan/lib/default/src/ckan/ckan/lib/navl/dictization_functions.py', line 399 in unflatten
  current_pos = current_pos[key]
IndexError: list index out of range
```
To cut a (very) long story short, the unflatten function was getting data that included entries such as the following:

```
 ('extras',): [{'key': 'coverage_end_date', 'value': u'2002-09-01'},
               {'key': 'coverage_start_date', 'value': u'2001-09-01'},
               {'key': 'homepage', 'value': u'http://homepage.com/'},
               {'key': 'origin', 'value': u'Origin'}],
 ('extras', 0, 'key'): u'qwe',
 ('extras', 0, 'value'): u'qwe',
 ('extras', 1, 'key'): u'wer',
 ('extras', 1, 'value'): u'wer',
 ('extras', 2, 'key'): u'etr',
 ('extras', 2, 'value'): u'etr',
 ('extras', 3, 'key'): u'rty',
 ('extras', 3, 'value'): u'rty',
 ('extras', 4, 'key'): u'tyu',
 ('extras', 4, 'value'): u'tyu',
 ('extras', 5, 'key'): u'yui',
 ('extras', 5, 'value'): u'yui',
 ('extras', 6, 'key'): u'uio',
 ('extras', 6, 'value'): u'uio',
```
It turns out that the existence of the `('extras', )` key/value pair was interfering with the unflattening process of the `('extras', n, foo)` items. How did such an item come about? It turns out that `ckan.logic.converters.convert_to_extras` is the cause and doesn't work in what I would say is a safe and unsurprising manner (it generates the list of `dict` objects rather than inserts the appropriate `('extras', n, foo)` items into the data object).

Interestingly enough, the related `convert_from_extras` function *does* work in what I would call the expected manner (handling `('extras', n, foo)` items).

I'll submit a patch once I get the ticket number for this issue.

### PR DESCRIPTION
**Pull request by ntoll**
This branch introduces a single change:
- Rewrite the `convert_to_extras` function so it behaves in a way that doesn't interfere with other extras and complements the related convert_from_extras function.

I notice there is no test coverage for these.

Fixes #2150.

### CODE REVIEW

**Comment by amercader** [comment]
OK, several things going on here :)

I've been having a look at this and could reproduce the issue using your extension (you get the exception when you provide more free extras than custom fields, otherwise free extras will make custom fields disappear (as described in #1894)).

One thing to note is that on 2.2.1 (the one that your instance targets) you can *not* mix custom fields that get internally transformed into extras with free form extras when using the core converter. As @davidread mentioned in the previous comment the docs said otherwise but unfortunately this was a a mistake left from bad merging (this is now fixed #2259).

AFAICT the issue is fixed when using master or the `release-v2.3` branch. The test you provided passes for me in current master if I comment out the `assert not ('extras',) in data` bit.

Looking at patching this in previous versions, I think we agreed that it was too big a change and broke the API, as it required a change in logic to check that the free extras don't clash with the custom ones (for full context see [1]). I'd suggest that you keep using your custom `convert_to_extras` converter on your extension until you can upgrade to 2.3.

Finally, I'm not saying that this patch is no longer relevant, as you mention it may do things in a safer way ( I need to have another look with more time), but is not directly relevant to fix the original exception you reported.

Hope all of this makes sense.

[1] https://lists.okfn.org/pipermail/ckan-dev/2014-October/008170.html

**Comment by ntoll** [comment]
Hey hey... great stuff and glad to hear the problem will be fixed in the next release. When is that scheduled to be?

**Comment by wardi** [comment]
The free-form vs. converted extras problem will be solvable after #3072 is adapted for dataset extras. We'll have a separate namespace available for each plugin so we could easily have these values live side-by-side (and remove the extras table while we're at it)

**Comment by rossjones** [comment]
Looks like this PR is now unnecessary? Suggest we close it.

**Pull request closed without merging**
