### PR TITLE
Update plugin.py

### LINKED ISSUE #5565: cookiecutter template "fanstatic" should be "assets"
**CKAN version**
2.9

**Describe the bug**
When creating a new extension using ``ckan generate extension``, a "fanstatic" directory is created.

**Expected behavior**
According to https://docs.ckan.org/en/2.9/theming/webassets.html, it should be "assets".

A fix would be to rename the "fanstatic" directory in https://github.com/ckan/ckan/tree/master/contrib/cookiecutter/ckan_extension/%7B%7Bcookiecutter.project%7D%7D/ckanext/%7B%7Bcookiecutter.project_shortname%7D%7D

### PR DESCRIPTION
**Pull request by Gauravp-NEC**
Fixes #5565 

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by Gauravp-NEC** [comment]
I have updated the add_resource entries in plugin.py file in this PR

**Comment by paulmueller** [comment]
In order for #5565 to be fixed, the following things still need to be taken care of:

- [ ] Add *.yml to MANIFEST.in
- [ ] An `assets/webassets.yml` file should be added and maybe an exemplary `assets/my_extenstion.css` file or so which is registered in the webassets.yml file?

**Comment by Gauravp-NEC** [comment]
@smotornyuk, Please review this PR. I have updated the add_resource entries in plugin.py file which is a part of issue https://github.com/ckan/ckan/issues/5565.

**Comment by smotornyuk** [comment]
There is [fanstatic](https://github.com/ckan/ckan/tree/master/contrib/cookiecutter/ckan_extension/%7B%7Bcookiecutter.project%7D%7D/ckanext/%7B%7Bcookiecutter.project_shortname%7D%7D/fanstatic) folder next to `plugin.py`, that was previously reffered by `toolkit.add_resource('fanstatic',  '{{ cookiecutter.project_shortname }}')`. Now, when you are replaced 'fanstatic' with 'assets` inside `add_resource` call, you also have to rename that folder

**Comment by Gauravp-NEC** [comment]
@smotornyuk, I have rename the "fanstatic" directory to "assets" in the following locations:

1.https://github.com/ckan/ckan/tree/master/contrib/cookiecutter/ckan_extension/%7B%7Bcookiecutter.project%7D%7D/ckanext/%7B%7Bcookiecutter.project_shortname%7D%7D
2. https://github.com/ckan/ckan/tree/master/ckanext/example_theme_docs/v16_initialize_a_javascript_module
3. https://github.com/ckan/ckan/tree/master/ckanext/example_theme_docs/v17_popover
4. https://github.com/ckan/ckan/tree/master/ckanext/example_theme_docs/v18_snippet_api
5. https://github.com/ckan/ckan/tree/master/ckanext/example_theme_docs/v19_01_error
6. https://github.com/ckan/ckan/tree/master/ckanext/example_theme_docs/v19_02_error_handling
7. https://github.com/ckan/ckan/tree/master/ckanext/example_theme_docs/v20_pubsub
8. https://github.com/ckan/ckan/tree/master/ckanext/example_theme_docs/v21_custom_jquery_plugin
9. https://github.com/ckan/ckan/tree/master/ckanext/example_theme_docs/v22_fanstatic_and_webassets

Please merge and close this issue if it looks good. Thank you

**Comment by smotornyuk** [comment]
Changes look good, the only issue now is failing test: `ckan.tests.test_coding_standards:test_building_the_docs`. There is a number of references in the docs to old fanstatic-style paths, that are unavailable now. Can you make sure, that mentioned test pass ([Here's](https://docs.ckan.org/en/2.9/contributing/test.html) test configuration in case you haven't configured test instance yet)

**Comment by Gauravp-NEC** [comment]
@smotornyuk ,Thankyou for your response.
I have updated those documents which are referring to the old fanstatic-style paths.

**Comment by smotornyuk** [comment]
Great work. Now everything is fine

**Pull request merged**
