### PR TITLE
Fix "Consider dict comprehensions instead of using 'dict()'" issue

### PR DESCRIPTION
**Pull request by k-nut**
This pull request automatically fixes all occurrences of the following issue:

Issue type: [Consider dict comprehensions instead of using 'dict()'](https://www.quantifiedcode.com/app/issue_class/539Wia7V)
Issue details: [https://www.quantifiedcode.com/app/project/gh:ckan:ckan?groups=code_patterns/%3A539Wia7V](https://www.quantifiedcode.com/app/project/gh:ckan:ckan?groups=code_patterns/%3A539Wia7V)

To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.

Legal note: We won't claim any copyrights on the code changes.

Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)

### CODE REVIEW

**Comment by wardi** [comment]
we need to discuss dropping python 2.6 support

**Comment by TkTech** [comment]
2.7 has been available for 6 years. I think we're past the deprecation cycle.

**Comment by amercader** [comment]
https://lists.okfn.org/pipermail/ckan-dev/2016-January/009608.html

> Starting from the next CKAN 2.6 version, the minimum Python version
required for CKAN will be Python 2.7 (we recommend using the latest
Python patch release).

**Comment by wardi** [comment]
@amercader oh, great! I forgot we had settled that.

**Comment by amercader** [comment]
So who sent this PR, @k-nut or a bot? Because it added a PEP8 error :monkey:

**Comment by TkTech** [comment]
It didn't add a PEP8 error, it fixed the PEP8 errors :)

**Comment by wardi** [comment]
https://github.com/ckan/ckan/blob/master/doc/maintaining/installing/install-from-source.rst could be updated while we're here

**Comment by k-nut** [comment]
I clicked the button to make the bot create a pull request ;) I'll fix the pep8 issue and update this PR.

**Comment by k-nut** [comment]
@wardi there still are some mentions of python2.6 throughout the code. I'll create a new pull request that aims to update eveything to 2.7

```
ckan/__init__.py
3:__version__ = '2.6.0a'

ckan/lib/util.py
13:# subprocess.check_output() isn't in Python 2.6.
15:# Python 2.6.

ckan/model/extension.py
17:        "Replaces stdlib operator.methodcaller in python <2.6"

ckan/tests/helpers.py
36:    # Python 2.6 doesn't have these, so define them here

ckanext/datapusher/tests/test.py
87:        # Httpretty crashes with Solr on Python 2.6,

ckanext/resourceproxy/tests/test_proxy.py
63:        # Httpretty crashes with Solr on Python 2.6,
```

Looks like a couple of backports that will allow us to delete some code 🔥

**Comment by wardi** [comment]
@k-nut that sounds even better!

**Comment by k-nut** [comment]
Closing this in favor of #3125.

**Pull request closed without merging**
