### PR TITLE
#6086 fix sqlalchemy configuration for datastore

### LINKED ISSUE #6086: Datastore: sqlalchemy setting "pool_pre_ping"
**CKAN version**
2.9.x master at 93ef47244b01db097cd65494677296234a4d37d6

**Describe the bug**

The setting "`pool_pre_ping`" for the datastore connection is not working, because of a wrong setting key.  

This is the [code](https://github.com/ckan/ckan/blob/93ef47244b01db097cd65494677296234a4d37d6/ckanext/datastore/backend/postgres.py#L122-L125):
```python
        config.setdefault('pool_pre_ping', True)
        engine = sqlalchemy.engine_from_config(config,
                                               'ckan.datastore.sqlalchemy.',
                                               **extras)
```
Since sqlachemy is told to read config keys with prefix `ckan.datastore.sqlalchemy.`, the setting `pool_pre_ping` will not be taken into consideration.

**Additional details**

This issue is identical to #5932, but related to the datastore engine and not to the main ckan db.

### PR DESCRIPTION
**Pull request by etj**
Fixes #6086

### Proposed fixes:

Fix mistyped configuration key.

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [x] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Review by kowh-ai — APPROVED** [review]
Looks good - Just wondering how you go about testing this config change?

**Comment by pdelboca** [comment]
@kowh-ai @etj this is working as expected and I think it's good to merge. 

If we want, we can test it with a simple unit test in `test_db.py` like the following one:

```python
def test_engine_has_pool_pre_ping():
    engine = db.get_read_engine()
    assert engine.pool._pre_ping == True
```

**Comment by kowh-ai** [comment]
@pdelboca - Great - are you able to merge? - I don't have enough Sprudel

**Comment by amercader** [comment]
Thanks @kowh-ai, this looks good

**Comment by amercader** [comment]
`pool_pre_ping` is SQLAlchemy>=1.2,so not backporting to CKAN 2.8 and 2.7

**Pull request merged**
