### PR TITLE
Catch TypeError from invalid dates thrown by dateutils

### PR DESCRIPTION
**Pull request by kentsanggds**
## Fixes

Problem with catching TypeErrors thrown when an invalid date like `20/062012` and `2014-15` are passed in as date strings.

### Proposed fixes:

Catch TypeError and provide an error log so that devs can investigate any issues.

### Features:

- [X] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [X] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by Zharktas** [comment]
Just to add a note, this due to a bug in dateutil https://github.com/dateutil/dateutil/issues/1108

**Review by Zharktas — APPROVED** [review]

**Comment by amercader** [comment]
@Zharktas this was merged to the `2.9` branch by mistake, can you cherry-pick it to master?

@kentsanggds thanks for your patch, all PRs should target master and we then cherry-pick the changes to the release branches

**Comment by Zharktas** [comment]
Bah, the one time i didn't check that it was done against master, I'll fix it.

**Comment by amercader** [comment]
I wonder if we can configure Github in some way to "only accept PRs against master"

**Pull request merged**
