### PR TITLE
install package data via setup.py

### PR DESCRIPTION
**Pull request by grahame**
### Proposed fixes:

Installation via pip from a local checkout was not installing package data, including '.sql' migrations. this includes installs via pip and a `git+ssh` URL.

This fixes a regression introduced in c1d4dda4d39288ada8872d35323c976690ff4b5e

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by wardi** [comment]
We're using [manifest.in](https://github.com/ckan/ckan/blob/master/MANIFEST.in) file for tracking package data. I hope we don't have to duplicate that. What method of installation are you using?

**Comment by grahame** [comment]
Yes, ideally we wouldn't have to duplicate that configuration.

Steps to reproduce:
```
satsuma:~ $ virtualenv ./test
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/gbowland/test/bin/python2
Also creating executable in /home/gbowland/test/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
satsuma:~ $ . ./test/bin/activate
(test) satsuma:~ $ pip install git+git://github.com/ckan/ckan.git                
Collecting git+git://github.com/ckan/ckan.git
  Cloning git://github.com/ckan/ckan.git to /tmp/pip-GpG5TS-build
Installing collected packages: ckan
  Running setup.py install for ckan ... done
Successfully installed ckan-2.7.0a0
(test) satsuma:~ $ cd test
(test) satsuma:~/test $ find . -name 021_postgres_upgrade.sql            
```

**Comment by rossjones** [comment]
@wardi @grahame The manifest.in ( https://github.com/ckan/ckan/blob/master/MANIFEST.in#L21 ) now contains the migrations, so I think you can safely close this.

**Comment by kmbn** [comment]
We decided to close old pull requests that are not actively worked on so that we can focus our effort and attention on PRs made against the current version of CKAN. A lot has changed in the last several months and many PRs will have gone stale or may now be in conflict with the latest version.

Please note: this isn't a judgement about the quality of your pull request. We just don't have the resources to review older PRs.

If you would like to reopen your PR (and update it if necessary), please do!

**Pull request closed without merging**
