### PR TITLE
Clean old banner logic

### PR DESCRIPTION
**Pull request by pdelboca**
This PR cleans the logic for an old banner. 

Currently there is no logical call to it, the few that exists on templates default to false and no view set that template variable.

### CODE REVIEW

**Comment by pdelboca** [comment]
@Zharktas I fixed the conflict in this one! Feel free to merge whenever you have time :)

**Comment by pdelboca** [comment]
@Zharktas I think we are safe to merge this right?

**Comment by pdelboca** [comment]
@Zharktas polite reminder :)

**Comment by Zharktas** [comment]
@pdelboca sorry for taking so long with this one. There are now old and new templates which both have the old banners, would you remove them from public-bs3 and templates-bs3 as well :)

**Review by Zharktas — APPROVED** [review]

**Pull request merged**
