### PR TITLE
[7914]Fix Core resource_read template relies on Datastore

### LINKED ISSUE #7914: Core resource_read template relies on Datastore
## CKAN version

2.10

## Describe the bug

The datastore plugin provides its own version of the `package/resource_read.html` template if enabled. However, the core template still includes datastore-related logic, checking `datastore_active` and including datastore-specific content if true. As a result, if datastore entries exist but then the datastore is disabled, the resource view page will crash.

### Steps to reproduce

- Create a CKAN instance with datastore enabled.
- Create a resource.
- Create a datastore entry for the resource.
- Disable the datastore plugin.
- Visit the resource.

### Expected behavior

If the datastore plugin is not enabled, then datastore features should simply be ignored.

### Additional details
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

      File "/mnt/local_data/ckan_venv/src/ckan/ckan/templates/package/resource_read.html", line 56, in block 'download_resource_button'
        <a class="dropdown-item" href="{{ h.url_for('datastore.dump', resource_id=res.id, bom=True) }}"
      File "/mnt/local_data/ckan_venv/src/ckan/ckan/lib/helpers.py", line 385, in url_for
        my_url = _url_for_flask(*args, **kw)
      File "/mnt/local_data/ckan_venv/src/ckan/ckan/lib/helpers.py", line 443, in _url_for_flask
        my_url = _flask_default_url_for(*args, **kw)
      File "/usr/lib/ckan/default/lib64/python3.7/site-packages/flask/helpers.py", line 338, in url_for
        return appctx.app.handle_url_build_error(error, endpoint, values)
      File "/usr/lib/ckan/default/lib64/python3.7/site-packages/flask/helpers.py", line 326, in url_for
        endpoint, values, method=method, force_external=external
      File "/usr/lib/ckan/default/lib64/python3.7/site-packages/werkzeug/routing.py", line 2315, in build
        raise BuildError(endpoint, values, method, self)
    werkzeug.routing.BuildError: Could not build url for endpoint 'datastore.dump' with values ['bom', 'resource_id']. Did you mean 'dataset.read' instead?

### PR DESCRIPTION
**Pull request by TomeCirun**
Fixes #7914 

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by ThrawnCA** [comment]
Why not just move the datastore-specific content into `ckanext/datastore/templates/package/resource_read.html`?

**Comment by pdelboca** [comment]
Hey @TomeCirun , we agree with @ThrawnCA . 

Since this is a responsibility of the `datastore` plugin it will be better to move this logic to `ckanext/datastore/templates/package/resource_read.html`

Are you up to fix this? Thanks!

**Comment by TomeCirun** [comment]
Yep, I will do it, thanks @pdelboca @ThrawnCA

**Comment by TomeCirun** [comment]
@pdelboca Done

**Comment by pdelboca** [comment]
@TomeCirun let's keep the condition `{% if res.datastore_active %}` in the new template. That flag is a little bit tricky and not only depends of datastore plugin being active, but also if there is data in the datastore.

Removing it can cause the dropdown to be shown even if there is no data in the datastore.

**Comment by TomeCirun** [comment]
@pdelboca done

**Review by ThrawnCA — APPROVED** [review]

**Comment by pdelboca** [comment]
Thanks @TomeCirun and @ThrawnCA !

**Pull request merged**
