### PR TITLE
4807 remove all remaining pylons code in core

### LINKED ISSUE #4807: Remove all remaining Pylons code in core
This should be done in separate pull requests to make reviews easier

- [x] Remove `requirements.py2.*` files and update documentation to remove py2 mentions
- [x] Remove py2 specific code. Look for `if six.PY2:` and remove what's inside!
- [x] Remove py3 checks. Look for `six.PY3` and make that the standard code run (remove the check if any)
- [ ] Remove usage of six. We should not need the compatibility layer any more. Make all code standard Python 3

This should definitely be done separately

- [ ] Remove unicode literals (eg `my_conf[u"test_key_1"] = u"Test value 1"` -> `my_conf["test_key_1"] = "Test value 1"`

### PR DESCRIPTION
**Pull request by steveoni**
Fixes #4807 

### Proposed fixes:
Remove py2 specific code

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by amercader** [comment]
@steveoni thanks for this. Check the linter failures, there still are some `pylons` usages lying around that need to be removed

**Comment by anuveyatsu** [comment]
Hey @steveoni please ping the reviewer once you think it's ready to review again 👍

**Comment by amercader** [comment]
Sorry @steveoni , some more failures due to dead code

**Comment by steveoni** [comment]
oh ok!. do I need to resolve this from my end? @amercader

**Comment by steveoni** [comment]
@amercader

**Comment by amercader** [comment]
Thanks @steveoni !

**Pull request merged**
