### PR TITLE
[#3076] Removed links in api_info.html

### LINKED ISSUE #3076: Datastore API Demo modal window encourages robots to make needless queries
### CKAN Version if known (or site URL)
2.1 ---> 2.5.2 http://demo.ckan.org/dataset/gold-prices/resource/b9aae52b-b082-4159-b46f-7bb9c158d013

### Please describe the expected behaviour
the CKAN Data API modal window designed to demonstrate the syntax for using the datastore API should not encourage robots to make queries against the database

### Please describe the actual behaviour
the modal window includes hyperlinked text for all resources ...

```
Query example (first 5 results)
http://demo.ckan.org/api/action/datastore_search?resource_id=b9aae52b-b082-4159-b46f-7bb9c158d013&limit=5
Query example (results containing 'jones')
http://demo.ckan.org/api/action/datastore_search?resource_id=b9aae52b-b082-4159-b46f-7bb9c158d013&q=jones
Query example (via SQL statement)
http://demo.ckan.org/api/action/datastore_search_sql?sql=SELECT * from "b9aae52b-b082-4159-b46f-7bb9c158d013" WHERE title LIKE 'jones'
```

These hyperlinks encourage robots - that do not follow robots.txt instructions - to conduct needless queries that result in db errors against all the data resources.

### What steps can be taken to reproduce the issue? 
The modal window  [page template ](https://github.com/ckan/ckan/blob/b7204bb307abb1f488b5d409262db40b1e840d59/ckan/templates/ajax_snippets/api_info.html) should be redone to remove the hyperlinks.

### PR DESCRIPTION
**Pull request by jrods**
Fixes #3076 

### Proposed fixes:
Removing the api link examples to help prevent robots that don't listen to robot.txt from
calling needless querys on the api

I messed up the branch in the original PR: https://github.com/ckan/ckan/pull/3223

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [x] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by jrods** [comment]
> @mattfullerton Also confusing is that this snippet gets inserted as soon as datastore is enabled and independent of whether the data is actually in the datastore:
https://github.com/ckan/ckan/blob/master/ckan/templates/package/resource_read.html#L48

@mattfullerton I'm not sure if I understand, but in the snippet, it checks to see if the resource is active in the datastore: https://github.com/ckan/ckan/blob/master/ckan/templates/package/snippets/data_api_button.html#L7

**Comment by wardi** [comment]
The data_api_button.html should be moved to this new template directory, and the code in resource_read.html:

```html
 {% if 'datastore' in g.plugins %}
    <li>{% snippet 'package/snippets/data_api_button.html', resource=res, datastore_root_url=c.datastore_api %}</li>
 {% endif %}
```

Should be removed and replaced with a resource_read.html template in the datastore extension:

```html
{% ckan_extends %}
{% block resource_actions_inner %}
  {{ super() }}
  <li>{% snippet 'package/snippets/data_api_button.html', resource=res,  datastore_root_url=c.datastore_api %}</li>
{% endblock %}
```

`if 'datastore' in g.plugins` in a core template just seems wrong...

**Comment by jrods** [comment]
@wardi is there any more datastore specific templates that can be moved over that you can think of?

**Comment by wardi** [comment]
none that touch that same code so they can wait. Thank you for tolerating my requests to clean up some of the adjacent code :-)

**Comment by jrods** [comment]
@wardi no problem =)

**Pull request merged**
