### PR TITLE
Fix file replacement bug

### LINKED ISSUE #5102: Uploading a resource with the same name does not update the file contents
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### Please describe the expected behaviour
The uploaded file should replace the previous file

### Please describe the actual behaviour
The uploaded file is lost, and the previous file can only be downloaded

### What steps can be taken to reproduce the issue? 
1) Upload a file called "test.txt"
2) Upload a file called "test.txt" with different contents
3) Download "test.txt" and inspect contents

### PR DESCRIPTION
**Pull request by g-rock**
Fixes #5102

### Proposed fixes:
Invalidates cache by using download attribute

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by smotornyuk** [comment]
Won't this change make user forcibly download content even if the resource does not contain uploaded file, but just links to some external web page instead?

**Comment by g-rock** [comment]
If a user uploads a resource using the "Link" button they will be shown the "Go to Resource" button and not the "Download" button.

**Comment by g-rock** [comment]
Removed the attribute from `resource_view.html` because that button will display regardless of whether the resource is a file, or an URL to some external content.

**Comment by smotornyuk** [comment]
I still disagree. 
1. [This attribute has bad support in ie 11](https://caniuse.com/#search=download). So there still be complains, even though this browser almost never used
2. You are adding this attribute to the link, that has `Download`, `View`, `API Endpoint`, `Go to resource` labels depending on different conditions. But having a `download` attribute will force downloads no matter what user expected to see. This is a bit frustrating. 

I think you should take a look at @mutantsan 's suggestion in the original issue. It's not ideal, as in such a way we'll disable any caching, but it much more stable and explicit. If only we can use something, like the last modification date instead of access time - it would be even better.

**Pull request closed without merging**
