### PR TITLE
Upgrade bundled PDF.js

### PR DESCRIPTION
**Pull request by jqnatividad**
Completes #2193.  Bundled PDF.js upgraded to v1.0.1040.  A lot has changed since PDF.js was bundled June 2013, so dependencies were also upgraded (localization, compatibility.js, etc.) and directory structure was synchronized to PDF.js prebuilt dir structure (http://mozilla.github.io/pdf.js/getting_started/) to ease future upgrades.

Suppressed "Open File." Corrected CSS to show Zoom selector correctly. Enabled "Presentation mode" (full-screen), which required overriding resource_views.html snippet to enable iframe allowfullscreen (see #2230). Suppressed printing because of known pdf.js problem with printing from iframe (https://github.com/mozilla/pdf.js/issues/5397).  Also enabled secondary toolbar with extended controls (Doc properties, rotate, hand control, first/last page, etc.)

### CODE REVIEW

**Comment by amercader** [comment]
Wow, that is one big pull request. I'm slightly weary of adding 400 files to the repo history. Do we actually need all language files and character maps (cmap files) to render correctly?

AFAICT changing the locale in CKAN has no effect on the PDF viewer so maybe we can omit these? (or make them being used).

I have no problem with the actual changes, this is me not knowing how pdf.js works.

**Comment by jqnatividad** [comment]
Hi @amercader, sorry about the delay.  Working on another CKAN extension we're going to release soon - ckanext-discourse for discourse.org integration :)

As for the I10n files, its tightly woven into PDF.js and I'd hesitate to remove it, especially if we plan to upgrade PDF.js later.  What if I changed it so it actually does use the CKAN locale settings, so its at least worth merging in those files?

**Comment by amercader** [comment]
> Working on another CKAN extension we're going to release soon - ckanext-discourse for discourse.org integration :) (ckan/ideas-and-roadmap#44)

Great!

Making the pdf preview use the locale would be nice.

Perhaps now would be a good time to move the pdf view extension to a separate extension to untie it from core?
I'm happy to move things to ckan/ckanext-pdfview as it is now and give you access so you can update the library there. How does this sound?

**Comment by jqnatividad** [comment]
OK @amercader, sounds like a plan.  Its cleaner that way.

**Comment by amercader** [comment]
See #2270 for removal from core and https://github.com/ckan/ckanext-pdfview for the new extension. Once everyone is happy and #2270 is merged I'll close this and announce it.

**Comment by amercader** [comment]
Closing. PDF viewer has been moved to https://github.com/ckan/ckanext-pdfview

**Pull request closed without merging**
