### PR TITLE
GitHub Actions: Use bandit to check security

### PR DESCRIPTION
**Pull request by cclauss**
https://pypi.org/project/bandit

Fixes #

### Features:

- [x] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by Zharktas** [comment]
@cclauss what does bandit actually do ? it would be nice have a description about it without having to read the documentation itself. How does it differ from CodeQL which we already are running on commits ?

And if we would start using this, it should be in its on job and not part of the linting. Linting should not fail due to security issues.

**Comment by cclauss** [comment]
> Bandit is a tool designed to find common security issues in Python code. To do this Bandit processes each file, builds an AST from it, and runs appropriate plugins against the AST nodes. Once Bandit has finished scanning all the files it generates a report. Bandit was originally developed within the OpenStack Security Project and later rehomed to PyCQA.

When was the last time that CodeQL told you something useful?  If your experience is like mine, the answer is never.

Building and running an image takes time and resources so It is not really a good idea to do it separately for each test runner.  I usually stack up tests: https://github.com/cclauss/itinerant-tester/blob/master/.github/workflows/lint_python.yml to avoid repetitive steps.

**Comment by Zharktas** [comment]
Does bandit find anything useful, I find it hard to believe that 15 year old code base would not have any issues but the Action run says there isn't any ?

The CKAN project has a convention of creating an issue and discussing it first especially if the change affects work processes. Now this just seems to be imposed as "you should run this" but it doesn't seem to anything useful for us.

**Comment by cclauss** [comment]
I have landed about 30 PRs on this repo so please hold the lecture.

**Pull request closed without merging**
