### PR TITLE
Mentioning `Express Loader` in DataStore Extension Document

### PR DESCRIPTION
**Pull request by Gauravp-NEC**
This PR fixes the issue: https://github.com/ckan/ckan/issues/4415

### Features:

- [ ] includes tests covering changes
- [x] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by Gauravp-NEC** [comment]
@amercader , Does this PR looks good?

**Comment by Gauravp-NEC** [comment]
@amercader , As the issue https://github.com/ckan/ckan/issues/4415 is label as `To Discuss`, based on my understanding I have raise this PR. Do we need to completely obsolete the `DataPusher` ? Please let me know your opinion on this PR. Thanks :)

**Comment by Gauravp-NEC** [comment]
Gentle reminder!

**Comment by Gauravp-NEC** [comment]
https://github.com/ckan/ckan/issues/8044

**Comment by ThrawnCA** [comment]
Is there anything that the DataPusher does better than XLoader? Offhand I couldn't cite anything.

**Pull request closed without merging**
