### PR TITLE
Image lossless optimization

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Use Google's zopflipng and Mozilla's mozjpeg to re-compress the png and jpg images losslessly.

15 jpg images optimized as below:
```
 ckanext/example_theme/v12_extra_public_dir/public/promoted-image.jpg | Bin 17050 -> 15592 bytes
 doc/images/add_dataset_1.jpg                                         | Bin 105540 -> 97969 bytes
 doc/images/add_dataset_2.jpg                                         | Bin 99576 -> 92472 bytes
 doc/images/add_dataset_3.jpg                                         | Bin 90906 -> 88898 bytes
 doc/images/create_organization.jpg                                   | Bin 130946 -> 121908 bytes
 doc/images/customize_look_and_feel.jpg                               | Bin 83589 -> 77767 bytes
 doc/images/edit_dataset.jpg                                          | Bin 97662 -> 89988 bytes
 doc/images/exploring_datasets.jpg                                    | Bin 123245 -> 114666 bytes
 doc/images/manage_news_feed.jpg                                      | Bin 120015 -> 110951 bytes
 doc/images/manage_organization.jpg                                   | Bin 117404 -> 108754 bytes
 doc/images/manage_user_profile.jpg                                   | Bin 83963 -> 77220 bytes
 doc/images/manage_users.jpg                                          | Bin 30372 -> 29243 bytes
 doc/images/move_dataset_between_organizations.jpg                    | Bin 71949 -> 67194 bytes
 doc/images/register_account.jpg                                      | Bin 97118 -> 89506 bytes
 doc/images/search_the_site.jpg                                       | Bin 140175 -> 131939 bytes
 ```

 89 png images optimized as below:
```
 ckan/public/base/images/background-tag-ie7.png                                                                       | Bin 1486 -> 1271 bytes
 ckan/public/base/images/background-tag.png                                                                           | Bin 2475 -> 993 bytes
 ckan/public/base/images/background-tile.png                                                                          | Bin 1674 -> 225 bytes
 ckan/public/base/images/bg.png                                                                                       | Bin 5683 -> 3911 bytes
 ckan/public/base/images/breadcrumb-slash-ie7.png                                                                     | Bin 3568 -> 3050 bytes
 ckan/public/base/images/ckan-logo-footer.png                                                                         | Bin 625 -> 435 bytes
 ckan/public/base/images/ckan-logo.png                                                                                | Bin 945 -> 626 bytes
 ckan/public/base/images/dashboard-followee-related.png                                                               | Bin 3629 -> 2794 bytes
 ckan/public/base/images/dotted.png                                                                                   | Bin 129 -> 74 bytes
 ckan/public/base/images/editing.png                                                                                  | Bin 322 -> 203 bytes
 ckan/public/base/images/full-width-nav-right.png                                                                     | Bin 166 -> 99 bytes
 ckan/public/base/images/icon-search-27x26.png                                                                        | Bin 1634 -> 318 bytes
 ckan/public/base/images/nav-active.png                                                                               | Bin 290 -> 227 bytes
 ckan/public/base/images/nav.png                                                                                      | Bin 3584 -> 2742 bytes
 ckan/public/base/images/od_80x15_blue.png                                                                            | Bin 1088 -> 163 bytes
 ckan/public/base/images/placeholder-200x125.png                                                                      | Bin 458 -> 435 bytes
 ckan/public/base/images/placeholder-420x220.png                                                                      | Bin 1012 -> 895 bytes
 ckan/public/base/images/placeholder-680x400.png                                                                      | Bin 1888 -> 1532 bytes
 ckan/public/base/images/placeholder-application.png                                                                  | Bin 4696 -> 3772 bytes
 ckan/public/base/images/placeholder-group.png                                                                        | Bin 4950 -> 4033 bytes
 ckan/public/base/images/placeholder-image.png                                                                        | Bin 5611 -> 4663 bytes
 ckan/public/base/images/placeholder-organization.png                                                                 | Bin 4796 -> 3861 bytes
 ckan/public/base/images/sprite-ckan-icons.png                                                                        | Bin 21142 -> 13523 bytes
 ckan/public/base/images/sprite-resource-icons.png                                                                    | Bin 55391 -> 44581 bytes
 ckan/public/base/images/table-seperator.png                                                                          | Bin 136 -> 82 bytes
 ckan/public/base/vendor/bootstrap/img/glyphicons-halflings-white.png                                                 | Bin 8777 -> 8621 bytes
 ckan/public/base/vendor/bootstrap/img/glyphicons-halflings.png                                                       | Bin 12799 -> 12586 bytes
 ckan/public/base/vendor/select2/select2.png                                                                          | Bin 613 -> 577 bytes
 ckan/public/base/vendor/select2/select2x2.png                                                                        | Bin 845 -> 743 bytes
 ckanext/reclineview/theme/public/vendor/leaflet/0.7.3/images/layers-2x.png                                           | Bin 2898 -> 1585 bytes
 ckanext/reclineview/theme/public/vendor/leaflet/0.7.3/images/layers.png                                              | Bin 1502 -> 913 bytes
 ckanext/reclineview/theme/public/vendor/leaflet/0.7.3/images/marker-icon-2x.png                                      | Bin 4033 -> 4032 bytes
 ckanext/reclineview/theme/public/vendor/leaflet/0.7.3/images/marker-shadow.png                                       | Bin 797 -> 681 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/css/smoothness/images/ui-bg_flat_0_aaaaaa_40x100.png           | Bin 180 -> 86 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/css/smoothness/images/ui-bg_flat_75_ffffff_40x100.png          | Bin 178 -> 74 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/css/smoothness/images/ui-bg_glass_55_fbf9ee_1x400.png          | Bin 120 -> 111 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/css/smoothness/images/ui-bg_glass_65_ffffff_1x400.png          | Bin 105 -> 90 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/css/smoothness/images/ui-bg_glass_75_dadada_1x400.png          | Bin 111 -> 102 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/css/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png          | Bin 110 -> 102 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/css/smoothness/images/ui-bg_glass_95_fef1ec_1x400.png          | Bin 119 -> 115 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/css/smoothness/images/ui-bg_highlight-soft_75_cccccc_1x100.png | Bin 101 -> 86 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/css/smoothness/images/ui-icons_222222_256x240.png              | Bin 4369 -> 3687 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/css/smoothness/images/ui-icons_2e83ff_256x240.png              | Bin 4369 -> 3687 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/css/smoothness/images/ui-icons_454545_256x240.png              | Bin 4369 -> 3687 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/css/smoothness/images/ui-icons_888888_256x240.png              | Bin 4369 -> 3687 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/css/smoothness/images/ui-icons_cd0a0a_256x240.png              | Bin 4369 -> 3687 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/images/arrow_redo.png                                          | Bin 572 -> 550 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/images/arrow_right_peppermint.png                              | Bin 128 -> 126 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/images/arrow_right_spearmint.png                               | Bin 128 -> 126 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/images/arrow_undo.png                                          | Bin 578 -> 555 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/images/bullet_blue.png                                         | Bin 241 -> 231 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/images/bullet_star.png                                         | Bin 279 -> 273 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/images/drag-handle.png                                         | Bin 1130 -> 98 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/images/help.png                                                | Bin 345 -> 328 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/images/sort-asc.png                                            | Bin 105 -> 104 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/images/sort-desc.png                                           | Bin 107 -> 106 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/images/stripes.png                                             | Bin 1125 -> 94 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/images/tag_red.png                                             | Bin 537 -> 529 bytes
 ckanext/reclineview/theme/public/vendor/slickgrid/2.2/images/tick.png                                                | Bin 484 -> 465 bytes
 ckanext/reclineview/theme/public/vendor/timeline/css/timeline.png                                                    | Bin 19872 -> 14048 bytes
 ckanext/reclineview/theme/public/vendor/timeline/css/timeline@2x.png                                                 | Bin 49364 -> 36430 bytes
 doc/_static/ckanlogo.png                                                                                             | Bin 1303 -> 312 bytes
 doc/images/9.png                                                                                                     | Bin 98921 -> 71100 bytes
 doc/images/architecture.png                                                                                          | Bin 56408 -> 54096 bytes
 doc/images/ckan_importing_diagram.png                                                                                | Bin 13781 -> 12976 bytes
 doc/images/custom-css.png                                                                                            | Bin 35862 -> 26582 bytes
 doc/images/custom_config_fields.png                                                                                  | Bin 34702 -> 29976 bytes
 doc/images/debug-footer.png                                                                                          | Bin 106636 -> 80570 bytes
 doc/images/example_theme_javascript_popover.png                                                                      | Bin 39066 -> 31011 bytes
 doc/images/example_theme_overlapping_popovers.png                                                                    | Bin 48286 -> 39034 bytes
 doc/images/extra-public-dir.png                                                                                      | Bin 83093 -> 76188 bytes
 doc/images/html_and_css.png                                                                                          | Bin 117293 -> 97270 bytes
 doc/images/image_view.png                                                                                            | Bin 417762 -> 404169 bytes
 doc/images/manage_views.png                                                                                          | Bin 97453 -> 72290 bytes
 doc/images/more-custom-css.png                                                                                       | Bin 287759 -> 216657 bytes
 doc/images/most-popular-groups-custom-snippet.png                                                                    | Bin 85662 -> 60369 bytes
 doc/images/most-popular-groups-snippet.png                                                                           | Bin 143788 -> 120464 bytes
 doc/images/most-popular-groups.png                                                                                   | Bin 25153 -> 17136 bytes
 doc/images/popular-dataset.png                                                                                       | Bin 13589 -> 10855 bytes
 doc/images/popular-resource.png                                                                                      | Bin 14433 -> 11576 bytes
 doc/images/recently-changed-packages-activity-stream.png                                                             | Bin 101362 -> 84013 bytes
 doc/images/recline_graph_view.png                                                                                    | Bin 63764 -> 58463 bytes
 doc/images/recline_grid_view.png                                                                                     | Bin 139829 -> 110501 bytes
 doc/images/recline_map_view.png                                                                                      | Bin 646414 -> 575899 bytes
 doc/images/recline_view.png                                                                                          | Bin 124197 -> 99226 bytes
 doc/images/sort-datasets-by-popularity.png                                                                           | Bin 89653 -> 62447 bytes
 doc/images/text_view.png                                                                                             | Bin 164787 -> 132723 bytes
 doc/images/views_overview.png                                                                                        | Bin 148515 -> 116516 bytes
 doc/images/webpage_view.png                                                                                          | Bin 554051 -> 347511 bytes
```

### CODE REVIEW

**Comment by deinok** [comment]
@PeterDaveHello Please, rebuild the CircleCI Test

**Comment by PeterDaveHello** [comment]
@deinok I don't have permission to rebuild it on Circle CI, would you please help me rebuild it? Thanks.

**Comment by deinok** [comment]
@PeterDaveHello @wardi triggered for you ;)

**Comment by PeterDaveHello** [comment]
Test passed!

**Comment by wardi** [comment]
How are the jpegs recompressed losslessly?

**Comment by PeterDaveHello** [comment]
Just keep the same pixel but use a better encode to record them.

**Pull request merged**
