### PR TITLE
Update ckan.po

### PR DESCRIPTION
**Pull request by Atharex**
Updated the ckan.po for slovenian translations

### CODE REVIEW

**Comment by joetsoi** [comment]
@amercader sorry to dump this one on you, you can feel free to reassign to me if you just tell me what to do with it, either direct to transifex, or whatever

**Comment by amercader** [comment]
@Atharex Can you upload your updated po file to Transifex? This way your changes will get pulled when we update the translations before 2.4 (and it will be later merged to master)

https://www.transifex.com/projects/p/ckan/resource/2-4/

Thanks

**Comment by Atharex** [comment]
Sure, it should be on Transifex now.

**Comment by amercader** [comment]
Thanks very much @Atharex, your strings are merged as part of 8dd053e994b324d6e4ae6ad84bdc1d5f9006b7b9

**Pull request closed without merging**
