### PR TITLE
Update sqlalchemy to 1.3.3

### PR DESCRIPTION
**Pull request by frafra**
Fixes: #4736 
Related to: https://github.com/ckan/ckan/pull/4763#issuecomment-490235987

### CODE REVIEW

**Comment by frafra** [comment]
https://github.com/okfn/vdm/ seems unmaintained. There is a branch for sqlalchemy 1.1, but not for 1.2.

**Comment by amercader** [comment]
Thanks @frafra. Should we aim for SQLAlchemy 1.3 if we are upgrading?
And yes VDM is unmaintained but it will need to be updated to support SA 1.3 otherwise it will throw an error.
I've just uploaded vdm==0.15 to Pypi which should allow to run on SA 1.3. Can you update the requirement on `requirements.in` and `requirements.txt` and see how the tests look?

**Comment by frafra** [comment]
Updated to 1.3.3.

**Comment by amercader** [comment]
@frafra there is work being done in the same front by @iamarnavgarg on #4782 
Is it ok if I close this PR?

**Comment by frafra** [comment]
Sure!

**Pull request closed without merging**
