### PR TITLE
Fix to allow multiple tags in a single dataset search

### PR DESCRIPTION
**Pull request by hardingalexh**
Fixes #
In the current version of the dataset search screen, applied tag facets are not displayed past the first facet applied.

This is because the params/args present on the request are `MultiDict`, and they are being accessed using `items()`, which only returns the first value for each key. Passing in the `multi=True` arg to `items()` allows for multiple series for a given key, which solves this problem.

Previous Behavior (check URL)
Screen Shot 2019-04-30 at 2 39 33 PM

Fixed behavior:
Screen Shot 2019-05-01 at 2 40 14 PM

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by amercader** [comment]
Thanks for this @hardingalexh. We should add a test to prevent the bug from creeping up again in the future. Something inspired in [this one](thttps://github.com/ckan/ckan/blob/master/ckan/tests/controllers/test_package.py#L1510) should be easy to write.
Also if you check the CircleCI failures there is a PEP8 formatting error: 

```
-------------------
ckan/lib/helpers.py
-------------------
E501 ln:1836 line too long (88 > 79 characters)
E501 ln:1871 line too long (88 > 79 characters)
```

Do you know the CKAN version this bug was introduced?

**Comment by hardingalexh** [comment]
Thanks @amercader - fixed the pep8 failure.

Not entirely sure when this was introduced, I've only been using CKAN since ~January and I believe the bug has been around since then. Could do some detective work to step back through this if you'd like.

**Comment by amercader** [comment]
@hardingalexh don't worry, I'll dig out the version it was introduced. If you can write the test I'll merge this.

**Comment by hardingalexh** [comment]
@amercader added a test to make sure that the correct number of tag pills show up for a filtered query. Not sure what's going on with the travis build - any thoughts there?

**Comment by amercader** [comment]
Don't worry about the travis failures, these are unrelated. Great work @hardingalexh , thanks for your patch

**Pull request merged**
