### PR TITLE
Add Python 3.6 to Travis CI

### PR DESCRIPTION
**Pull request by cclauss**
Helps with #4060

### Proposed fixes:
Add Python 3.6 to Travis CI ~in allow_failures mode~ while keeping all Python 2.7 processing in tact.

### Features:
- [x] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by cclauss** [comment]
@deinok My sense is that this change (with or without __allow_failures__) lets us sidestep #4213 and jump straight to step 7 of #4060  Your thoughts?

**Comment by deinok** [comment]
ref: #4060 
I need confirmation from the mantainers in order to continue fixing the CI related issues.
Also, I think first, we should test python3 outside docker image

**Comment by deinok** [comment]
But the travis change LGTM. Probably at some point we are going to add it as a Job in CircleCI

**Comment by cclauss** [comment]
I thought that #4213 was that confirmation.

**Comment by deinok** [comment]
@cclauss I'm not sure, but a confirmation of the Roadmap in #4060 from @amercader would be ok.

**Comment by cclauss** [comment]
@amercader Your review please?

**Comment by amercader** [comment]
@cclauss sorry this got sidelined a bit. As I understand it this is a mechanism to make sure non py3-incompatible changes slide into the code until the proper support is in place.

As it has been a while are there any changes needed before merging?

**Pull request closed without merging**
