### PR TITLE
Modernize Python 2 code to get ready for Python 3

### LINKED ISSUE #3309: Python 3 support (OLD)
Add Python 3 support.

[Python 2.7 support will end in 2 years](https://pythonclock.org/).

- [x] add Python 3 support to [ofs](https://pypi.python.org/pypi/ofs) and [pairtree](https://pypi.python.org/pypi/Pairtree): ~https://github.com/okfn/ofs/pull/14~, ~https://github.com/benosteen/pairtree/pull/2~
- [ ] remove [ofs](https://pypi.python.org/pypi/ofs) and [pairtree](https://pypi.python.org/pypi/Pairtree), they were needed by the old Filestore.
- [ ] replace Pylons with Flask: ckan/ckan#3119
- [x] remove [ordereddict](https://pypi.python.org/pypi/ordereddict)
- [ ] remove [ofs](https://pypi.python.org/pypi/ofs) and [pairtree](https://pypi.python.org/pypi/Pairtree) dependencies as they are no longer used
- [ ] migrate away from vdm or add Python 3 support to vdm since getting rid of vdm seems like a not an easy task, okfn/vdm#13
- [ ] replace [webhelpers](https://pypi.python.org/pypi/WebHelpers) with a modern alternative
- [ ] replace [repoze.who-friendlyform](https://pypi.python.org/pypi/repoze.who-friendlyform) with a modern alternative
- [ ] add Python 3 support to the ckan own code base
- [ ] Replace Paste with Click #4639

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #3309 (PARTIAL FIX!!)

Make the minimal, safe changes required to convert the repo's code to be syntax compatible with both Python 2 and Python 3. There would _definitely_ be more work required to complete the port to Python 3 but this is a minimal, safe first step.

Run: `futurize --stage1 -w **/*.py`  # done in zsh for ** globbing

See Stage 1: "safe" fixes http://python-future.org/automatic_conversion.html#stage-1-safe-fixes

$ `pip install future`
$ `git checkout -b modernize-python2-code`
$ `futurize --stage1 -w **/*.py`  # done in zsh for ** globbing
$ `git commit --all -m "Modernize Python 2 code to get ready for Python 3"`
$ `git push --set-upstream origin modernize-python2-code`

### CODE REVIEW

**Comment by wardi** [comment]
@cclauss thanks, but this sort of change creates noisy merge conflicts and would be better done only when working on one of the affected files (or just before we've moved off pylons).

**Comment by cclauss** [comment]
Please consider removing the __Good for Contribution__ label from issue #3309 because clearly, it is not.

**Comment by wardi** [comment]
@cclauss we absolutely want help with Python 3 support. Automated changes to the source in code that is going to be removed or modified just isn't what we need at this time.

**Comment by cclauss** [comment]
#3309 has been open for going on one year and not one of the PRs related to it has ever been merged.  Automated solutions are not all bad.

**Comment by wardi** [comment]
Here's the progress on our Flask migration, which is the largest issue blocking Python 3 support right now: https://github.com/ckan/ckan/pulls?q=label%3A%22Pylons+-+Flask+migration%22+is%3Apr

There has been some progress on removing vdm too, we just need some help adding tests. The other changes mentioned in #3309 are good for contribution as well.

**Pull request closed without merging**
