### PR TITLE
support non root for fanstatic

### PR DESCRIPTION
**Pull request by fanjinfei**
Fixes #
https://github.com/ckan/ckan/issues/3618
Non root CKAN generates broken link for fanstatic resources 
### Proposed fixes:
add base_url to fanstatic config

### Features:

- [x] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [X] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by wardi** [comment]
@fanjinfei would you add a small test that sets the site_root and generates a fanstatic url so that this doesn't break in the future?

**Comment by fanjinfei** [comment]
@wardi I did not touch `Package` code. Why would test_package.py:TestRelatedRevision fail here?

**Comment by tino097** [comment]
@fanjinfei it looks its CircleCI error
https://status.circleci.com/

**Comment by fanjinfei** [comment]
It looks like the `config` is not restored properly.

**Comment by wardi** [comment]
@fanjinfei try using the change_config helper instead

**Comment by wardi** [comment]
@amercader this works for us and the original reporter of #3618

**Comment by amercader** [comment]
Backported to 2.7

**Comment by Engerrs** [comment]
Hi @amercader, can those fix be backported into 2.6?

**Comment by vaquer** [comment]
Hi @amercader this fix was backported into 2.6? I still having this issue with the branch `release-v2.6-latest` 😞

**Comment by surendhar22** [comment]
Hi @amercader is this fix ported over to CKAN 2.9? The issue seems to be still persisting in the later versions.

**Pull request merged**
