### PR TITLE
Add conf file containing non-ascii characters

### LINKED ISSUE #6336: CKAN won't start if properties have accents in the ini config file
**CKAN version**
2.9.3

**Describe the bug**
Ckan won't start if is set ckan.title or ckan.description has accents.

**Steps to reproduce**

1. In the ckan.ini configuration file set ckan.title = "Catálogo de datos abiertos"
2. Restart/Reload Apache
3. Try to access the ckan web page --> Server Error 500
4. Take a look to the log output

**Expected behavior**
CKAN will start independent of the text set in the ckan.title and ckan.description.

**Additional details**

I think the error comes from this library in the Apache WSGI config file:
`from logging.config import fileConfig as loggingFileConfig
`

Log output:

> Traceback (most recent call last):
  File "/..path../ckan/default/apache.wsgi", line 17, in <module>
    loggingFileConfig(config_path)
  File "/usr/lib/python3.6/logging/config.py", line 74, in fileConfig
    cp.read(fname)
  File "/usr/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 564: ordinal not in range(128)

### PR DESCRIPTION
**Pull request by frafra**
Fixes #6336

### Proposed fixes:

Adds support for conf file containing non-ascii characters.

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by frafra** [comment]
@quinoescobar could you please test this patch?

**Comment by quinoescobar** [comment]
> @quinoescobar could you please test this patch?

Sure,  😄

**Comment by quinoescobar** [comment]
> @quinoescobar could you please test this patch?

Hi Fran

I tried it and i got this error message:

> mod_wsgi (pid=33290): Failed to exec Python script file '/path/apache.wsgi'.
mod_wsgi (pid=33290): Exception occurred processing WSGI script '/path/apache.wsgi'.
Traceback (most recent call last):
  File "/path/apache.wsgi", line 19, in <module>
    config = CKANConfigLoader(config_path).get_config()
  File "/path/src/ckan/ckan/cli/__init__.py", line 24, in __init__
    self._create_config_object()
  File "/path/src/ckan/ckan/cli/__init__.py", line 46, in _create_config_object
    self._read_config_file(use_config_path)
  File "/path/src/ckan/ckan/cli/__init__.py", line 33, in _read_config_file
    self.parser.read(filename)
  File "/usr/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.8/configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.8/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 515: ordinal not in range(128)

I implemented the changes of this commit and setted the title to Catálogo, restared the service and reload the app.

Without changing the title to containing a non-ascii character I got this error message:

> mod_wsgi (pid=31615): Failed to exec Python script file '/path/apache.wsgi'.
mod_wsgi (pid=31615): Exception occurred processing WSGI script '/path/apache.wsgi'.
Traceback (most recent call last):
  File "/path/apache.wsgi", line 21, in <module>
    loggingDictConfig(config)
  File "/usr/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.8/logging/config.py", line 496, in configure
    raise ValueError("dictionary doesn't specify a version")
ValueError: dictionary doesn't specify a version

And after adding a version property in the ckan.ini, no matter what number of version I set always got this error message:

> mod_wsgi (pid=32974): Failed to exec Python script file '/path/apache.wsgi'.
mod_wsgi (pid=32974): Exception occurred processing WSGI script '/path/apache.wsgi'.
Traceback (most recent call last):
  File "/path/apache.wsgi", line 21, in <module>
    loggingDictConfig(config)
  File "/usr/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.8/logging/config.py", line 498, in configure
    raise ValueError("Unsupported version: %s" % config['version'])
ValueError: Unsupported version: 3

**Comment by frafra** [comment]
Ok, thank you! I will try to fix that then :)

**Comment by frafra** [comment]
Ok, I see, there are two different files for wsgi, one stored in `contrib/docker/apache.wsgi`, which is the one you are using, and one is the usual `wsgi.py`, which I patched.

I am not sure why `apache.wsgi` is there, and I think it should be removed, probably.
Have you tried to use `wsgi.py` with my patch instead?
The main difference I see is that the regular `wsgi.py` does not enable the virtual environment, which should not be an issue if you use the Python interpreter located in it.

**Comment by quinoescobar** [comment]
I'm using the wsgi.py but it's renamed to apache.wsgi in the CKAN installation

**Comment by pdelboca** [comment]
Closing due to inactivity and as a general cleanup of our PR. Please re-open if you consider it is still relevant. Thanks!

**Pull request closed without merging**
