### PR TITLE
[fix] data api showing datastore_search_sql #7289

### PR DESCRIPTION
**Pull request by svetozarstojkovicdatopian**
Fixes #

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [x] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### Description
1. Added new helper function to read config `ckan.datastore.sqlsearch.enabled` in `helper.py` 
2. Added new plugin variable to `plugin.py`
3. Added new condition to show/hide api endpoint and example in data api modal.

### CODE REVIEW

**Review by tino097 — CHANGES_REQUESTED** [review]
@svetozarstojkovicdatopian PR looks great, however you are trying to merge against `2.9` branch and it should be `dev-v2.9`. Also, is there any reason for this PR not to be merged in `master` branch ?

**Comment by svetozarstojkovicdatopian** [comment]
@tino097 I changed the destination to dev-2.9.
I wasn't aware of what is the protocol here so that's why I didn't merge to master.

Do we have a procedure explained somewhere that I can read?

Thanks,
Svetozar

**Comment by tino097** [comment]
@svetozarstojkovicdatopian usualy this type of fixes/improvments we merge in master and if the change applies for backport we are cherrypicking the commit into relevant branch. 
So i believe you could switch this PR to master and we can backport it to dev-2.9 or dev-2.10 for the next patch releases

**Comment by tino097** [comment]
@svetozarstojkovicdatopian i would suggest to create new PR that will be branched from `master` and we can merge it

**Comment by svetozarstojkovicdatopian** [comment]
Will be solved through https://github.com/ckan/ckan/pull/7403

**Pull request closed without merging**
