### PR TITLE
Fix Postgres healthcheck

### PR DESCRIPTION
**Pull request by frafra**
Partial fix for #4715

### CODE REVIEW

**Comment by amercader** [comment]
Can you explain the reasoning behind this change @frafra ?

**Comment by frafra** [comment]
Sure @amercader :-)

Here is the error you get from the health check if you run `docker-compose up`:
```FATAL: role "postgres" does not exist```

This happens because the users used by the health check is wrong: the user used by the ckan container is `ckan`, not `postgres`:
https://github.com/ckan/ckan/blob/aa1442cdea0d414a314285151d265b7f719bed81/contrib/docker/docker-compose.yml#L26

**Comment by davidread** [comment]
My understanding is that the default user is `postgres` so that should always work, but `ckan` should be fine too. Both work for me locally. So I'm not clear why this PR would help. Especially when the error message is about a *role*, rather than the *user* being changed in the PR. 🤷‍♂ 

BTW I tried docker-compose on this branch but get another unrelated error - a 404 for SOLR. But I'm not hugely familiar with this area, so I probably did something wrong...

**Comment by frafra** [comment]
I can confirm that this patch fixes the issue, while keeping "postgres" make it fail. Bear in mind that we could have been using different Postgres images/versions due to the fact that there is no tag specified at the moment on the Dockerfile.

**Comment by davidread** [comment]
I tried again and can reproduce this exact error, as per the issue:
```
cd contrib/docker
cp .env{.template,}
docker-compose up --build --exit-code-from ckan
```
 I'm still not sure why postgres user isn't there, but happy to just have it merged to fix this. I'll leave it to @amercader to decide as he's assigned.

We should really have CI if we're going to maintain this.

**Comment by frafra** [comment]
Ok, it looks like there is a difference between the Docker image on Dockerhub and the one you can generate from the repository: the first uses postgresql as user, the latter uses ckan.

**Comment by davidread** [comment]
Good find. [Dockerhub currently has a release](https://hub.docker.com/r/ckan/postgresql/builds) of: https://github.com/ckan/ckan/blob/60b98f932629acf67428c445a4e3d79fed495912/contrib/docker/postgresql/Dockerfile which is 3 years old. Sounds like someone with admin rights to https://hub.docker.com/u/ckan should setup autobuild, to ensure it doesn't diverge in future. This is probably a topic to take off line.

I'm keen to see this PR merged whatever.

**Comment by markstuart** [comment]
@frafra @davidread what is needed to get this over the line? I'm keen to have this fix in as part of the work in #5381 , it'd be nice if the db logs weren't filling up with errors from the health check call :+1:

**Comment by markstuart** [comment]
Thanks @amercader 😁

**Pull request merged**
