### PR TITLE
Update api_info.html

### LINKED ISSUE #5276: DataStore: "Further information in the main CKAN Data API and DataStore documentation" poorly translatable
### Please describe the expected behaviour
The first paragraph in the dialog brought up by clicking the green "Data API" button from a resource which uses the DataStore (such as [this one](https://demo.ckan.org/fr/dataset/test-this-now/resource/66029d0b-2a3c-4365-bed4-cbe9a6a6685c)) ends with the following sentence:

> Further information in the main CKAN Data API and DataStore documentation.

This sentence should be found in the ckan.po translation file.

### Please describe the actual behaviour
Rather than just that sentence, ckan.po contains:
```
#: ckanext/datastore/templates/ajax_snippets/api_info.html:26
msgid ""
" Further information in the <a             "
"href=\"http://docs.ckan.org/en/latest/maintaining/datastore.html\" "
"target=\"_blank\">main CKAN Data API and DataStore documentation</a>.</p> "
```
That is, there are superfluous spaces before and after the sentence, and there are superfluous spaces and newlines inside the opening A tag.

### What steps can be taken to reproduce the issue? 
1. Enable the DataStore
1. Add a tabular resource, such as a CSV file, in the DataStore
1. Access the resource
1. Press the button to show the Data API modal

---

The sentence starts at [line 26 of api_info.html](https://github.com/ckan/ckan/blob/master/ckanext/datastore/templates/ajax_snippets/api_info.html#L26). This sentence was previously translated to French, but it was lost (except when using the Bootstrap 2 template) after the file was reindented in [revision 369db2d0e5a3205f6fc1c97ead666ee1ae1740ef](https://github.com/ckan/ckan/commit/369db2d0e5a3205f6fc1c97ead666ee1ae1740ef) (the sentence is duplicated in the French ckan.po starting from revision 97544fa417baf0dbdca653c58b0767518ea79e9c).

To ease translation and ensure that translations are not frequently lost, the template could use _trans_'s _trimmed_ to that superfluous whitespace does not pollute translation templates and cause unnecessary duplication.

### While we're at it
1. This may be a good occasion to change the problematic "sentence" into an actual sentence (one with a verb).
1. It also looks like what used to be called "the Data API" is now called "the DataStore API".
1. I suppose it would be best to link to the version of the documentation for the linking CKAN instance rather than to "latest" all the time. For example, for 2.4.1, link to https://docs.ckan.org/en/ckan-2.4.9/maintaining/datastore.html. So replace "latest" with a variable which keeps the string constant.

### PR DESCRIPTION
**Pull request by Gauravp-NEC**
Fix for issue 5276

Fixes #5276 

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by Gauravp-NEC** [comment]
@amercader , Please review this PR.  Thankyou :)

**Comment by Gauravp-NEC** [comment]
@amercader , Please review this PR. If it looks good please merge it. Thanks :)

**Comment by Gauravp-NEC** [comment]
@amercader , Please review this PR. Thankyou :)

**Comment by amercader** [comment]
Thanks @Gauravp-NEC , please see https://github.com/ckan/ckan/issues/5276#issuecomment-760952133

**Pull request closed without merging**
