### PR TITLE
Search index rebuild takes a while; let's give it a progress counter

### PR DESCRIPTION
**Pull request by deniszgonjanin**
Search index rebuild can take an hour or two when you have many thousands of datasets. This PR shows a simple counter, so that the user can get a little bit of feedback on the progress, and know that the rebuild isn't stuck somewhere.

### CODE REVIEW

**Comment by davidread** [comment]
This is neat! Could you add a --quiet option for when this is run in build scripts?

Ian says there's an off-by-one error too ;-)

**Comment by deniszgonjanin** [comment]
Heh, yes there is

**Comment by deniszgonjanin** [comment]
Should be good to go

**Comment by davidread** [comment]
This is great. Creating new PR with a minor test fix: #2645

**Pull request closed without merging**
