### PR TITLE
commented statement in legacy test for coding standards

### PR DESCRIPTION
**Pull request by tino097**
Small fix for commented line in the 
`/ckan/ckan/tests/legacy/test_coding_standards.py` which was merged with #4069

### CODE REVIEW

**Comment by tino097** [comment]
@amercader i think we should remove `/ckan/ckan/tests/legacy/functional/api/model/test_licenses.py` 
as it passes pep8 but it is blacklisted and it is pointing to rest endpoint. Any objection on the removal ?

**Comment by amercader** [comment]
sounds good, let's remove it

**Comment by wardi** [comment]
@tino097 the pep8 failure needs to be fixed on this one

**Comment by tino097** [comment]
@wardi its fixed now

**Pull request merged**
