### PR TITLE
Some links in CKAN is not reachable

### PR DESCRIPTION
**Pull request by amercader**
### CKAN Version if known (or site URL)

for example:

Configuration File:

http://docs.ckan.org/en/latest/maintaining/CKANconfigurationfile

Environmental Variables:

http://docs.ckan.org/en/latest/maintaining/env-vars-wikipedia

### Please describe the expected behaviour

Expect link to related documents.

### Please describe the actual behaviour

Page not found.

### CODE REVIEW

**Comment by amercader** [comment]
Thanks @bwanglzu fixed now. Let us know if you find any other broken link or better yet fix them yourself as in d3f6eaa and send a PR!

**Comment by bwanglzu** [comment]
no problem~

**Comment by smotornyuk** [comment]
I found few additional broken links

 **Changelog:**
- http://docs.ckan.org/en/latest/changelog.html#v2-2-2014-02-04 - link to filestore under *API changes and deprecations* section
- http://docs.ckan.org/en/latest/changelog.html#v1-2-2010-11-25 - links to v1.2, v1.1, v1.0 and v0.11 milestones and link to http://www.ckan.net near link to v0.11 milestone. Probably, they should be removed

**Contributing**

- making a pull request: 
  * *Testing CKAN* link

- Writing documentation 
  * Style
    * Section titles
      * *link to Django content*

- CSS coding standards:
  * Front-end Documentation

- JavaScript coding standards:
  * AJAX
    * CKAN Client
  * Testing:
    * Mocha

- Python coding standards:
  * Sphinx field lists
  * Python Coding Standards from Yahoo

**Theming**
- customizing templates
  * HTML tags and CSS classes:
    *link to Bootstrap documentation
- customizing javascript
  * jQuery plugins
    *Immediately-Invoked Function Expression (IIFE) 
- Template helpers
  * broken description of ckan.lib.helpers.html_auto_link

**Extending**
- internationalization
  * Manually create translations
    * init_catalog
- Plugin interfaces
  * IMapper
    * link to sqlalchemy
- Making configuration options runtime-editable
  * configuration file 

**Maintainer**
  * datastore
    *datastore_search_sql:
      *link to postgres
    * datastore_make_public
      *CSV link

**Comment by amercader** [comment]
@smotornyuk wow, great work. Do you want fix some of these in a separate PR?  I'll merge this one.

**Comment by smotornyuk** [comment]
Yes, i've just did it and going to create pull request

**Comment by amercader** [comment]
@smotornyuk did you send the PR for this?

**Pull request merged**
