### PR TITLE
add icons and css adoption

### PR DESCRIPTION
**Pull request by hknochi**
Fixes #
add a Icon to ckan/public/base/images/sprite-resource-icons.png (in ckan-style) to get shown an icon for image resources
add  rules in main.css to get shown the icon in UI (resource-view)

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [x ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by seebi** [comment]
:+1:

**Comment by amercader** [comment]
@hknochi This is great, but could you target the master branch instead of 2.2.3?
Also it will be great if you could include the original vector files on the repo so we don't need to dig them out next time they are needed

**Comment by espona** [comment]
The new sprite-resource-icons.png does not display as good as previous. The background is not transparent. Is there any possibility to get the vector file? Thanks!

**Comment by amercader** [comment]
@espona You can find the vector version of the icons in this repo: https://github.com/ckan/ckan-assets

**Pull request closed without merging**
