### PR TITLE
mark template blocks to allow better extensibility

### LINKED ISSUE #4949: Improve extensibility of the 'user form' template
### CKAN Version if known (or site URL)

2.8.x

### Please describe the expected behaviour

As a developer of extensions, I expect to extend/override specific parts of the template at `ckan/templates/user/edit_user_form.html` be possible and easy, without needing to copy the whole original code. 

For instance, in the context of a deploy that uses LDAP as access protocol, I'd like to hide/remove the password related fieldset because it has no point. 

### Please describe the actual behaviour

It is not possible to extend  because there is no proper blocks

### PR DESCRIPTION
**Pull request by mgaitan**
Fixes #4949 

### Proposed fixes:

added several block tags that wrap different parts of the template, whitout change logic nor markup.

### CODE REVIEW

**Comment by tino097** [comment]
@mgaitan can you please resolve the conflicting file
thanks

**Comment by Gauravp-NEC** [comment]
@mgaitan , Are you working on this PR?
@tino097 , It looks like **mgaitan** is inactive for more than 2.5 years. Can I resolve the conflict of this PR? Please let me know your opinion. Thanks

**Comment by tino097** [comment]
@Gauravp-NEC go on, but please have in mind that there were few changes from the time this was originally submitted. Also apply same changes for BS3 template

**Comment by Gauravp-NEC** [comment]
> @Gauravp-NEC go on, but please have in mind that there were few changes from the time this was originally submitted. Also apply same changes for BS3 template

@tino097 , Based on your approval and suggestion I have raised the PR https://github.com/ckan/ckan/pull/6876

**Comment by Gauravp-NEC** [comment]
@tino097 , I think now this PR can be closed in favour of PR https://github.com/ckan/ckan/pull/6876

**Pull request closed without merging**
