### PR TITLE
Deleting a dataset sends IResourceController.before_delete

### LINKED ISSUE #4705: Problems when deleting resources
*Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
2.9.0a.
 
### Please describe the expected behaviour

If I call resource_delete or purge package in admin page,
The resources in file store must be deleted together if the resource is deleted,
If the resource's datastore_active is true, the resource is deleted from the datastore.
but the deleted resource remains.

### Please describe the actual behaviour

Resources in file store and datastore are not deleted when I call resource_delete or purge package from the admin page.

### What steps can be taken to reproduce the issue? 

When deleting a revision associated with a package in views.admin, If there is resource in the file store or datastore, delete it together.

### PR DESCRIPTION
**Pull request by davidread**
Although it doesn't actually delete the resources, because when a
sysadmin views the deleted dataset it should show with those resource,
and they wouldn't show up if we set their state=deleted.

This fixes #4705 by sending the IResourceController.before_delete events
necessary for Datastore and FileStore to get rid of the associated data.

I think this is a better option compared to deleting the resources, which can be seen in alternate PR https://github.com/ckan/ckan/pull/4904

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by iamarnavgarg** [comment]
Hi @davidread , the code changes done by you seems to disassociate the resources with the plugins such as datastore. Can you please explain the reasons for keeping the resources even if the package is deleted and is likely to be purged.?

**Comment by davidread** [comment]
> explain the reasons for keeping the resources even if the package is deleted and is likely to be purged.?

Yes, after you have done package_delete, dataset.state=deleted and resources.state=active. The dataset can still be viewed by a sysadmin, which is useful for understanding what was deleted.

If the resource is also deleted, i.e. dataset.state=deleted and resources.state=deleted, when the sysadmin views it, the dataset will show without any resources. I don't think this is helpful, and was the view of the tech team many years ago.

However this seems the right time to tell datastore etc that the resources are deleted. (Better than if a dataset/resources are purged.)

**Comment by iamarnavgarg** [comment]
Hi @davidread, In the fix of #4867 (Line 186) we try to implement the similar behaviour as stated by you, wherein, the resource.state='deleted' are still visible when dataset.state=deleted. The criteria that the sysadmin should be able to view the resources associated with the dataset is fulfilled. Thus, when the purge button is pressed, then only the associated resources get deleted. So, as per my understanding this is expected behaviour. Please let me know your opinion on this @davidread ?

**Comment by amercader** [comment]
I think the issue with keeping the resources in `state=active` is that then the Datastore won't delete the associated table, if I'm reading this code correctly:

https://github.com/ckan/ckan/blob/master/ckanext/datastore/plugin.py#L151:L154

I wonder if the potential issue of sysadmins looking at deleted datasets and not seeing the resources will get invalidated with the new activity streams? IIUC the new activities store the full dataset dict so that would contain the resources. So an admin could look at this old "revision" or version. Maybe there's not a UI for this or maybe that's not how it works.

**Comment by amercader** [comment]
Also perhaps it also makes sense to call `IResourceController.before_delete/after_delete` on `dataset_purge`? AFAICT it's not calling `package_delete` but it would be also good to trigger the files/tables deletion on purge as well right?

**Comment by iamarnavgarg** [comment]
> I think the issue with keeping the resources in `state=active` is that then the Datastore won't delete the associated table, if I'm reading this code correctly:
> 
> https://github.com/ckan/ckan/blob/master/ckanext/datastore/plugin.py#L151:L154
> 
> I wonder if the potential issue of sysadmins looking at deleted datasets and not seeing the resources will get invalidated with the new activity streams? IIUC the new activities store the full dataset dict so that would contain the resources. So an admin could look at this old "revision" or version. Maybe there's not a UI for this or maybe that's not how it works.

Can you please elaborate more on this ? And is it related to fix **4867** ?

**Comment by pdelboca** [comment]
Closing due to inactivity. Please reopen it if you consider it is still relevant. Thanks!

**Pull request closed without merging**
