### PR TITLE
Docker install archived

### PR DESCRIPTION
**Pull request by davidread**
Fixes issue #2820

### CODE REVIEW

**Comment by wardi** [comment]
@davidread there's no longer a company supporting datacats. I still use it every day, but I don't have time to keep up with docker API breakage, OSX support etc. Let's just say the existing docker images are not maintained and docker installation is not supported by us for now.

**Comment by davidread** [comment]
Ok, how's this?

**Comment by dersteppenwolf** [comment]
Big trouble. 
Probably datacats it is the only way for new users to run ckan. 
(BTW, awesome work...)

And looking to the official docs...http://docs.ckan.org/en/latest/maintaining/installing/index.html?highlight=docker
> There used to be an ‘official’ Docker install of CKAN. There are legacy docker images at https://hub.docker.com/u/ckan/ which are not maintained ...

Therefore... we are on our own... 
I tried to build the  images using datacats https://github.com/datacats/datacats/blob/master/docker/build_images.sh  but it fails.
 the "latest" (ckan 2.5?)  tag doesn't work.

Looks like a perfect time for a fork.

**Comment by davidread** [comment]
> Probably datacats it is the only way for new users to run ckan. 

Nope, there are excellent instructions for source install and also ubuntu package.

> Looks like a perfect time for a fork [of datacats]

Yeah the norm is for each developer to create a personal fork, do each fix on a branch and create Pull Requests to get it merged into the main-line for everyone's benefit.

**Pull request merged**
