### PR TITLE
#2870: require password when changing email

### PR DESCRIPTION
**Pull request by Zharktas**

### CODE REVIEW

**Comment by rossjones** [comment]
Should be assigned to @smotornyuk once ready.

**Comment by smotornyuk** [comment]
@Zharktas , in case of applying this PR, user become unable to change any information without password verification. Probably, you should check if email had been changed in addition?

**Comment by Zharktas** [comment]
@smotornyuk True, I thought I checked that it would only used with changing email, but apparently not. Will change it to check for modifications of email instead.

**Comment by smotornyuk** [comment]
Thanks, i think that completed. @rossjones , can it be merged now?

**Comment by rossjones** [comment]
@smotornyuk Ideally we'd have a test, but if you or @Zharktas don't have time to do that, I'd rather merge it than have the PR sat around for ever.  What do you think?

**Comment by Zharktas** [comment]
@rossjones added tests for both trying to change email with wrong password and with right password.

**Comment by rossjones** [comment]
Thanks very much for doing that, it is much appreciated.

**Pull request merged**
