### PR TITLE
add reset for reset_key on successful password change

### PR DESCRIPTION
**Pull request by nateprewitt**
and associated test.

Fix for #2370

### CODE REVIEW

**Comment by wardi** [comment]
@nateprewitt nice! Thanks.

**Comment by wardi** [comment]
We're not adding new tests to tests/legacy at this time, would you move the test to tests/controllers/test_user.py instead?

**Comment by nateprewitt** [comment]
Yep, wasn't sure where to put it so I grouped it with the other perform_reset tests. I'll move it over now.

**Comment by nateprewitt** [comment]
I had to import create_reset_key from [mailer.py](https://github.com/ckan/ckan/blob/master/ckan/lib/mailer.py#L154) to initialize the reset_key in the model.

If there's a cleaner interface to do this, let me know and I'll make the fix.

**Comment by wardi** [comment]
@amercader how far can we backport this one?

**Comment by amercader** [comment]
@wardi all the way down to 2.0!

**Pull request merged**
