### PR TITLE
"Previous" button in Organization/Group edit form page.

### LINKED ISSUE #6623: No "Previous" button in Organization/Group edit form page
**CKAN version**
Master
**Describe the bug**
There is no "Previous" button available in Organization/Group edit form page. If a user changes his mind not to edit Organization/Group form page or mistakenly reached to Organization/Group edit form page, there should be a "Previous/back" button to go back to previous page. 

**Steps to reproduce**
Edit any Organization/Group.

**Expected behavior**
 There should be a "Previous/back" button to go back to previous page. 

**Additional details**
Currently, user can only go back using `browser` back arrow.

### PR DESCRIPTION
**Pull request by Gauravp-NEC**
There is no "Previous" button available in Organization/Group edit form page. If a user changes his mind not to edit Organization/Group form page or mistakenly reached to Organization/Group edit form page, there should be a "Previous/back" button to go back to previous page. Currently, user can only go back using browser back arrow.

Fixes #6623 

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Review by Zharktas — CHANGES_REQUESTED** [review]
Submitting the form would still save it, there is no handling for value "previous" anywhere. You should add link to the read function of the the wanted page instead.

**Comment by Gauravp-NEC** [comment]
@Zharktas , Please review this PR. Now all the test cases have been passed. Thanks :)

**Comment by Gauravp-NEC** [comment]
@Zharktas , Please review this PR. Now all the test cases have been passed. Thanks :)

**Comment by Zharktas** [comment]
You are still submitting the form which would save it as there is no handler for value "previous". When implementing link to previous page, the url for that link should be whatever the previous page was.

**Comment by Gauravp-NEC** [comment]
@Zharktas , I have made the handler uniformly  in commit https://github.com/ckan/ckan/pull/6640/commits/77582d2a160a792b9d5d3e65b9b0c72b7f7b61bf. Currently previous button is used in resource_form.html.

**Comment by Zharktas** [comment]
Have you even tried this how it would handle ? If you modify anything in the form and click the "previous button" it would save the form and it would do exactly the thing its not supposed to do.

**Comment by Gauravp-NEC** [comment]
> You are still submitting the form which would save it as there is no handler for value "previous". When implementing link to previous page, the url for that link should be whatever the previous page was.

@Zharktas , Did you mean to have handler for value "previous" something like below? :https://github.com/ckan/ckan/blob/b88286ecdf224732d7c86a9956b9038b629ad531/ckan/views/resource.py#L226-L239

**Comment by Gauravp-NEC** [comment]
> Have you even tried this how it would handle ? If you modify anything in the form and click the "previous button" it would save the form and it would do exactly the thing its not supposed to do.

@Zharktas , Would please let me know what exactly needs to done in this PR.

**Comment by Gauravp-NEC** [comment]
> Have you even tried this how it would handle ? If you modify anything in the form and click the "previous button" it would save the form and it would do exactly the thing its not supposed to do.

@Zharktas , Would please let me know what exactly needs to done in this PR.

**Comment by Gauravp-NEC** [comment]
> Have you even tried this how it would handle ? If you modify anything in the form and click the "previous button" it would save the form and it would do exactly the thing its not supposed to do.

@Zharktas , Would please let me know what exactly needs to done in this PR.

**Comment by Gauravp-NEC** [comment]
> You are still submitting the form which would save it as there is no handler for value "previous". When implementing link to previous page, the url for that link should be whatever the previous page was.

@Zharktas , Did you mean to have handler for value "previous" something like below? https://github.com/ckan/ckan/blob/b88286ecdf224732d7c86a9956b9038b629ad531/ckan/views/resource.py#L226-L239

**Comment by Gauravp-NEC** [comment]
> Have you even tried this how it would handle ? If you modify anything in the form and click the "previous button" it would save the form and it would do exactly the thing its not supposed to do.

@Zharktas , Would please let me know what exactly needs to done in this PR.

**Comment by Gauravp-NEC** [comment]
> You are still submitting the form which would save it as there is no handler for value "previous". When implementing link to previous page, the url for that link should be whatever the previous page was.

@Zharktas , Did you mean to have handler for value "previous" something like below? https://github.com/ckan/ckan/blob/b88286ecdf224732d7c86a9956b9038b629ad531/ckan/views/resource.py#L226-L239

**Comment by Gauravp-NEC** [comment]
> Have you even tried this how it would handle ? If you modify anything in the form and click the "previous button" it would save the form and it would do exactly the thing its not supposed to do.

@Zharktas , Would please let me know what exactly needs to done in this PR.

**Comment by Zharktas** [comment]
Please stop spamming, you will only get ignored and it will make tracking changes more difficult for us. I've already told you twice that submitting a form is not the correct way to create this kind of feature. If you don't know how to create links to the read functions, you should start by reading of basics of web programming instead of trying to hack changes together by pure guesses.

**Comment by Zharktas** [comment]
You are still saving the form, that is not what previous button should do when user is changing his mind. I'm going to close this PR , since you clearly have no idea what you are doing.

**Pull request closed without merging**
