### PR TITLE
[#2161] Update multilingual schema with changes from #2078 #1905 #1495.

### PR DESCRIPTION
**Pull request by davidread**
See issue: https://github.com/ckan/ckan/issues/2161

I tested this manually as follows:
```
sudo cp /vagrant/src/ckan/ckanext/multilingual/solr/* /usr/share/solr/solr-4.3.1/example/solr/collection1/conf/
sudo service jetty restart

ckanapi -c $CKAN_INI action package_create name=t1
ckanapi -c $CKAN_INI action resource_create package_id=t1 name=test url=test1
ckanapi -c $CKAN_INI action resource_create package_id=t1 name=test url=test2

# error message appears with the old version of the schema:
ckan.lib.search.common.SearchIndexError: Solr returned an error: 400 Bad Request - <?xml version="1.0" encoding="UTF-8"?>
<response>
<lst name="responseHeader"><int name="status">400</int><int name="QTime">2</int></lst><lst name="error"><str name="msg">ERROR: [doc=32c19a046cd46f1ba52ae96dacb0b74c] multiple values encountered for non multiValued field res_name: [test, test]</str><int name="code">400</int></lst>
</response>

# revert to normal schema post-testing
sudo cp /vagrant/src/ckan/ckan/config/solr/schema.xml /usr/share/solr/solr-4.3.1/example/solr/collection1/conf/schema.xml
sudo service jetty restart
```

### CODE REVIEW

**Comment by davidread** [comment]
@metaodi you showed interest - can you test it works for your setup?

**Comment by metaodi** [comment]
@davidread I'll have a look, maybe @tschortsch can take a look as well.

**Comment by tschortsch** [comment]
Looks good to me. The new schema works in our setup.

**Comment by metaodi** [comment]
@davidread looks good to me as well :+1:

**Comment by davidread** [comment]
Great, over to @amercader to approve and merge.

**Comment by amercader** [comment]
:steam_locomotive: thanks all for the reviews

**Pull request merged**
