### PR TITLE
[#3352] Introduce all_fields option to user_list with test.

### LINKED ISSUE #3352: Add a user_list option that returns just names instead of dicts
user_list currently returns a dict for each user and the enhancement is to add an option to allow returning the user names.

DGU has 30k users and it takes 3 minutes, which is no good for a web request. Whereas returning just the names takes 10 seconds, skipping the dictization and the additional parts of the query that adds up revisions by the user.

package_list and group_list both return either names or dicts, depending on the `all_fields` parameter, so the proposal is to do the same, the only difference being that the default is True, for backward compatibility. (Other list actions just return dicts.)

### PR DESCRIPTION
**Pull request by davidread**
Fixes #3352 

### Features:

- [x] includes tests covering changes
- [x] includes updated documentation
- [no] includes user-visible changes
- [yes] includes API changes
- [na] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by amercader** [comment]
Looks good!

**Comment by wardi** [comment]
:confused:

**Comment by davidread** [comment]
But you didn't merge it @amercader...

**Comment by amercader** [comment]
oh no, sorry. I could swear that I had merged it :cold_sweat: Do you have a local copy of your branch to resubmit?

**Comment by amercader** [comment]
If not I'll use this diff to resubmit it and/or merge it

**Comment by davidread** [comment]
Ok looks good to merge again :)

**Comment by amercader** [comment]
Sorry about the mess up before!

**Pull request merged**
