### PR TITLE
Fix Unicode Decode Error in error page

### PR DESCRIPTION
**Pull request by Zharktas**
### Proposed fixes:
If error messages have latin characters, there error template fails to render them with the following log output.

```
File "/usr/lib/ckan/default/src/ckan/ckan/templates/error_document_template.html", line 8, in block "primary"
{{ content}}
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```
This pr fixes the decoding of the variable.

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [x] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by Zharktas** [comment]
The test is apparently failing on master and is not related to this pr, build probably passes after #4726 is merged.

**Comment by wardi** [comment]
Let's not pass bytes in to templates in the first place, would you move the decode to the controller/view instead?

**Comment by Zharktas** [comment]
Ah, true.  I'll fix it some point.

**Comment by Zharktas** [comment]
Apparently this only affected flask routes, pylons already had handling for different character encodings.

**Comment by Zharktas** [comment]
#4829 fixes the same thing, but from different angle, so I'm closing this.

**Pull request closed without merging**
