### PR TITLE
Fix to properly handle nested data sequence

### LINKED ISSUE #6052: Nested data can't be inserted into datastore depending on its location in the data
**CKAN version**
2.8.4

**Describe the bug**
I want to add GeoJson data to the datastore of a resource. I noticed, that depending of the placement of the nested part of the data, the data cannot be inserted into the datastore. When the nested part is the first field in the datastore the data can't be added. If I move the nested part to the end of the data, the data can be inserted without any problems.

**Steps to reproduce**
1. Create a new Ressource:
```
curl --location --request POST 'http://localhost:5000/api/3/action/resource_create' \
--header 'Authorization: 16311abf-2021-416a-8e67-b9057877a8fd' \
--header 'Content-Type: application/json' \
--data-raw '{
        "package_id": "idap-779",
        "name": "fabulous1",
        "url_type": "datastore",
        "datastore_active": true
}
```

2. Create a datastore for the resource
```
curl --location --request POST 'http://localhost:5000/api/3/action/datastore_create' \
--header 'Authorization: 16311abf-2021-416a-8e67-b9057877a8fd' \
--header 'Content-Type: application/json' \
--data-raw '{
	"resource_id":"7cc50940-9d18-4ad2-b6b3-c460423f513f",
	"force":true,
	"fields":[
		{"id":"geojson","type":"json"},
		{"id":"name","type":"text"},
		{"id":"id","type":"text"}
	],
	"primary_key":["id"],
	"calculate_record_count":false
}
```

3. Insert data into the datastore
```
curl --location --request POST 'http://localhost:5000/api/3/action/datastore_upsert' \
--header 'Authorization: 16311abf-2021-416a-8e67-b9057877a8fd' \
--header 'Content-Type: application/json' \
--data-raw '{
    "force":true,
    "records":[
        {
            "geojson":{
                "coordinates":[2.3508,48.432],
                "type":"Point"
            },
            "name":"nY",
            "id":"3"
        }
    ],
    "method":"upsert",
    "resource_id":"7cc50940-9d18-4ad2-b6b3-c460423f513f",
    "calculate_record_count":false,
    "dry_run":false
}
```

Leads to the response:
```
{
    "help": "http://ckan:5000/api/3/action/help_show?name=datastore_upsert",
    "success": false,
    "error": {
        "message": "Internal Server Error",
        "__type": "Internal Server Error"
    }
}
```

And to this error in ckan:
```
2021-04-28 09:42:54,481 ERROR [ckan.views.api] tuple index out of range
Traceback (most recent call last):
  File "/srv/app/src/ckan/ckan/views/api.py", line 288, in action
    result = function(context, request_data)
  File "/srv/app/src/ckan/ckan/logic/__init__.py", line 466, in wrapped
    result = _action(context, data_dict, **kw)
  File "/srv/app/src/ckan/ckanext/datastore/logic/action.py", line 261, in datastore_upsert
    result = backend.upsert(context, data_dict)
  File "/srv/app/src/ckan/ckanext/datastore/backend/postgres.py", line 1815, in upsert
    return upsert(context, data_dict)
  File "/srv/app/src/ckan/ckanext/datastore/backend/postgres.py", line 1420, in upsert
    upsert_data(context, data_dict)
  File "/srv/app/src/ckan/ckanext/datastore/backend/postgres.py", line 1137, in upsert_data
    (used_values + unique_values) * 2)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 467, in do_executemany
    cursor.executemany(statement, parameters)
IndexError: tuple index out of range
```

When I change the location of the nested data part everything works as expected:

1. Create a new Ressource:
```
curl --location --request POST 'http://localhost:5000/api/3/action/resource_create' \
--header 'Authorization: 16311abf-2021-416a-8e67-b9057877a8fd' \
--header 'Content-Type: application/json' \
--data-raw '{
        "package_id": "idap-779",
        "name": "fabulous1",
        "url_type": "datastore",
        "datastore_active": true
}
```

2. Create a datastore for the resource
```
curl --location --request POST 'http://localhost:5000/api/3/action/datastore_create' \
--header 'Authorization: 16311abf-2021-416a-8e67-b9057877a8fd' \
--header 'Content-Type: application/json' \
--data-raw '{
	"resource_id":"79d5677b-7f6f-418c-92a4-0b8a617707d0",
	"force":true,
	"fields":[
		{"id":"name","type":"text"},
		{"id":"id","type":"text"},
                {"id":"geojson","type":"json"}
	],
	"primary_key":["id"],
	"calculate_record_count":false
}
```

3. Insert data into the datastore
```
curl --location --request POST 'http://localhost:5000/api/3/action/datastore_upsert' \
--header 'Authorization: 16311abf-2021-416a-8e67-b9057877a8fd' \
--header 'Content-Type: application/json' \
--data-raw '{
    "force":true,
    "records":[
        {
            "name":"nY",
            "id":"3",
            "geojson":{
                "coordinates":[2.3508,48.432],
                "type":"Point"
            }
        }
    ],
    "method":"upsert",
    "resource_id":"79d5677b-7f6f-418c-92a4-0b8a617707d0",
    "calculate_record_count":false,
    "dry_run":false
}
```
Leads to the response and the data is added correctly:
```
{
    "help": "http://ckan:5000/api/3/action/help_show?name=datastore_upsert",
    "success": true,
    "result": {
        "records": [
            {
                "name": "nY",
                "geojson": [
                    "{\"type\": \"Point\", \"coordinates\": [2.3508, 48.432]}",
                    ""
                ],
                "id": "3"
            }
        ],
        "resource_id": "79d5677b-7f6f-418c-92a4-0b8a617707d0",
        "method": "upsert",
        "__extras": {
            "calculate_record_count": false,
            "dry_run": false
        }
    }
}
```

**Expected behavior**
The insertion of nested data works no matter where the nested part in the data is located

### PR DESCRIPTION
**Pull request by Deep-NEC**
Fixes #6052 

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by pdelboca** [comment]
Hello @Deep-NEC ! Thanks for this contribution! I'm gonna review it.

Could you please:
 - Fix the Lint issue.
 - Add a change file
 - Add some unit test to cover this scenario
 
 Thanks!

**Comment by Deep-NEC** [comment]
> Hello @Deep-NEC ! Thanks for this contribution! I'm gonna review it.
> 
> Could you please:
> 
> * Fix the Lint issue.
> * Add a change file
> * Add some unit test to cover this scenario
> 
> Thanks!

Hello @pdelboca Thankyou for reviewing my PR,

I have fixed the lint issue, added change file and also added few unit testcases covering the fix scenario.

Thanks

**Comment by pdelboca** [comment]
@Deep-NEC I'm having some troubles understanding what's causing the issue and why the proposed solution is working.

Can you explain your approach? Why is it that pushing the nested field to the last fixes the issue?

In that case it would be nice to refactor that piece of code into it's own private function with a proper docstring to explain what is doing and why. That way is going to be easier to follow the code in the future.

**Comment by Gauravp-NEC** [comment]
> @Deep-NEC I'm having some troubles understanding what's causing the issue and why the proposed solution is working.
> 
@pdelboca, Cause of issue is when the nested part is the first field in the datastore the data can't be added. If nested part is moved to the end of the data, the data can be inserted without any problems. 

> Can you explain your approach? Why is it that pushing the nested field to the last fixes the issue?
> 
The approach of Deep-NEC is to check the `type value` of first_field. If the `type value` is nested in first_field then nested contained value is appended at the end in fields.

> In that case it would be nice to refactor that piece of code into it's own private function with a proper docstring to explain what is doing and why. That way is going to be easier to follow the code in the future.

I will submit a new PR.

**Pull request closed without merging**
