### PR TITLE
[#2578] Make sure markdown_extract doesn't break if a dict is passed

### PR DESCRIPTION
**Pull request by metaodi**

### CODE REVIEW

**Comment by metaodi** [comment]
@rossjones No the function does not handle this case correctly and no the output won't the perfect either. But I think this is probably something that needs to be handled either in ckanext-fluent or an other custom extensions. This check is only to make sure, that the CKAN site does not break (i.e. throw an internal server error).
It's not perfect, but at least you can still use the site.

In my special case I only need to access this data via API, which works perfectly :wink:

**Comment by rossjones** [comment]
I'll mention during tomorrow's call that it's a "stop ckan crashing because of an accidental external extension".  Might be worth mentioning on the ckanext-fluent github too though?

**Comment by davidread** [comment]
Can you be clearer about the case that this helps please? Surely any dict will cause an exception on the re.sub step straight afterwards?

**Comment by metaodi** [comment]
I will close this for now, as it is clearly not a CKAN core issue, but rather a problem of ckanext-scheming or ckanext-fluent.

**Pull request closed without merging**
