### PR TITLE
1903 Removes the old auth models and their use.

### PR DESCRIPTION
**Pull request by rossjones**
Removes all of the old auth models, and contains a migration to delete the now unused tables. There are a few components still depending (secretly behind the scenes) on PackageRole and as a result for this PR to be complete it needs to re-implement number_administered_packages. Also breaks stats.

Should allow for close of #1903 as there's another PR for renaming new_authz.

### CODE REVIEW

**Comment by davidread** [comment]
So is it just these 3 test failures to fix now? Or are there other things? Perhaps someone else has a chance to fix these up.
```
======================================================================
ERROR: ckanext.datastore.tests.test_create.TestDatastoreCreate.test_create_datastore_resource_on_dataset
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "/home/travis/build/ckan/ckan/ckanext/datastore/tests/test_create.py", line 708, in test_create_datastore_resource_on_dataset
assert res_dict['result']['datastore_active'] is True
KeyError: 'datastore_active'
======================================================================
ERROR: ckanext.stats.tests.test_stats_lib.TestStatsPlugin.test_top_package_owners
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "/home/travis/build/ckan/ckan/ckanext/stats/tests/test_stats_lib.py", line 91, in test_top_package_owners
owners = Stats.top_package_owners()
File "/home/travis/build/ckan/ckan/ckanext/stats/stats.py", line 99, in top_package_owners
package_role = table('package_role')
File "/home/travis/build/ckan/ckan/ckanext/stats/stats.py", line 18, in table
return Table(name, model.meta.metadata, autoload=True)
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/sql/schema.py", line 352, in __new__
table._init(name, metadata, *args, **kw)
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/sql/schema.py", line 425, in _init
self._autoload(metadata, autoload_with, include_columns)
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/sql/schema.py", line 448, in _autoload
self, include_columns, exclude_columns
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1671, in run_callable
return conn.run_callable(callable_, *args, **kwargs)
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1198, in run_callable
return callable_(self, *args, **kwargs)
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/default.py", line 355, in reflecttable
return insp.reflecttable(table, include_columns, exclude_columns)
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/reflection.py", line 463, in reflecttable
for col_d in self.get_columns(table_name, schema, **table.dialect_kwargs):
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/reflection.py", line 277, in get_columns
**kw)
File "<string>", line 2, in get_columns
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/reflection.py", line 53, in cache
ret = fn(self, con, *args, **kw)
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/dialects/postgresql/base.py", line 1923, in get_columns
info_cache=kw.get('info_cache'))
File "<string>", line 2, in get_table_oid
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/reflection.py", line 53, in cache
ret = fn(self, con, *args, **kw)
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/dialects/postgresql/base.py", line 1839, in get_table_oid
raise exc.NoSuchTableError(table_name)
NoSuchTableError: package_role
======================================================================
FAIL: test_multilingual_plugin.TestDatasetTermTranslation.test_user_read_translation
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "/home/travis/build/ckan/ckan/ckanext/multilingual/tests/test_multilingual_plugin.py", line 84, in test_user_read_translation
assert translations[term] in response
AssertionError
```

**Comment by rossjones** [comment]
The first failure ```KeyError: 'datastore_active'``` is unrelated.

**Comment by davidread** [comment]
Ready to be reviewed now.

Basically this authz stuff was simply not being used (read), so removing the code (the writing of the roles for a package, e.g. when it is created) doesn't affect anything. Other recent PRs have patched some little bits that did reference it, and so merging in from master has solved those. There was one remaining place it was being referenced, which was in the stats extension, which I've updated that in this PR.

**Comment by davidread** [comment]
This useful cleanup is almost 3 months in review now :-(

**Comment by davidread** [comment]
@amercader Now is the perfect time to review this clean-up and merge it!

**Comment by davidread** [comment]
Hooray! That's 1000 lines gone :boom:  :smile: Thanks @rossjones @amercader

**Pull request merged**
