### PR TITLE
#2216 displaying users draft datasets

### PR DESCRIPTION
**Pull request by benjaminlaot**
Allowed displaying of users draft and deleted datasets

### CODE REVIEW

**Comment by clementmouchet** [comment]
+1 to see this merged into master (the filters are a radical change of behaviour)

**Comment by amercader** [comment]
See comment in #2216

**Comment by davidread** [comment]
This PR would allow anyone to list private and draft datasets, which I don't think we want. I've done an alternative PR here: https://github.com/ckan/ckan/pull/2256

**Comment by amercader** [comment]
Closed in favour of #2256

**Pull request closed without merging**
