### PR TITLE
[7008]Fix ckan generate config debug issue

### LINKED ISSUE #7008: ckan generate config debug issue
**CKAN version**
master

**Describe the bug**
`ckan generate config` exports a configuration including `debug = false` in the `[app:main]` section of the ini file. This setting overrides any debug setting in `[DEFAULT]` which is where it normally occurs, and where okfn/docker-ckan adds the `debug = true` setting for development ckan environments

**Steps to reproduce**
Steps to reproduce the behavior: run `ckan generate config`

**Expected behavior**
`debug = false` should be in the `[DEFAULT]` section not `[app:main]`

**Additional details**

### PR DESCRIPTION
**Pull request by TomeCirun**
Fixes #7008 

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by TomeCirun** [comment]
@smotornyuk can you tell if this is the right way to do it?

Thanks

**Comment by smotornyuk** [comment]
I prefer to avoid using this approach because debug option slips out standard config option workflow: it's not validated anymore and not auto-documented.

I'll take a look at the issue and check the complexity of handling configuration sections via config declarations. If it's too complex, let's go with your solution(but we need to update the documentation in this case).
So, for now, I'll put this PR on hold and ping you after this small research.

**Comment by TomeCirun** [comment]
any news on this one ? @smotornyuk

**Comment by smotornyuk** [comment]
I've created PR #7105, but it's not discussed/reviewed yet, so it may be not the final version yet)

**Comment by EricSoroos** [comment]
This has been superseded by #7105

**Pull request closed without merging**
