### PR TITLE
WIP: CircleCI  v1 to v2 again

### PR DESCRIPTION
**Pull request by cclauss**
A new attempt at #4333 with a newly forked repo.

Follows the confusing process documented at https://circleci.com/sunset1-0/#migration-steps

The first commit __changes no code__ to see if we can sidestep the strange build behavior discussed in  #4335

### CODE REVIEW

**Comment by cclauss** [comment]
@amercader Picking up from https://github.com/ckan/ckan/issues/4335#issuecomment-405867945

You are absolutely right!  The __solr__ build issue went away when I switch from __Ubuntu 14.04 (Trusty)__ back to __Ubuntu 12.04 (Precise)__ at https://circleci.com/gh/cclauss/ckan/edit#build-environment (substitute your id for __cclauss__ in the URL).

So... as described in the URL you sent, we [must move off of Precise](https://circleci.com/docs/1.0/build-image-precise/) and this PR needs to [install Solr on Ubuntu 14.04 (Trusty)](https://www.digitalocean.com/community/tutorials/how-to-install-solr-on-ubuntu-14-04).

Do we want __apt-get -y install solr-common__ or __solr-tomcat__ or __solr-jetty__ ... ?

**Comment by jrods** [comment]
@cclauss It's been a long time since I've looked at this, so forgive me for
not remembering the details.

Unless you need that old verion of solr, you can try using the solr docker
images if circleci allows it. But i believe the original issue was needing
to make a new commit for creating a new build image that wouldnt lose
reference to the solr binary.

You can try installing solr manually, there are binary packages readily
available.

**Comment by cclauss** [comment]
5651 [main] INFO  org.eclipse.jetty.server.AbstractConnector  – Started SocketConnector@0.0.0.0:__8983__

But now tests fail trying to connect to localhost:__6379__

**Comment by cclauss** [comment]
Closed in favor of #4394

**Pull request closed without merging**
