### PR TITLE
Fix solr multicore not persisting restarts

### PR DESCRIPTION
**Pull request by davidread**
When making SOLR run multicore, I found that using the HTTP request to SOLR to tell it to create a SOLR core worked only until you restart Jetty/SOLR. I couldn't get the 'persist' parameter to work, so had to fall back to editing the solr.xml file.

### CODE REVIEW

**Comment by tino097** [comment]
thumbs up!

**Comment by amercader** [comment]
Just out of curiosity, what Solr version where you using when testing this @davidread?

**Comment by davidread** [comment]
@amercader it's Postgres 9.3.16 (as comes with Ubuntu 14.04)

**Comment by amercader** [comment]
@davidread thanks, was asking about Solr (as this issue relates to Solr) :)

**Comment by davidread** [comment]
:-/

SOLR 3.6.2 (i.e. solr-jetty package default for Ubuntu 14.04)

**Pull request merged**
