### PR TITLE
Upgrade Flask, Werkzeug, Jinja2 and Click

### PR DESCRIPTION
**Pull request by amercader**
After long fascinating reads across several Changelogs I think there are no immediate things that stand out before upgrading these libraries, except for two minor things (test failures):

1. @mutantsan Our wrapper for the request object in templates [stopped working](https://app.circleci.com/pipelines/github/ckan/ckan/2230/workflows/cdb6184f-9d1e-4df1-a9be-f95c6a663fb3/jobs/9971/tests#failed-test-1). This was introduced in https://github.com/ckan/ckan/pull/5809 and will be backported to 2.9.4. Maybe it's worth keeping in the next CKAN version but if you don't find how to get it working again I think it's fine to revert it on master.
2. @smotornyuk This command [is failing](https://app.circleci.com/pipelines/github/ckan/ckan/2230/workflows/cdb6184f-9d1e-4df1-a9be-f95c6a663fb3/jobs/9971/tests#failed-test-0) with the latest version of Click:

```
ckan user token add user_name my_token
Traceback (most recent call last):
  File "/home/adria/dev/pyenvs/ckan-py3/bin/ckan", line 11, in <module>
    load_entry_point('ckan', 'console_scripts', 'ckan')()
  File "/home/adria/dev/pyenvs/ckan-py3/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/adria/dev/pyenvs/ckan-py3/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/adria/dev/pyenvs/ckan-py3/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/adria/dev/pyenvs/ckan-py3/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/adria/dev/pyenvs/ckan-py3/lib/python3.8/site-packages/click/core.py", line 1666, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/home/adria/dev/pyenvs/ckan-py3/lib/python3.8/site-packages/click/core.py", line 923, in make_context
    self.parse_args(ctx, args)
  File "/home/adria/dev/pyenvs/ckan-py3/lib/python3.8/site-packages/click/core.py", line 1379, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/adria/dev/pyenvs/ckan-py3/lib/python3.8/site-packages/click/core.py", line 2364, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/adria/dev/pyenvs/ckan-py3/lib/python3.8/site-packages/click/core.py", line 2320, in process_value
    value = self.type_cast_value(ctx, value)
  File "/home/adria/dev/pyenvs/ckan-py3/lib/python3.8/site-packages/click/core.py", line 2307, in type_cast_value
    return convert(value)
  File "/home/adria/dev/pyenvs/ckan-py3/lib/python3.8/site-packages/click/types.py", line 75, in __call__
    return self.convert(value, param, ctx)
  File "/home/adria/dev/pyenvs/ckan-py3/lib/python3.8/site-packages/click/types.py", line 170, in convert
    return self.func(value)
  File "/home/adria/dev/pyenvs/ckan-py3/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/adria/dev/pyenvs/ckan-py3/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/adria/dev/pyenvs/ckan-py3/lib/python3.8/site-packages/simplejson/decoder.py", line 392, in raw_decode
    raise TypeError("Input string must be text, not bytes")
TypeError: Input string must be text, not bytes
```

I believe it has to do with the `--json` option parsing but couldn't find a quick fix for it. Any ideas?

### CODE REVIEW

**Comment by smotornyuk** [comment]
PS it means that we must check all the commands with the `type` in options and make sure, that all `type`'s are idempotent

**Comment by amercader** [comment]
Thanks for the quick tip @smotornyuk. What you describe seems like a regression in Click but your patch seems clearer anyway. I checked the rest of the `type` param in other commands options and all seemed to work fine

**Comment by amercader** [comment]
@mutantsan I've reverted #5809. I think that by the time the next CKAN version is out less and less extensions would need to support `request.params` in the templates. And if an alternative approach can be found that works on Flask 2 then we can add it in a separate PR.

**Comment by mutantsan** [comment]
@amercader, sorry, I didn't come to a solution. Probably, to get rid of it was the best idea :)

**Pull request merged**
