### PR TITLE
[#5593] Fix for Datastore file dump extension

### PR DESCRIPTION
**Pull request by Engerrs**

### CODE REVIEW

**Comment by shubham-mahajan** [comment]
@Engerrs The Checks are failing for the coding standards. Can you please fix those?

**Comment by jqnatividad** [comment]
Hi @Engerrs , I'm afraid there are still some minor coding standards tweaks required in datastore/writer.py (primarily, string literals need to be prefixed by 'u').
Do you mind as its blocking datastore dump from fully working?

**Comment by Engerrs** [comment]
Hi @jqnatividad , I updates the string, please let me know if there anything else that is need to be updated.

**Comment by shubham-mahajan** [comment]
@Engerrs @jqnatividad LGTM now.

**Pull request merged**
