### PR TITLE
[#1527] Allow to customize emails sent from CKAN

### PR DESCRIPTION
**Pull request by amercader**
The reset password and user invite emails sent from CKAN have their subjects and bodies hardcoded into `ckan/lib/mailer.py`. This PR includes changes to make the subjects configurable on the ini file, and the bodies via overriding templates from extensions.
It also adds a bit more detail to the user invite email, including which organization/group you've been actually added to, and with which role.

Both subjects and bodies are translated.

It also fixes a couple of bugs on the `user_invite` action and updates and refactors all mailing legacy tests,

### CODE REVIEW

**Comment by wardi** [comment]
How about a couple 1-line templates for the subjects instead:
* ckan/templates/emails/invite_user_subject.txt
* ckan/templates/emails/reset_password_subject.txt

**Comment by amercader** [comment]
@wardi you got it: 422df75

**Comment by wardi** [comment]
@amercader thanks! :beers:

**Comment by amercader** [comment]
One thing to note (outside the scope of this PR) is that the message extractors that we rely on for txt files and Javascript files are based on Genshi:

https://github.com/ckan/ckan/blob/60a7edf78ebc4d980c8caa25d5dbd6a5b7c294b6/setup.py#L183:L191

Would be good to get rid of these and use Jinja2 so we can drop the Genshi requirement

**Comment by wardi** [comment]
I can't think of a reason to keep genshi for text and js templates, We already removed the legacy templates, so extensions that depend on them must be really broken already.

**Comment by amercader** [comment]
Sure, as long as we extract strings on txt and js files using jinja2 (which I didn't manage with a 2 min try) let's get rid of it for good.

On other news, I hate CKAN legacy tests...

**Comment by amercader** [comment]
@wardi All tests should be green now in case you want to squeeze this on 2.5

**Comment by wardi** [comment]
Dang, didn't get to this one in time

**Pull request merged**
