### PR TITLE
fix redirect with nonroot take 2

### PR DESCRIPTION
**Pull request by wardi**
#2968 with fixes

### CODE REVIEW

**Comment by MrkGrgsn** [comment]
@wardi Is it safe to alter `SCRIPT_NAME`? I would think changing an environment variable could break other middleware?

**Comment by wardi** [comment]
@MrkGrgsn you're right this change inserts the middleware around all the other middleware. I thought we were inserting the middleware at the other end of the stack. We should fix that.

I also agree in general this is a hack, but the alternative was to fork routes so that url_for would work properly with a root_path setting

**Comment by wardi** [comment]
for backporting: related changes include
- https://github.com/ckan/ckan/commit/bf106b0
- https://github.com/ckan/ckan/commit/a76da0c
- https://github.com/ckan/ckan/commit/9cf0369
- ... these commits ...
- https://github.com/ckan/ckan/commit/16a81926b

**Comment by amercader** [comment]
@wardi I know we've gone over this, but just want to double check if you think this is safe for backporting, seeing as it involves changes down to the middleware level.

Also if that's the case that all the commits from different PRs in the above comment should be backported.

**Comment by wardi** [comment]
well, now that we're on 2.5 + these changes I'm still seeing multiple different redirect issues, it's probably better to leave it out until I can track down the new problems.

**Comment by amercader** [comment]
cool, I won't backport it then

**Pull request merged**
