### PR TITLE
download button for datastore-only resources

### LINKED ISSUE #7806: Datastore-only resources missing Download button
## CKAN version
all

## Describe the bug
When creating a datastore-only resource it is possible to add views like the datatable view that provides a filtered download option, but on the resource page itself no download button is offered.

### Steps to reproduce
~create a resource with `datastore_create`, view the resource info page.~ see https://github.com/ckan/ckan/pull/7807#issuecomment-1730206956 for proper steps to reproduce

### Expected behavior
A download button with the usual options (CSV, TSV, JSON, XML) should be visible

### PR DESCRIPTION
**Pull request by wardi**
Fixes #7806

### Proposed fixes:

- add download button for datastore-only resources
- fix surrounding template indentation

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [X] includes user-visible changes
- [ ] includes API changes
- [X] includes bugfix for possible backport

### CODE REVIEW

**Comment by kowh-ai** [comment]
Testing the change, I’ve added a datastore-only resource as per the documentation [here](https://docs.ckan.org/en/2.10/maintaining/datastore.html#test-the-set-up)

`curl -X POST http://127.0.0.1:5000/api/3/action/datastore_create -H "Authorization: {YOUR-API-KEY}" -d '{"resource": {"package_id": "{PACKAGE-ID}"}, "fields": [ {"id": "a"}, {"id": "b"} ], "records": [ { "a": 1, "b": "xyz"}, {"a": 2, "b": "zzz"} ]}'`

It added OK and I see the table in the database. I restarted my CKAN container but I don’t see the “**Download**” button like I do on another resource I have added to this package/dataset. I have added some custom text to `resource_read.html` which does render on this page after a container restart, so I know changes to code are getting picked up during a container restart. I’ll keep digging. I must be doing something wrong
Screenshot 2023-09-21 at 1 41 59 pm
Screenshot 2023-09-21 at 1 42 13 pm

**Comment by wardi** [comment]
Interesting. It's nothing you did but creating a datastore resource with datastore_create seems to have given it a URL, and this change assumes no URL will be set.

I submitted this as a fix I need for upcoming table designer work where the resource is created without a url value set, that's why you're not seeing the change.

**Comment by wardi** [comment]
@kowh-ai Here are proper steps to reproduce:

1. Create a resource with no URL value set (just give it a name or description and click save)
2. `ckanapi action datastore_create resource_id=<the-resource-you-created> force=true`
3. visit the resource page (it should now have a download dropdown with this change)

**Comment by kowh-ai** [comment]
@wardi thanks for that...will pick this up when I'm back from vacation end of next week...apologies for the delay

**Comment by kowh-ai** [comment]
@wardi - nope, still doesn't show the "download" button after updating the existing resource

Screenshot 2023-10-02 at 11 12 00 am

**Comment by wardi** [comment]
updating the existing resource won't clear the url, try with a new resource instead.

**Comment by kowh-ai** [comment]
`ckanapi action datastore_create <etc>` requires an existing resource id ie: cannot create a new resource

The following 2 commands create the resource but there are no (Download, Goto Resource or Data API) buttons on the page

`ckanapi action resource_create package_id=26ecd3d3-6402-41ac-8dd0-106578c9c2b0 name=resource5`

`ckanapi action resource_create package_id=26ecd3d3-6402-41ac-8dd0-106578c9c2b0 name=resource6 \ upload@/srv/app/really.simple.csv force=true`

**Comment by wardi** [comment]
Thanks @kowh-ai that seem like a slightly different issue but I'll try to fix that here too.

**Comment by amercader** [comment]
I was able to reproduce and check the fix. @kowh-ai feel free to create a separate issue for that last behaviour

**Pull request merged**
