### PR TITLE
[#2938] Org list sort package_count added to UI and sort logic modification

### PR DESCRIPTION
**Pull request by Engerrs**
Adding package_count sorting to UI for Organization list.

### CODE REVIEW

**Comment by Engerrs** [comment]
Hi @amercader , I've added a full PR with all changes in one.

**Comment by wardi** [comment]
actually, we can get counts of datasets for all orgs from the facets returned by package_search, and those numbers will always take permissions into account.

**Comment by Engerrs** [comment]
@wardi, its a good idea, I'll rewrite then the logic for this one.

**Comment by Engerrs** [comment]
@wardi , it appears that the method is done by one big query and in the result he got the counts of datasets from **organization_show** method, which displays the right count already.

**Comment by wardi** [comment]
@Engerrs I'm saying this is duplicating code and only shows the correct counts if the site hasn't defined a custom policy for dataset visibility with an IPermissionLabels plugin.

If we make one call to package_search with limit=0 the facet counts returned will always have the correct count.

**Comment by kmbn** [comment]
We decided to close old pull requests that are not actively worked on so that we can focus our effort and attention on PRs made against the current version of CKAN. A lot has changed in the last several months and many PRs will have gone stale or may now be in conflict with the latest version.

Please note: this isn't a judgement about the quality of your pull request. We just don't have the resources to review older PRs.

If you would like to reopen your PR (and update it if necessary), please do!

**Pull request closed without merging**
