### PR TITLE
Fix Bootstrap 3 issues

### LINKED ISSUE #3754: Bootstrap3 UI issues
Chromium v59:
#3620
This is how looks dataset search page when filters are enabled
screenshot from 2017-07-27 16-18-29
And this is organization list(I have one organization):
screenshot from 2017-07-27 16-19-45

### PR DESCRIPTION
**Pull request by klikstermkd**
Fixes #3754

### CODE REVIEW

**Comment by klikstermkd** [comment]
Ready for review.

**Comment by smotornyuk** [comment]
Search field still displayed over filter layer
screenshot from 2017-08-24 12-50-46

And, i'm not sure, whether it is related, but if you click on **Embed** button on resource preview page, modal window displayed under the shadow layer:

screenshot from 2017-08-24 12-54-11

**Comment by klikstermkd** [comment]
@smotornyuk I fixed the issue with the search field being shown, but the second one that you reported for the embed modal not properly shown is working fine for me. In fact, I already fixed that in #3733 that is merged into master.

**Comment by smotornyuk** [comment]
Hm, i suspect, i forgot to clean browser's cache, because it's working now :+1:

**Pull request merged**
