### PR TITLE
[#2216] user can now see his private & draft datasets again

### PR DESCRIPTION
**Pull request by davidread**
My recent commit https://github.com/ckan/ckan/commit/b2dfccc8932947711d4f9b0f2500be4c40208b21 stopped draft and private datasets from being returned by user_show, because other general users should not know about these datasets that they cannot view. However it was rightly pointed out by @benjaminlaot that when a user views his own user page (or a sysadmin views it) it makes sense to show these draft and private datasets to him. So I've added logic for this in this PR.

Similar logic is added to the number_created_packages property (user_show). However user_list's number_created_packages excludes draft&private datasets for everyone (for simplicity) - before it just excluded draft ones. This is now also documented and tested.

### CODE REVIEW

**Comment by davidread** [comment]
@amercader this will need to go into CKAN 2.3 - can you label it please?

**Comment by benjaminlaot** [comment]
Great job !

**Comment by benjaminlaot** [comment]
If I may, I think that to fit with the  spirit of #2261 reported by @clementmouchet, it would be great to allow the display of packages with custom states by changing this filter in def user_show(context, data_dict) line 1359: 

dataset_q = dataset_q \
                .filter(_or_(model.Package.state=='active',
                            model.Package.state=='draft'))

by this one : dataset_q = dataset_q \
                       .filter(model.Package.state!='deleted')

It won't break existing behaviour as draft and active datasets will be displayed for a user looking at his own account or a  sysadmin, but it also allows the existence of custom states for more flexibility

If you are agreed with this, these lines might change too (line 205 in ckan/model/user.py)

if include_private_and_draft: 
       q = q.filter(model.Package.state.in_(('active', 'draft')))

replaced by : 
if include_private_and_draft: 
     q = q.filter(model.Package.state!='deleted')

Whad do you think @davidread ?

**Comment by amercader** [comment]
@davidread merged to master and 2.3

**Pull request merged**
