### PR TITLE
[#3071] Regenerating API Key fails for users missing required columns(ex: email)

### PR DESCRIPTION
**Pull request by wildcatzita**

### CODE REVIEW

**Comment by wildcatzita** [comment]
Fix for [issue](https://github.com/ckan/ckan/issues/3071)

**Comment by amercader** [comment]
I better fix would be to call whatever function is being used to create a user on `paster user add` internally from `paster sysadmin add` so both supported the same parameters. @wildcatzita WDYT?

**Comment by wildcatzita** [comment]
@amercader , sounds good. I'll fix.

**Comment by wildcatzita** [comment]
Hi @amercader , fixed. Can you please check?

**Comment by amercader** [comment]
Thanks @wildcatzita for the changes!

**Pull request merged**
