### PR TITLE
Bugfix #5468 page view tracking sub path issue

### LINKED ISSUE #5468: Page view tracking of datasets is not working if ckan is running at a subpath
### CKAN Version if known (or site URL)
2.8.4

### Please describe the expected behaviour
Page view tracking works as describend in https://docs.ckan.org/en/2.8/maintaining/tracking.html as well if ckan is operated at subpath.

### Please describe the actual behaviour

Page view tracking works as expected if ckan runs at standard root path "/".
But we're running ckan on a subpath ('/ckan') using the ckan.root_path property in the production.ini.
In this case the page view tacking of datasets **always shows zero hits**.

After some investigation into the db, I figured out that the hits are successfully reflected in table 'tracking_raw', but not updated during a 'paster --plugin=ckan tracking update' in table 'tracking_summary'.

I further noticed, that tracking_summary.package_id keeps the value '\~\~not\~found\~\~' for all datasets at this system. (Unlike to a system running on '/' where correct package-ids are set).

When I compared the stored urls of both systems, i also noticed that the leading url path is reflected in the stored url. So you'll get:
' /ckan/dataset/test' or ' /ckan/de/dataset/test'(both not working) im comparision to ' /dataset/test' or ' /de/dataset/test' (both working).

I've tried to track the problem in the code. For my understanding the problem could be located in **/cli/tracking.py** - function **update_tracking**.
Below the comment "get ids for dataset urls" happens the construction of a sql, using a regex.

```
# get ids for dataset urls
sql = u'''UPDATE tracking_summary t
            SET package_id = COALESCE(
                (SELECT id FROM package p
                WHERE p.name = regexp_replace
                  (' ' || t.url, '^[ ]{1}(/\\w{2}){0,1}' || %s, ''))
                ,'~~not~found~~')
            WHERE t.package_id IS NULL
            AND tracking_type = 'page';'''
engine.execute(sql, PACKAGE_URL)
```

This regex does not reflect a leading path part ('/ckan' in our example), which leads to an failing UPDATE statement.

### What steps can be taken to reproduce the issue? 
- configure ckan under a sub path like mentioned in the docs https://docs.ckan.org/en/2.8/maintaining/configuration.html#ckan-root-path
- enable page view tracking like mentioned in the docs https://docs.ckan.org/en/2.8/maintaining/tracking.html
- create a dateset and visit it
- update the page view tracking statistic like mentioned in the docs https://docs.ckan.org/en/2.8/maintaining/tracking.html (I did it manually running the paster command)
- Retrieve the tracking data by API or paster command like mentioned in https://docs.ckan.org/en/2.8/maintaining/tracking.html
- alternatively confirm my findings by inspecting the database tables 'tracking_raw' and 'tracking_summary'

### PR DESCRIPTION
**Pull request by Nisha1293**
Fixes #5468 

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Review by tino097 — APPROVED** [review]

**Comment by amercader** [comment]
@tino097 please merge if happy with the changes

**Comment by tino097** [comment]
@amercader i was waiting for #8479 to get merged to keep eye if any conflicts would occur

**Comment by tino097** [comment]
hey @Nisha1293 can you please just resolve this issue and its ready to go

**Comment by tino097** [comment]
Closing in favor of https://github.com/ckan/ckan/pull/8523

**Pull request closed without merging**
