### PR TITLE
Fix Followers count not updated immediately in UI

### LINKED ISSUE #3639: Followers count not updated immediately on UI
### CKAN Version if known (or site URL)
Any.

### Please describe the expected behaviour
When you follow/unfollow something (org, group etc.), the followers count should immediately be updated in the UI.

### Please describe the actual behaviour
When you follow/unfollow something (org, group etc.), the followers count isn't immediately updated in the UI, instead a refresh is needed to see the change.

### What steps can be taken to reproduce the issue? 
Go to any org, group, user or dataset and press the Follow/Unfollow button. The Followers count is not updated until you refresh the page.

I can fix this and provide a PR.

### PR DESCRIPTION
**Pull request by klikstermkd**
Fixes #3639 

### Features:

- [X] includes tests covering changes
- [ ] includes updated documentation
- [X] includes user-visible changes
- [ ] includes API changes
- [X] includes bugfix for possible backport

### CODE REVIEW

**Comment by klikstermkd** [comment]
Ready for review.

**Comment by klikstermkd** [comment]
@smotornyuk I found some issues with the way I implemented this. I will provide a fix.

**Comment by smotornyuk** [comment]
ok, i'll wait then:)

**Comment by klikstermkd** [comment]
@smotornyuk I fixed the issues. Now it's ready for review :)

**Comment by smotornyuk** [comment]
Verified

**Pull request merged**
