### PR TITLE
[WIP] 2575 - Allows the disabling of datastore_search_sql

### PR DESCRIPTION
**Pull request by rossjones**
Although the datastore is useful, it may be that some users may will to
disable the specific datastore_search_sql.  This PR allows them to do
that to fix https://github.com/ckan/ckan/issues/2575

### CODE REVIEW

**Comment by amercader** [comment]
PEP :8ball: 

```
---------------------------------------
ckanext/datastore/tests/test_disable.py
---------------------------------------
E302 ln:6 expected 2 blank lines, found 1


Failing Files:
==============
ckanext/datastore/tests/test_disable.py
```

Issue numbers please, ta

**Comment by rossjones** [comment]
This *still* need to handle legacy mode ....

**Comment by amercader** [comment]
@rossjones something like this will avoid this test being run on Postgres 8 and fix Travis:

```diff
diff --git a/ckanext/datastore/tests/test_disable.py b/ckanext/datastore/tests/test_disable.py
index 38cc53f..d2f66e8 100644
--- a/ckanext/datastore/tests/test_disable.py
+++ b/ckanext/datastore/tests/test_disable.py
@@ -1,3 +1,4 @@
+import nose
 
 import pylons.config as config
 import ckan.plugins as p
@@ -6,6 +7,15 @@ import nose.tools as t
 
 class TestDisable(object):
 
+    @classmethod
+    def setup_class(cls):
+
+        plugin = p.load('datastore')
+        if plugin.legacy_mode:
+            # make sure we undo adding the plugin
+            p.unload('datastore')
+            raise nose.SkipTest("SQL tests are not supported in legacy mode")
+
     @t.raises(KeyError)
     def test_disable_sql_search(self):
         config['ckan.datastore.sqlsearch.enabled'] = False
```

**Comment by amercader** [comment]
@rossjones ping, if you tweak the tests as above to not run on legacy mode this is good to go

**Comment by davidread** [comment]
I think you just need an ```import nose```
```
ERROR: test suite for <class 'ckanext.datastore.tests.test_disable.TestDisable'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/suite.py", line 208, in run
    self.setUp()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/suite.py", line 314, in setupContext
    try_run(context, names)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/util.py", line 469, in try_run
    return func()
  File "/home/travis/build/ckan/ckan/ckanext/datastore/tests/test_disable.py", line 15, in setup_class
    raise nose.SkipTest("SQL tests are not supported in legacy mode")
NameError: global name 'nose' is not defined
```

**Pull request merged**
