### PR TITLE
[#4130] allow to query resources by date fields

### PR DESCRIPTION
**Pull request by smotornyuk**
Fix for #4130 
I'm not sure, what value of searching by date with that microsecond precision, required by PostgreSQL, but adding any additional flags for more granular customization of precision is far beyond the scope of this problem, so I just make a change that uses equality instead of LIKE operator for DateTime fields

### CODE REVIEW

**Comment by wardi** [comment]
@smotornyuk I think we agreed to change this to only use LIKE on text fields instead of only not on date fields, right?

**Comment by smotornyuk** [comment]
Yep. I finally back, so i'll update this PR soon

**Comment by smotornyuk** [comment]
Sorry, i completely forgot about it:((
Updated

**Comment by ashmeet-kandhari** [comment]
Hi,

Any update on this issue?

**Comment by smotornyuk** [comment]
ping @wardi

**Comment by wardi** [comment]
This just needs a small test to make sure it keeps working then it's GTG

**Comment by smotornyuk** [comment]
And test is finally there! @wardi , if you have time - this pr is ready for deploy

**Pull request merged**
