### PR TITLE
Change unicode() --> six.text_type() for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Related to #3309  (partial fix)

__unicode()__ was removed in Python 3 because all str are Unicode so this PR:
* Changes all calls to __unicode()__ into calls to [__six.text_type()__](https://pythonhosted.org/six/#six.text_type)
* Change all instances of __(str, unicode)__ to [__six.string_types__](https://pythonhosted.org/six/#six.string_types)
* Change remaining instances of __unicode__ to [__six.text_type__](https://pythonhosted.org/six/#six.text_type)

### CODE REVIEW

**Comment by amercader** [comment]
@torfsen As the champion of proper unicode handling what do you think of this?

@cclauss I think this is worth adding to the docs for future contributors (probably [here](http://docs.ckan.org/en/latest/contributing/unicode.html)).

More generally I wonder if we should add a section on the contributing docs about using the py2/3 compatible alternatives that @cclauss has been submitting, otherwise us and new contributors won't be aware of them

**Comment by cclauss** [comment]
Added a few more files that we hidden by the __print__ Syntax Errors and also made changes to __unicode.rst__.  It would be helpful if you could also advise on the [__ur'string'__ issues](https://github.com/ckan/ckan/issues/created_by/cclauss) because I do not know how to resolve these and Python 3 Syntax Errors block progress.

**Comment by torfsen** [comment]
In general, I think @cclauss did exactly the right thing. There will probably be some places where we'll run into problems with 3rd-party libraries, because they might have decided to use `bytes` instead of `str` in Python 3 -- I'm especially thinking about the networking stuff (things like #3921). However I'm not sure whether these can be discovered a priori, since we currently don't have a consistent string handling w.r.t. to bytes vs. Unicode in CKAN. Hence, in my opinion, this PR is the right approach, problems can then be figured out when they arise.

W.r.t. to `ur` strings there doesn't seem to be a totally Python 2 + 3 compatible solution. However, the differences between `ur` in Python 2 and `r` in Python 3 seem only to concern `\u` escape sequences -- which we currently don't use in CKAN (at least according to a [quick GitHub search](https://github.com/ckan/ckan/search?utf8=%E2%9C%93&q=%5Cu&type=)). However, we still need to figure out if we can simply use `r` instead of `ur` (which would allow us to use the same code for Python 2 and Python 3). The main use of raw strings is in regular expressions, but I don't know if the `re` module of Python 2 behaves differently for `unicode` vs. `str` patterns (like `%` formatting does, for example).

Also, obviously + 1 for updating the docs on these issues. I also suggest adding a separate page in the documentation regarding Python 2 / 3 compatibility in general.

**Comment by amercader** [comment]
@cclauss can you add the convention of using `six.text_type()` instead of `unicode()` to the Unicode docs page before we merge this? 
http://docs.ckan.org/en/latest/contributing/unicode.html

Cheers

**Comment by cclauss** [comment]
Done.

**Pull request merged**
