### PR TITLE
Consolidate Postgres and Solr install docs

### PR DESCRIPTION
**Pull request by amercader**
Right now people following the package install docs need to jump to the source install docs for setting up Postgres and Solr and are expected to come back to the package install docs once finished. This causes confusion, as in #3085 and #3086.

This changes moves the Postgres and Solr install instructions to separate file which are then included from the package and source install pages, so you don't need to leave them during the install process.

### CODE REVIEW

**Comment by k-nut** [comment]
Seeing how confusing this seems to be I very much like this change!

**Comment by TkTech** [comment]
I think we can start removing any non-multicore solr docs as well, as it's now more than three years obsolete.

**Comment by amercader** [comment]
@TkTech I've removed the old multicore docs but I don't have many experience with the modern approach and the managed schema stuff. Perhaps you can help with this? We would need to take into account the version of Solr that you can install via package on Ubuntu 14.04 (the one that target our packages).

In any case I think this can go into a separate PR. Do you want to merge this one?

**Comment by TkTech** [comment]
@amercader I think you might have gotten that backwards? The multicore docs stick around, the single-core docs disappear (single core mode has been obsolete for 3+ years)

**Comment by amercader** [comment]
@TkTech the multicore docs I removed were meant to for Solr 1.x and involved a lot of manual editing of files, so I think they can be safely removed. As for the new multicore docs, as I said I'm happy with anything that can be done out of the box on the Ubuntu 14.04 packaged Solr version.

**Comment by amercader** [comment]
@TkTech can we get this merged? These are just structural changes and we can deal with the new Solr versions on a separate PR

**Comment by amercader** [comment]
@TkTech bump, would be really good to merge this. I know it's says Solr, but there's nothing controversial here, just structure changes.

**Comment by TkTech** [comment]
Been awhile since I looked at this one so I just gave it another once over. 👍

**Pull request merged**
