### PR TITLE
[#5849] Update for Data Dictionary save logic

### PR DESCRIPTION
**Pull request by Engerrs**

### CODE REVIEW

**Comment by kowh-ai** [comment]
Hi @Engerrs  - Could you please provide a description for this PR please?

**Comment by Engerrs** [comment]
Hi @kowh-ai , there is actually a link to the described issue and this PR is a solution for it. (https://github.com/ckan/ckan/issues/5849)

**Comment by kowh-ai** [comment]
Thanks @Engerrs. @wardi are you able to review Yan's code in this PR. Iv'e taken a look and it's really a little beyond my level of understanding to formally review - thanks

**Comment by wardi** [comment]
Converting the types of fields in-place can be a very expensive operation for large tables, this could even time out making it impossible to submit changes to the data dictionary. In-place type conversions could cause errors that aren't handled here. Successive in-place type conversions could also lose data making the data loaded into the datastore not match what would be there if loaded from csv again.

Those are some of the reasons type_override is implemented in xloader/datapusher, not in datastore itself. xloader/datapusher are already set up to run as separate jobs, always use the source csv so they won't lose data, and can handle and log errors gracefully.

I do like the feature. Maybe it can be implemented as a new API call or background job?

**Comment by Engerrs** [comment]
Hi @wardi , well I can think about it more. New API call sounds reasonable, DEV's can implement their custom view with form that can call the new API endpoint.

**Comment by wardi** [comment]
altering the table might also make sense when setting the types on the columns to a `datastore_create` call instead of the `type_override` in the data dictionary. Right now the types are ignored on existing columns which is a little weird. Altering the table would be better behavior.

An extension could make that call in the background when a user changes the `type_override` in the data dictionary to get the same functionality without the timeout issues.

**Pull request closed without merging**
