### PR TITLE
CKAN Docker Update for 2.9

### PR DESCRIPTION
**Pull request by kowh-ai**
This PR is to update CKAN's Docker install as follows:

- Based on OKFN (https://github.com/okfn/docker-ckan)
- All images will be on DockerHub
- Will include the Dockerfile to build a "local" CKAN image (like the way OKFN does it)
- Base image is Alpine Linux
- CKAN 2.9
- Python 3
- Apache web server is replaced with uWSGI
- A new NGINX Reverse Proxy container 
- Updated versions of other containers (postgresql, solr, datapusher) where applicable
- A rewrite of the Docker Install documentation

**To Do:**

- Rebuild CKAN images and upload to DockerHub after CKAN 2.9 official release is available
- Include **Dev** Docker-compose and Docker components (like OKFN)
- set up automatic builds using Travis / CircleCI
- Migrate to a new repo
- Make sure previous CKAN versions can be taken care of

Note:

- Will be updated when the Official CKAN 2.9 release is ready
- A CKAN DockerHub repository will be used as the official repository

### Features:

- [ ] includes tests covering changes
- [ X] includes updated documentation
- [ X] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by kowh-ai** [comment]
@ckan/core - I think it was mentioned when the Draft version of this PR was discussed (a few moons ago) that a new GitHub Repo might be the best location for this work...I don't have write access so could one of the CKAN Core team please create a new repo for me please and I will continue on this PR...thanks (...maybe called something like this: ckan/ckan-docker-install)

**Comment by amercader** [comment]
@kowh-ai you should be an admin on ckan/ckan-docker now. As discussed on the dev meeting let's:

1. Move everything currently in that repo to a branch
2. Remove all files in the `master` branch and copy whatever files you need from this PR as the initial stage
3. Clearly flag in the README that it is a work in progress
4. Moving forward we can work with PRs on that repo as usual

If you let me know your username there I'll add you to the ckan org on hub.docker.com

**Comment by kowh-ai** [comment]
> If you let me know your username there I'll add you to the ckan org on hub.docker.com

Cool - thanks Adria! - username is: **kowhai**

**Comment by kowh-ai** [comment]
@amercader - on hub.docker.com (ckan org) I'd like to create a couple of repositories: **`ckan-base`** and **`ckan-dev`** but I don't have the permissions as I'm a member, not an owner of ckan. 

Can you please create these for me thanks?

**Comment by amercader** [comment]
@kowh-ai you should have perms now. Please clearly mark these repos as Work in Progress so that people don't use them yet

**Comment by kowh-ai** [comment]
@amercader - I'm looking at the build/testing framework for the new CKAN Docker update - any thoughts of what to do _or_ more importantly, **what not to do**?...

I'm thinking of setting up Travis CI for the https://github.com/ckan/ckan-docker repo

**Comment by amercader** [comment]
@kowh-ai whatever works best for you, if it runs and is green is good with me!
What are you planning on testing? That the images build fine or that CKAN runs fine when running from docker?
IIRC the current Travis tests in this repo test the former

**Comment by EricSoroos** [comment]
Closing -- Activity is now in the https://github.com/ckan/ckan-docker repo

**Pull request closed without merging**
