### PR TITLE
Aligned the spelling of 'boolean' in the documentation.

### PR DESCRIPTION
**Pull request by cafferata**
Fixes #

### Proposed fixes:

Aligned the spelling of 'boolean' in the documentation.

### Features:

- [ ] includes tests covering changes
- [x] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by wardi** [comment]
I think `bool` is better because it matches the python type name

**Comment by cafferata** [comment]
I'm less familiar with Python so I looked it up and I totally agree with you, `bool` goes above `boolean`. I have changed the types changed massively to `bool`.

**Comment by amercader** [comment]
Thanks @cafferata

**Comment by cafferata** [comment]
Thanks for merging. Keep up the good work. 👍

**Pull request merged**
