### PR TITLE
Fixed hardcoded 'Dataset'

### PR DESCRIPTION
**Pull request by ggcatu**
Fixes #

Fixing some hardcoded 'Dataset', 

Breadcrumb, Search form, New 'package'

### CODE REVIEW

**Comment by wardi** [comment]
We just discussed this at our dev meeting and our feeling is we need a new IDatasetForm method that can return the user-visible strings for the type defined. 
e.g.
```python
def get_strings(self):
    return {
        'Datasets': _('Records'),
        'View datasets': _('View records'),
        'Create dataset': _('Create record'),
        'Search datasets': _('Search records'),
        'Add dataset': _('Add record'),
    }
```
This way the strings can be picked up by tools that generate .po files (from core and extensions) instead of requiring them to be manually entered.

This affects the changes merged in #3643 as well. I know this expands the scope of the PR, @ggcatu @mattfullerton do either of you have time to implement this change?

**Comment by ggcatu** [comment]
@wardi and how should #3885 be correctly adressed in the future, as I think that is working only in kind of a hacky way, on the other hand maybe implement a way that a single IDataSetForm can manage multiple schemas.

Correct me if I'm wrong but ckanext-scheming forces you to use the same templates for all the schemas you define?

**Comment by wardi** [comment]
You're right,
```python
get_strings(self, dataset_type):
```
would be better, then scheming and any other IDatasetForms can do their thing properly

**Comment by wardi** [comment]
@ggcatu you can override the template that scheming uses for its pages to split off to per-type ones at the template level. That's a separate issue though, happy to discuss on the ckanext-scheming repo

**Comment by ggcatu** [comment]
Facets filtering was still sending to /dataset.... instead of /datatype

**Comment by kmbn** [comment]
We decided to close old pull requests that are not actively worked on so that we can focus our effort and attention on PRs made against the current version of CKAN. A lot has changed in the last several months and many PRs will have gone stale or may now be in conflict with the latest version.

Please note: this isn't a judgement about the quality of your pull request. We just don't have the resources to review older PRs.

If you would like to reopen your PR (and update it if necessary), please do!

**Pull request closed without merging**
