### PR TITLE
[#3598] Adding two new methods for IPackageController

### PR DESCRIPTION
**Pull request by Engerrs**
Added two methods to IPackageController, so that user can hook the dict that he sends before the actual create/update.
Modified their name in order to solve the issue with naming conflicts.

### CODE REVIEW

**Comment by wardi** [comment]
@Engerrs this change overlaps with functionality already available by implementing validation in an IDatasetForm (even better it works per-dataset-type) or by chaining the package_create/package_update actions themselves. I'm reluctant to add a third way to modify data passed by the user unless there's a really compelling reason.

**Comment by wardi** [comment]
@Engerrs here's the best place to override package_creation/updating the way you want: https://github.com/ckan/ckan/blob/master/ckan/plugins/interfaces.py#L1267

you get the data_dict to make any changes you want, then end your function with a
```python
return ckan.plugins.toolkit.navl_validate(...)
```

Looks like this method isn't in the docs where it should be. Also the docstring is a little scarier than probably necessary. I'll try to fix that.

**Comment by rossjones** [comment]
@wardi I guess it's safe to close this now if it is unnecessary.

**Comment by gt-novelt** [comment]
In case anyone is looking for the line @wardi was referring to, here is the permalink : https://github.com/ckan/ckan/blob/02e65d05815912e7afbe40094f8aa104a2ab64b3/ckan/plugins/interfaces.py#L1284

**Comment by kmbn** [comment]
We decided to close old pull requests that are not actively worked on so that we can focus our effort and attention on PRs made against the current version of CKAN. A lot has changed in the last several months and many PRs will have gone stale or may now be in conflict with the latest version.

Please note: this isn't a judgement about the quality of your pull request. We just don't have the resources to review older PRs.

If you would like to reopen your PR (and update it if necessary), please do!

**Pull request closed without merging**
