### PR TITLE
Update textview extension assets

### PR DESCRIPTION
**Pull request by pdelboca**
Some webassets are out of sync.

This PR adds some missing assets to the `textview` extension.

This is the output of executing `npm run postinstall`.

### CODE REVIEW

**Comment by wardi** [comment]
I'd moved some of these to webassets directories, did I miss updating a file that pointed to the public folder? https://github.com/ckan/ckan/pull/7505

**Comment by pdelboca** [comment]
@wardi thanks for the clarification!

Our `gulpfile.js` still copy this files to the theme folder. I'm gonna clean those lines in another PR. thanks!

**Comment by wardi** [comment]
Thanks @pdelboca I didn't know about gulpfile.js
I've also added another copy of highlight.js for the data API dialog in https://github.com/ckan/ckan/pull/7578 this one built with just the 5 languages needed for the examples (bash, javascript, powershell, python and R)

Sounds like I should add this to the gulpfile as well, right?

**Comment by pdelboca** [comment]
@wardi it is unclear.

I assume that we handle our frontend dependencies using gulp given that we have a command for it. The documentation its not quite clear either: https://docs.ckan.org/en/2.10/contributing/frontend/index.html?highlight=gulp#install-frontend-dependencies

Let's discuss it tomorrow in the CKAN Tech Meeting.

**Pull request closed without merging**
