### PR TITLE
[#5820] fix invite user with existing email error

### PR DESCRIPTION
**Pull request by mutantsan**
Fix for issue #5820 
I've added validators and catch the ValidationError.

### Features:

- [X] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [X] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by pdelboca** [comment]
This one looks good @amercader @wardi @mutantsan!

image

**Comment by amercader** [comment]
This looks great @mutantsan ,can you fix the conflicts so I can merge? Cheers

**Comment by amercader** [comment]
Sorry @mutantsan still some failures

**Comment by amercader** [comment]
@mutantsan I tried to fix the failures as it looked like a straight forward missing var but I'm still getting some failures after fixing that:

https://app.circleci.com/pipelines/github/ckan/ckan/2276/workflows/bbc52af2-a283-42ac-9bbf-c42aa59493fe/jobs/10018/tests#failed-test-1

My changes:

https://github.com/ckan/ckan/compare/mutantsan-5820-invite-user-with-existing-email

**Comment by mutantsan** [comment]
Sorry, @amercader , that's my fault. I had to fix it immediately.
But I don't understand what are those failed tests. I don't have these errors locally :(

**Comment by amercader** [comment]
@mutantsan I re-run the tests and they passed: https://app.circleci.com/pipelines/github/ckan/ckan/2810/workflows/d0cb749a-9b79-4d7c-af32-b70e34daff04

If you fix the conflicts I'll merge this and backport it

**Comment by amercader** [comment]
This was merged to master already (https://github.com/ckan/ckan/commit/5708fc2ab500264680b027d0094124c70c3d9404), I've backported it to 2.9

**Pull request closed without merging**
