### PR TITLE
Remove old useless scripts in /bin

### PR DESCRIPTION
**Pull request by davidread**

### CODE REVIEW

**Comment by wardi** [comment]
big +1 from me

**Comment by wardi** [comment]
This would let us remove the ckanclient dev dependency too. The only other thing I see using it is a couple tests of questionable value in ckan/tests/legacy/wsgi_ckanclient.py.

**Comment by davidread** [comment]
Sounds good, I'll do it.

**Comment by wardi** [comment]
@joetsoi can I steal the assignment from you? I'm itching to merge this

**Comment by wardi** [comment]
love it

**Pull request merged**
