### PR TITLE
resource upload button position fixed

### PR DESCRIPTION
**Pull request by sagargg**
Borken UI fix for resource file remove 

**Before**
Screen Shot 2022-02-12 at 6 53 44 PM
**After**
Screen Shot 2022-02-12 at 6 53 58 PM

### CODE REVIEW

**Comment by pdelboca** [comment]
Thanks @sagargg ! Looks good the right alignment.

However, in my browsers the top alignment it's a little bit off (I'm testing both with Firefox and Chrome):
image

Is it also happening to you? :thinking:

**Comment by sagargg** [comment]
Hi @pdelboca , I've tested on safari, firefox and chrome, it is showing correct alignment for me.

**Comment by amercader** [comment]
@sagargg I can also see the mis-alignement on my local branch:

Screenshot 2022-02-18 at 15-00-34 Add resource - priva dataset - CKAN


And the button caption does not match ("Remove" vs "Clear upload"), so maybe that's a clue as to what is going on

**Comment by pdelboca** [comment]
Closing this as it has been fixed in https://github.com/ckan/ckan/pull/6801.

Thanks for this @sagargg !!

**Pull request closed without merging**
