### PR TITLE
Update bootstrap to version 3

### PR DESCRIPTION
**Pull request by mbocevski**
Since no updates have happened on #2602, we've gone ahead and did the update to bootstrap 3.3.7 on CKAN core. Thanks to @gocemitevski for doing the work. Please review and if any issues come up let's resolve them.

### Summary of changes:
- Removed deprecated classes from bootstrap2 and migrated to their respective counterparts in bootstrap3
- Rewrite of all LESS variables and remove duplication of LESS variables. 
- Separated the CKAN LESS variables which didn't exist in the bootstrap namespace
- Fontawesome updated to latest version and imported through LESS
- Update to latest bootstrap JS files
- General responsive design fixes.

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ X] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by amercader** [comment]
@mbocevski @gocemitevski This is fantastic, but there are several conflicts because it's based off the release-v2.5.2. Can you please rebase it so it targets the current master branch and it only includes your commits?

Otherwise it's really difficult to review and discuss

**Comment by mbocevski** [comment]
@amercader rebased onto master. Do you like to scratch this PR and we create a new PR or this will do?

**Comment by amercader** [comment]
@mbocevski new one please

**Comment by mbocevski** [comment]
Closing to reopen PR

**Pull request closed without merging**
