### PR TITLE
admin Blueprint

### PR DESCRIPTION
**Pull request by smotornyuk**
Based on #3762 and, as result, on #3239

### CODE REVIEW

**Comment by amercader** [comment]
Can you merge latest master @smotornyuk ?

**Comment by smotornyuk** [comment]
Done. And now there are no problem with `_link_active`

**Comment by amercader** [comment]
@smotornyuk one tiny thing and this is good to merge. Huge improvement on the form!

**Comment by amercader** [comment]
Not sure where these error failures are coming from. They should also be failing in master?

**Comment by smotornyuk** [comment]
These errors seems to be related to feed generation. I'll try to check it on master as soon as I have finished our client's tasks. 
But yes, this is not related to admin controller. As for your previous comment - `one tiny thing and this is good to merge` - did you forgot to commit review comment? Or what small change are you meaning?)

**Comment by amercader** [comment]
@smotornyuk I forgot to send the review :|

**Comment by amercader** [comment]
:tada: thanks @smotornyuk !

**Pull request merged**
