### PR TITLE
Remove embedded_dataviewer() and its blueprint endpoint 

### LINKED ISSUE #6383: Missing resource_embedded_dataviewer.html or misnamed template file
**CKAN version**
2.9.3

**Describe the bug**
Missing or incorrectly named template file

**Steps to reproduce**

Create a dataset with a resource and then go to the resource url and append `/embed` at the end, it causes an internal server error - `TemplateNotFound: package/resource_embedded_dataviewer.html`

**Expected behavior**
The resource to be correctly returned from the request.

**Additional details**
This is the line with the template filename - 

https://github.com/ckan/ckan/blob/master/ckan/views/resource.py#L875

### PR DESCRIPTION
**Pull request by TomeCirun**
Fixes #6383

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [x] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by amercader** [comment]
See https://github.com/ckan/ckan/issues/6383#issuecomment-932153629

**Comment by TomeCirun** [comment]
image

**Comment by TomeCirun** [comment]
polite reminder :)

**Comment by amercader** [comment]
Thanks @TomeCirun

**Pull request merged**
