### PR TITLE
Upgrade psycopg2, fixes ckan/ckan#4837

### LINKED ISSUE #4837: psycopg2 version depends on old libssl
### CKAN Version if known (or site URL)
2.8.2

### Please describe the expected behaviour
CKAN works with up-to-date libssl

### Please describe the actual behaviour
psycopg segfaults if running environment has libssl 1.1 or newer:
```
#0  0x00007f662989ac1b in ssl3_cleanup_key_block ()
   from target:/usr/lib/ckan/default/lib/python2.7/site-packages/psycopg2/.libs/./libssl-fad88670.so.1.0.2l
#1  0x00007f6629898516 in ssl3_clear ()
   from target:/usr/lib/ckan/default/lib/python2.7/site-packages/psycopg2/.libs/./libssl-fad88670.so.1.0.2l
#2  0x00007f66298a40a9 in tls1_clear ()
   from target:/usr/lib/ckan/default/lib/python2.7/site-packages/psycopg2/.libs/./libssl-fad88670.so.1.0.2l
#3  0x00007f663ecb79d2 in SSL_new () from target:/usr/lib/x86_64-linux-gnu/libssl.so.1.1
#4  0x00007f6629b2f389 in ?? () from target:/usr/lib/ckan/default/lib/python2.7/site-packages/psycopg2/.libs/libpq-909a53d8.so.5.10
#5  0x00007f6629b30925 in ?? () from target:/usr/lib/ckan/default/lib/python2.7/site-packages/psycopg2/.libs/libpq-909a53d8.so.5.10
#6  0x00007f6629b1a600 in PQconnectPoll ()
   from target:/usr/lib/ckan/default/lib/python2.7/site-packages/psycopg2/.libs/libpq-909a53d8.so.5.10
#7  0x00007f6629b1b099 in ?? () from target:/usr/lib/ckan/default/lib/python2.7/site-packages/psycopg2/.libs/libpq-909a53d8.so.5.10
#8  0x00007f6629b1de9f in PQconnectdb ()
   from target:/usr/lib/ckan/default/lib/python2.7/site-packages/psycopg2/.libs/libpq-909a53d8.so.5.10
#9  0x00007f6629d6e4d1 in _conn_sync_connect (self=0x7f662a1baa10) at psycopg/connection_int.c:716
#10 conn_connect (self=self@entry=0x7f662a1baa10, async=<optimized out>) at psycopg/connection_int.c:812
...
```
Notice the two libssl versions. A related psycopg2 issue: psycopg/psycopg2#543

### What steps can be taken to reproduce the issue? 
Install libssl 1.1 on server, restart apache2 and try to open the front page.

The issue can be resolved by updating to `psycopg2==2.8.2`

### PR DESCRIPTION
**Pull request by bzar**
Fixes #4837 

### Proposed fixes:
Upgrade psycopg2 to version 2.8.2

### Features:

- [ ] includes tests covering changes
- [X] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [X] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by bzar** [comment]
The test errors seem to result from the same source as in django: lcd1232/django-postgrespool2#11. The issue is described in a PR to the same repository lcd1232/django-postgrespool2#12. Trying to find out where to insert the same fix: https://github.com/lcd1232/django-postgrespool2/pull/12/files#diff-81ec40a918dd202e487e160513255b32R56

**Comment by amercader** [comment]
We won't backport the requirement as it's too risky, but we will mention it on the CHANGELOG.
We will backport the small code change related to the `connection` property, which should be able to handle both versions of psycopg2 (via some `AttributeError` catching or similar)

Does this make sense @bzar ?

**Comment by bzar** [comment]
Yes, that makes sense. There's no telling what other non obvious side effects the upgrade has and it shouldn't for now be done unless it's necessary. The compatibility fix should work either way.

**Comment by amercader** [comment]
Added just the code change in 2.8 as agreed (f9aaf910a). Apparently the new syntax (3 `connection`) is compatible with the psycopg2 version used in CKAN 2.8 (2.7.3.2), probably because the second connection is just a pool, but to be safe I added an `AttributeError` check.

**Comment by cesarjorgemartinez** [comment]
Hi, when to release a new 2.8.x version to use psycopg2 2.8.4?

Regards

**Comment by wardi** [comment]
Note that for backporting as far back as 2.6 `psycopg2==2.7.7` works for postgres 10 and the updated ssl libraries (e.g. on travis) but also prevents this error that happens with `psycopg2==2.8.2`

```python-traceback
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DBAPIError: (UndefinedTable) relation "user" does not exist
LINE 2: FROM "user"
...
```

**Pull request merged**
