### PR TITLE
Upgrade cypress and axe

### PR DESCRIPTION
**Pull request by Zharktas**
### Proposed fixes:
Upgrades Cypress and axe as they weren't previously updated due to incompatibilities.

**Fixes build warnings in docs.**

### Features:

- [ ] includes tests covering changes
- [x] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Review by jj-crypto — APPROVED** [review]

**Comment by amercader** [comment]
@Zharktas do you know why the `package.lock` file grew so much with these changes?

**Comment by amercader** [comment]
@Zharktas looks like this changed the `"lockfileVersion": 2`, probably because of using one of the latest node versions.
@EricSoroos suggested to perhaps wait on this as it can lead to reproducibility errors (let me know if I didn't get that right). Do you have any thoughts on this?

In any case it looks like if we go for it we should do the minimum Node version / package.lock format upgrade in a separate PR

**Comment by Zharktas** [comment]
@amercader I've upgraded the package.lock version as our github actions upgrade it every time as example here: https://github.com/ckan/ckan/actions/runs/1411142934

image

Should have probably mention it though.

**Comment by amercader** [comment]
@Zharktas fair enough. Does this mean that we need to document a minimum Node version for running the tests locally?

**Comment by Zharktas** [comment]
The new version is however backwards compatible https://github.blog/2021-02-02-npm-7-is-now-generally-available/#changes-to-the-lockfile, so it should not matter.

**Comment by Zharktas** [comment]
@amercader I removed the documentation fixes as they where fixed elsewhere, this would be good to merge unless you feel that lock-file version change should be done in separate PR. I can rerun this with older npm if you wish.

**Comment by amercader** [comment]
Let's  merge this as is, if that causes issues we can revisit it. Thanks @Zharktas

**Pull request merged**
