### PR TITLE
Update issue templates, other Github integration improvements

### PR DESCRIPTION
**Pull request by amercader**
Some changes on the issue template to hopefully direct users to the correct channel for each request.
Also change the code of conduct file name and format so it is picked up by the [Github Community page](https://github.com/ckan/ckan/community)

### CODE REVIEW

**Comment by amercader** [comment]
Pull to a clone

**Comment by wardi** [comment]
here's a clone with the changes. https://github.com/wardi/ckan-gh-integration/issues/new/choose Looks great!

**Comment by wardi** [comment]
where does the code of conduct appear in the github interface?

**Comment by amercader** [comment]
@wardi it should appear linked here: https://github.com/wardi/ckan-gh-integration/community, and in fact the link to the file works but I'm not sure why is still marked as yellow

**Pull request merged**
