### PR TITLE
Created breadcrumbs.html file

### LINKED ISSUE #4494: "Edit on GitHub" links on docs.ckan.org are broken
https://docs.ckan.org/en/latest/extensions/index.html links to
https://github.com/ckan/ckan/blob/master/home/docs/checkouts/readthedocs.org/user_builds/ckan/checkouts/latest/doc/conf.py/extensions/index.rst
instead of
https://github.com/ckan/ckan/blob/master/doc/extensions/index.rst

### PR DESCRIPTION
**Pull request by iamarnavgarg**
Fixes #4494 
Created a new breadcrumbs file in layout which implements the redirection of url.

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by iamarnavgarg** [comment]
Hello @amercader @wardi sir, would request you to please look into this PR.
Thanks!

**Comment by amercader** [comment]
@iamarnavgarg thanks for your PR, don't worry it will get looked at. Sometimes it's difficult to find the time.

**Comment by iamarnavgarg** [comment]
@amercader it's alright sir

**Comment by iamarnavgarg** [comment]
Hello @amercader now will it be possible for you to review it?
Thanks!

**Comment by iamarnavgarg** [comment]
Hello @amercader, will it now be possible for you to review it?
Thanks!

**Comment by iamarnavgarg** [comment]
Hi @amercader , request you to please merge this PR.

Thanks!

**Comment by pdelboca** [comment]
Thanks for this PR! I'm closing it due to inactivity as a general cleanup of our PRs.

It could be open anytime if anyone considers it important again.

**Pull request closed without merging**
