### PR TITLE
[#3215] Fix paster user add does not support apikey as described in help text

### PR DESCRIPTION
**Pull request by wildcatzita**

### CODE REVIEW

**Comment by wildcatzita** [comment]
Fix for [issue](https://github.com/ckan/ckan/issues/3215)

**Comment by wardi** [comment]
there seem to be some unrelated changes in this PR, would you like to rebase or manually remove them?

**Comment by wildcatzita** [comment]
Ok, I'll look at it

**Comment by wildcatzita** [comment]
@wardi , fixed. Can you please check?

**Comment by kmbn** [comment]
We decided to close old pull requests that are not actively worked on so that we can focus our effort and attention on PRs made against the current version of CKAN. A lot has changed in the last several months and many PRs will have gone stale or may now be in conflict with the latest version.

Please note: this isn't a judgement about the quality of your pull request. We just don't have the resources to review older PRs.

If you would like to reopen your PR (and update it if necessary), please do!

**Pull request closed without merging**
