### PR TITLE
update the python 3.6 to 3.7 in doc.

### LINKED ISSUE #6549: Syntax error on python 3.6 and on 3.8
**CKAN version**
master

**Describe the bug**
Running cli commands results in syntax error with python 3.6
```
SyntaxError: future feature annotations is not defined
```

We could either fix the error or bump our minimum python version to 3.7 as 3.6 end of life date is in a month anyway. 

On python 3.8, master produces different error:

```
from typing_extensions import TypedDict
ModuleNotFoundError: No module named 'typing_extensions'
```

### PR DESCRIPTION
**Pull request by Sunny-NEC**
Fixes #6549 

### Proposed fixes:
 3.6 end of life date  in a month , update python version 3.6 to 3.7 in  documents.
and  update the docs to reflect that master requires Python 3.7
### Features:

- [ ] includes tests covering changes
- [X] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by kowh-ai** [comment]
@Sunny-NEC - Could you please make sure Ubuntu 18.04 includes Python 3.7 by default? It used to. If not then please amend to mention if you are installing on Ubuntu 18.04 Python 3.7 should be used. Also please mention that Python 3.7 and Python 3.8 are supported by CKAN 2.9.x wherever possible - thanks

**Comment by frafra** [comment]
Ubuntu 18.04 uses Python 3.6, even if is EOL: https://packages.ubuntu.com/bionic/python3
I also work on a Linux box with the same Ubuntu 18.04, and it has the same problem, so many relies on the deadsnakes PPA.

**Comment by frafra** [comment]
I am working to make CKAN master compatible with Python 3.8+: #6692

**Comment by smotornyuk** [comment]
So, what's the point of using TypedDict from typing? 
CKAN has [typing_extensions](https://github.com/ckan/ckan/blob/master/requirements.txt#L120) added to requirements which means we can import TypedDict from typing_extensions all the time. And, in its turn, `typing_extensions` will import TypedDict from `typing` whenever it's available.

In the future, when we drop python v3.7 support, we can start using `TypedDict` from `typing` if it really bothers you, but now I don't see any real value in #6692

**Comment by frafra** [comment]
> CKAN has [typing_extensions](https://github.com/ckan/ckan/blob/master/requirements.txt#L120) added to requirements which means we can import TypedDict from typing_extensions all the time.

Python 3.8 cannot import `typing_extensions` according to https://github.com/ckan/ckan/issues/6549#issue-1057065172.

It looks like the problem is not `typing_extensions` not being available in Python 3.8, as I made a test:

```
cat << EOF > test.py
import os
import platform
import subprocess
subprocess.call(['pip', 'install', 'typing_extensions==4.0.0'], stdout=open(os.devnull, 'wb'))

print("Python", platform.python_version())
try:
    from typing_extensions import TypedDict
    print("TypedDict from typing_extensions")
except:
    typed_dict = False
try:
    from typing import TypedDict
    print("TypedDict from typing")
except:
    pass
EOF

for version in 3.{5,6,7,8,9,10}; do
    docker run --rm -v $PWD/test.py:/test.py python:${version}-alpine python /test.py
done 2>/dev/null
```

Result:
```
Python 3.5.10
Python 3.6.15
TypedDict from typing_extensions
Python 3.7.12
TypedDict from typing_extensions
Python 3.8.12
TypedDict from typing_extensions
TypedDict from typing
Python 3.9.10
TypedDict from typing_extensions
TypedDict from typing
Python 3.10.2
TypedDict from typing_extensions
TypedDict from typing
```

**Comment by frafra** [comment]
This is the failing test: `ckan.lib.search.common.SearchError: SOLR schema version not supported: 1.6. Supported versions are [2.8, 2.9]`. It does not seem related to this PR.

I would propose to merge this PR.

**Comment by Gauravp-NEC** [comment]
@kowh-ai , What is left to do in this PR?

**Comment by Gauravp-NEC** [comment]
@kowh-ai , What is left to do in this PR?

**Comment by Gauravp-NEC** [comment]
@kowh-ai , You can close this PR in favour of https://github.com/ckan/ckan/pull/6740 where rework is done and there is no conflict.

**Pull request closed without merging**
