### PR TITLE
Removed API info links for api queries

### LINKED ISSUE #3076: Datastore API Demo modal window encourages robots to make needless queries
### CKAN Version if known (or site URL)
2.1 ---> 2.5.2 http://demo.ckan.org/dataset/gold-prices/resource/b9aae52b-b082-4159-b46f-7bb9c158d013

### Please describe the expected behaviour
the CKAN Data API modal window designed to demonstrate the syntax for using the datastore API should not encourage robots to make queries against the database

### Please describe the actual behaviour
the modal window includes hyperlinked text for all resources ...

```
Query example (first 5 results)
http://demo.ckan.org/api/action/datastore_search?resource_id=b9aae52b-b082-4159-b46f-7bb9c158d013&limit=5
Query example (results containing 'jones')
http://demo.ckan.org/api/action/datastore_search?resource_id=b9aae52b-b082-4159-b46f-7bb9c158d013&q=jones
Query example (via SQL statement)
http://demo.ckan.org/api/action/datastore_search_sql?sql=SELECT * from "b9aae52b-b082-4159-b46f-7bb9c158d013" WHERE title LIKE 'jones'
```

These hyperlinks encourage robots - that do not follow robots.txt instructions - to conduct needless queries that result in db errors against all the data resources.

### What steps can be taken to reproduce the issue? 
The modal window  [page template ](https://github.com/ckan/ckan/blob/b7204bb307abb1f488b5d409262db40b1e840d59/ckan/templates/ajax_snippets/api_info.html) should be redone to remove the hyperlinks.

### PR DESCRIPTION
**Pull request by jrods**
Fixes #3076 

### Proposed fixes:

Removing the api link examples to help prevent robots that don't listen to robot.txt from
calling needless querys on the api

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [x] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

Issue #3076 - Help to prevent robots that don't listen to robot.txt from
calling needless querys on api links

### CODE REVIEW

**Comment by wardi** [comment]
I'm fine with this change, but I wonder why this template isn't under ckanext/datastore. It looks very datastore-specific

**Comment by jrods** [comment]
@wardi datastore doesn't have a templates directory setup, and what's currently being use to get the api_info template is using an api call to get snippet, which from the looks of it, uses the base.render method

**Comment by mattfullerton** [comment]
Also confusing is that this snippet gets inserted as soon as datastore is enabled and independent of whether the data is actually in the datastore:
https://github.com/ckan/ckan/blob/master/ckan/templates/package/resource_read.html#L48

**Comment by jrods** [comment]
Oops, messing up git, will reopen a new PR

**Pull request closed without merging**
