### PR TITLE
CLI. Implements `plugin-info` command

### PR DESCRIPTION
**Pull request by pdelboca**
This PR implements the plugin-info command as described in #4639.

### CODE REVIEW

**Comment by pdelboca** [comment]
Oh, I forgot to prefix the string literals. I'll be updating this PR later today.

**Comment by amercader** [comment]
Thanks @pdelboca !

**Comment by pwalsh** [comment]
> Oh, I forgot to prefix the string literals. I'll be updating this PR later today.

@pdelboca @amercader I know I'm late to the party with https://github.com/ckan/ckan/pull/4896/files but `from __future__ import unicode_literals` in every source file, rather than prefixing everywhere, might be more manageable across the whole codebase.

**Comment by amercader** [comment]
@pwalsh you have awaken an ancient beast!

See here for previous discussion about this:

https://github.com/ckan/ckan/pull/3049
https://github.com/ckan/ckan/pull/3068

Current guidelines:
https://docs.ckan.org/en/latest/contributing/unicode.html

**Pull request merged**
