### PR TITLE
increase the strength of the password reset token

### PR DESCRIPTION
**Pull request by anotheredward**
This is the first PR to merge features from the plugin:
https://github.com/data-govt-nz/ckanext-security/issues/2
into ckan core

### Fixes 
Having weak/predictable password reset tokens

### Proposed fixes:
Use a longer password reset token from a less predictable source. 

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by wardi** [comment]
@anotheredward looks like you're missing an `import os`

**Comment by anotheredward** [comment]
Thanks @wardi , I've added the missing import.

**Comment by anotheredward** [comment]
While this is the code we currently have in the ckan-security module, would
`random.SystemRandom`
be more appropriate?

I see that we use that elsewhere in the code base for cryptographically secure random number generation.

**Comment by TkTech** [comment]
@anotheredward `random.SystemRandom()` just provides the top-level `random` interface, but with `urandom` as the source. Just using `urandom` directly in this case is fine.

**Pull request merged**
