### PR TITLE
Make it possible to add a dataset without adding data.

### PR DESCRIPTION
**Pull request by mattfullerton**
This has probably been discussed before somewhere so I expect this will be rejected. But one use case is when a user is unsure whether the data upload will be successful and doesn't want to risk creating an orphaned dataset and hence lose the name (slug). I'm sure there are a few edge CKAN use cases where a user does not want to add any resources.

This code is probably not the best, I did this in a hurry. If the feature is actually desired I can work on it some more.

### CODE REVIEW

**Comment by amercader** [comment]
Migration from previous versions: custom python code that gets all resource ids from the datastore database and adds an extra manually to the resource table.

**Comment by mattfullerton** [comment]
@amercader Should I understand that comment?

**Comment by amercader** [comment]
@mattfullerton sorry, wrong PR

**Comment by amercader** [comment]
Closing in favour of #2327

**Pull request closed without merging**
