### PR TITLE
[WIP] Add Vagrant build for CKAN 2.7.2

### PR DESCRIPTION
**Pull request by ad-m**
Not for every optimum solution is to use Docker in an automated test & development environment. It can give you limitations when testing extensions espacially. I've developed a series of scripts that make it possible to create a stack efficiently in the Vagrant environment.

The entire environment will be available after the command is executed:
```
vagrant up 
```

Alternatively, it is possible to perform stepwise during testing of building:
```bash
for file in ./contrib/vagrant/bin/??_*.sh; do
    name=$(basename "$file"); 
    vagrant ssh default -c "/vagrant/contrib/vagrant/bin/$name"; 
    vagrant snapshot save default "$name"; 
done;
```

This is a proposal for change, so no docs at all. I assume the code will be extended, including CI integration to provide additional automated testing. Starting from the branches of ``ckan-2.7.2``, I get errors during testing and after many hours I have no idea about the source of the problem. 

The last lines of the test result:
```
$ ./contrib/vagrant/bin/run_ckan_test ckanext

(…)

ERROR: ckanext.reclineview.tests.test_view.TestReclineViewDatastoreOnly.test_create_datastore_only_view
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/vagrant/ckanext/reclineview/tests/test_view.py", line 121, in test_create_datastore_only_view
    result = self.app.get(url)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/fixture.py", line 208, in get
    return self.do_request(req, status=status)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/fixture.py", line 389, in do_request
    **req.environ)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/wsgilib.py", line 343, in raw_interactive
    app_iter = application(basic_environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/lint.py", line 170, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/vagrant/ckan/config/middleware/__init__.py", line 136, in __call__
    return self.apps[app_name](environ, start_response)
  File "/vagrant/ckan/config/middleware/common_middleware.py", line 216, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/cascade.py", line 130, in __call__
    return self.apps[-1](environ, start_response)
  File "/vagrant/ckan/config/middleware/common_middleware.py", line 61, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
    app_iter = self.application(environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
    app_iter = app(environ, wrapper.wrap_start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/middleware.py", line 201, in __call__
    self.app, environ, catch_exc_info=True)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/util.py", line 94, in call_wsgi_application
    app_iter = application(environ, start_response)
  File "/usr/lib/ckan/default/local/lib/p_metadata" does not existython2.7/site-packages/weberror/errormiddleware.py", line 165, in __call__
    return self.application(environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
    return request.get_response(self.app)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
    response = request.get_response(self.app)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/vagrant/ckan/config/middleware/pylons_app.py", line 250, in inner
    result = application(environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/middleware.py", line 73, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/routes/middleware.py", line 131, in __call__
    response = self.app(environ, start_response)
  File "/vagrant/ckan/config/middleware/common_middleware.py", line 80, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/wsgiapp.py", line 125, in __call__
    response = self.dispatch(controller, environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/wsgiapp.py", line 324, in dispatch
    return controller(environ, start_response)
  File "/vagrant/ckan/lib/base.py", line 212, in __call__
    res = WSGIController.__call__(self, environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/controllers/core.py", line 221, in __call__
    response = self._dispatch_call()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/controllers/core.py", line 172, in _dispatch_call
    response = self._inspect_call(func)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/controllers/core.py", line 107, in _inspect_call
    result = self._perform_call(func, args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/controllers/core.py", line 60, in _perform_call
    return func(**args)
  File "/vagrant/ckan/controllers/package.py", line 1123, in resource_read
    return render(template, extra_vars=vars)
  File "/vagrant/ckan/lib/base.py", line 177, in render
    return cached_template(template_name, render_template)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/templating.py", line 249, in cached_template
    return render_func()
  File "/vagrant/ckan/lib/base.py", line 131, in render_template
    return render_jinja2(template_name, globs)
  File "/vagrant/ckan/lib/base.py", line 88, in render_jinja2
    return template.render(**extra_vars)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/vagrant/ckanext/datastore/templates/package/resource_read.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/vagrant/ckan/templates/package/resource_read.html", line 3, in top-level template code
    {% set res = c.resource %}
  File "/vagrant/ckan/templates/package/base.html", line 3, in top-level template code
    {% set pkg = c.pkg_dict or pkg_dict %}
  File "/vagrant/ckan/templates/page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/vagrant/ckan/templates/base.html", line 103, in top-level template code
    {%- block page %}{% endblock -%}
  File "/vagrant/ckan/templates/page.html", line 19, in block "page"
    {%- block content %}
  File "/vagrant/ckan/templates/page.html", line 22, in block "content"
    {% block main_content %}
  File "/vagrant/ckan/templates/page.html", line 54, in block "main_content"
    {% block pre_primary %}
  File "/vagrant/ckan/templates/package/resource_read.html", line 22, in block "pre_primary"
    {% block resource %}
  File "/vagrant/ckan/templates/package/resource_read.html", line 24, in block "resource"
    {% block resource_inner %}
  File "/vagrant/ckan/templates/package/resource_read.html", line 73, in block "resource_inner"
    {% block data_preview %}
  File "/vagrant/ckan/templates/package/resource_read.html", line 74, in block "data_preview"
    {% block resource_view %}
  File "/vagrant/ckan/templates/package/resource_read.html", line 88, in block "resource_view"
    {% block resource_view_content %}
  File "/vagrant/ckan/templates/package/resource_read.html", line 98, in block "resource_view_content"
    {% snippet 'package/snippets/resource_view.html',
  File "/vagrant/ckan/lib/jinja_extensions.py", line 246, in _call
    return base.render_snippet(args[0], **kwargs)
  File "/vagrant/ckan/lib/base.py", line 78, in render_snippet
    renderer='snippet')
  File "/vagrant/ckan/lib/base.py", line 177, in render
    return cached_template(template_name, render_template)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/templating.py", line 249, in cached_template
    return render_func()
  File "/vagrant/ckan/lib/base.py", line 131, in render_template
    return render_jinja2(template_name, globs)
  File "/vagrant/ckan/lib/base.py", line 88, in render_jinja2
    return template.render(**extra_vars)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/vagrant/ckan/templates/package/snippets/resource_view.html", line 3, in top-level template code
    {% block resource_view %}
  File "/vagrant/ckan/templates/package/snippets/resource_view.html", line 16, in block "resource_view"
    {% snippet 'package/snippets/resource_view_filters.html', resource=resource %}
  File "/vagrant/ckan/lib/jinja_extensions.py", line 246, in _call
    return base.render_snippet(args[0], **kwargs)
  File "/vagrant/ckan/lib/base.py", line 78, in render_snippet
    renderer='snippet')
  File "/vagrant/ckan/lib/base.py", line 177, in render
    return cached_template(template_name, render_template)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/templating.py", line 249, in cached_template
    return render_func()
  File "/vagrant/ckan/lib/base.py", line 131, in render_template
    return render_jinja2(template_name, globs)
  File "/vagrant/ckan/lib/base.py", line 88, in render_jinja2
    return template.render(**extra_vars)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/vagrant/ckan/templates/package/snippets/resource_view_filters.html", line 5, in top-level template code
    data-module-fields="{{ h.dump_json(h.resource_view_get_fields(resource)) }}"
  File "/vagrant/ckan/lib/helpers.py", line 2063, in resource_view_get_fields
    result = logic.get_action('datastore_search')({}, data)
  File "/vagrant/ckan/logic/__init__.py", line 457, in wrapped
    result = _action(context, data_dict, **kw)
  File "/vagrant/ckan/logic/__init__.py", line 576, in wrapper
    return action(context, data_dict)
  File "/vagrant/ckanext/datastore/logic/action.py", line 453, in datastore_search
    res_exists, real_id = backend.resource_id_from_alias(res_id)
  File "/vagrant/ckanext/datastore/backend/postgres.py", line 1903, in resource_id_from_alias
    results = self._get_write_engine().execute(resources_sql, id=alias)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1690, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 727, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 824, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
    context)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
    context)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) relation "_table_metadata" does not exist
LINE 1: SELECT alias_of FROM "_table_metadata"
                             ^
 'SELECT alias_of FROM "_table_metadata"\n                                        WHERE name = %(id)s' {'id': u'af18a06c-46bf-40fd-a5e8-0337c2b3b6da'}
-------------------- >> begin captured logging << --------------------
ckan.model: INFO: Database table data deleted
ckan.model: INFO: Database initialised
ckan.model: INFO: Database rebuilt
ckan.model: INFO: Database table data deleted
ckan.model: INFO: Database initialised
ckan.model: INFO: Database rebuilt
factory.generate: DEBUG: BaseFactory: Preparing ckan.tests.factories.Dataset(extra={})
factory.containers: DEBUG: LazyStub: Computing values for ckan.tests.factories.Dataset(notes='Just another test dataset.', name=<OrderedDeclarationWrapper for <factory.declarations.Sequence object at 0x7f53ac2e1510>>, title='Test Dataset')
factory.generate: DEBUG: Sequence: Computing next value of <function <lambda> at 0x7f53ac2e4de8> for seq=53
factory.containers: DEBUG: LazyStub: Computed values, got ckan.tests.factories.Dataset(notes='Just another test dataset.', name='test_dataset_53', title='Test Dataset')
factory.generate: DEBUG: BaseFactory: Generating ckan.tests.factories.Dataset(notes='Just another test dataset.', name='test_dataset_53', title='Test Dataset')
ckan.model.modification: ERROR: (ProgrammingError) relation "_table_metadata" does not exist
LINE 1: SELECT 1 FROM "_table_metadata"
                      ^
 'SELECT 1 FROM "_table_metadata"\n            WHERE name = %(id)s AND alias_of IS NULL' {'id': u'af18a06c-46bf-40fd-a5e8-0337c2b3b6da'}
Traceback (most recent call last):
  File "/vagrant/ckan/model/modification.py", line 88, in notify
    observer.notify(entity, operation)
  File "/vagrant/ckanext/datastore/plugin.py", line 106, in notify
    'resource_id': resource.id})
  File "/vagrant/ckan/logic/__init__.py", line 457, in wrapped
    result = _action(context, data_dict, **kw)
  File "/vagrant/ckanext/datastore/logic/action.py", line 557, in datastore_make_public
    if not _resource_exists(context, data_dict):
  File "/vagrant/ckanext/datastore/logic/action.py", line 626, in _resource_exists
    return backend.resource_exists(res_id)
  File "/vagrant/ckanext/datastore/backend/postgres.py", line 1895, in resource_exists
    results = self._get_write_engine().execute(resources_sql, id=id)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1690, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 727, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 824, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
    context)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
    context)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) relation "_table_metadata" does not exist
LINE 1: SELECT 1 FROM "_table_metadata"
                      ^
 'SELECT 1 FROM "_table_metadata"\n            WHERE name = %(id)s AND alias_of IS NULL' {'id': u'af18a06c-46bf-40fd-a5e8-0337c2b3b6da'}
ckan.model.modification: ERROR: (ProgrammingError) relation "_table_metadata" does not exist
LINE 1: SELECT 1 FROM "_table_metadata"
                      ^
 'SELECT 1 FROM "_table_metadata"\n            WHERE name = %(id)s AND alias_of IS NULL' {'id': u'af18a06c-46bf-40fd-a5e8-0337c2b3b6da'}
Traceback (most recent call last):
  File "/vagrant/ckan/model/modification.py", line 88, in notify
    observer.notify(entity, operation)
  File "/vagrant/ckanext/datastore/plugin.py", line 106, in notify
    'resource_id': resource.id})
  File "/vagrant/ckan/logic/__init__.py", line 457, in wrapped
    result = _action(context, data_dict, **kw)
  File "/vagrant/ckanext/datastore/logic/action.py", line 557, in datastore_make_public
    if not _resource_exists(context, data_dict):
  File "/vagrant/ckanext/datastore/logic/action.py", line 626, in _resource_exists
    return backend.resource_exists(res_id)
  File "/vagrant/ckanext/datastore/backend/postgres.py", line 1895, in resource_exists
    results = self._get_write_engine().execute(resources_sql, id=id)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1690, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 727, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 824, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
    context)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
    context)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) relation "_table_metadata" does not exist
LINE 1: SELECT 1 FROM "_table_metadata"
                      ^
 'SELECT 1 FROM "_table_metadata"\n            WHERE name = %(id)s AND alias_of IS NULL' {'id': u'af18a06c-46bf-40fd-a5e8-0337c2b3b6da'}
ckanext.datastore.logic.action: DEBUG: Setting datastore_active=True on resource af18a06c-46bf-40fd-a5e8-0337c2b3b6da
ckan.lib.maintain: WARNING: Function _resource_preview() in module ckan.controllers.package has been deprecated and will be removed in a later release of ckan. Resource preview is deprecated. Please use the new resource views
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 238 tests in 230.349s

FAILED (errors=31)
```

### CODE REVIEW

**Comment by amercader** [comment]
@ad-m if your pull request was based of master it would be much easier to see the actual changes (we can adapt it later to the release branches).
There are many ways to deploy CKAN so perhaps the vagrant files should be in a separate repo (linked from the docs) so they are easier to maintain. In any case we need to see the actual changes, so please resubmit with the PR based of master or this one targeting the `dev-v2.7` branch.
Thanks!

**Comment by ad-m** [comment]
@amercader , fixed base branch. It should now be much clearer to determine what I omitted when preparing the installation description. I can not determine it myself. It's either my trivial error or something is incomplete in the text description in the current documentation.

**Comment by Vanuan** [comment]
Don't you need to initialize Postgres for tests?

**Comment by Vanuan** [comment]
[Test documentation](http://docs.ckan.org/en/latest/contributing/test.html) suggests that you need to create a database with a special name:
```
sudo -u postgres createdb -O ckan_default ckan_test -E utf-8
sudo -u postgres createdb -O ckan_default datastore_test -E utf-8
```
> Changed in version 2.1: Previously PostgreSQL tests used the databases defined in your development.ini file, instead of using their own test databases.

**Comment by Vanuan** [comment]
Nevermind, didn't notice CREATE DATABASE commands.

**Comment by ad-m** [comment]
@Vanuan , i use CREATE DATABASE  commands to achieve passwordless execution.

**Comment by ad-m** [comment]
@gerbyzation , first of all it doesn't work. See #3933. 

First, I tried to get the installations as described in the text description. Failed to. To help me determine what steps I omitted, I wrote a command to the Vagrant scripts. Unfortunately, the installation was still unsuccessful. I do not know the CKAN project and I am not able to determine the source of errors on my own, since the project does not even install.

If I can install the project in Vagrant - if someone helps me determine what I missed - I will be able to verify that the text instruction is complete. Perhaps textual instructions are also worth testing, for example, by extracting & executing marked commands. Special RST tags can be used to mark mandatory installation commands in text instruction.

Then I tried to install it in Docker. After many attempts, it also failed.

In this situation, I had to let go further participation in the project.

**Comment by gerbyzation** [comment]
@ad-m I think there is a workaround available (believe it's this one https://github.com/ckan/ckan/issues/3929#issuecomment-348734086) and a patch in the making. I have backported the docker setup to the latest stable release (2.7.2) which works. But I agree that the installation process is difficult.

**Comment by amercader** [comment]
@ad-m Sorry about your frustation and lack of response on this thread

```
LINE 1: SELECT 1 FROM "_table_metadata"
```
This means that there is a missing step to set up the [DataStore permissions](http://docs.ckan.org/en/ckan-2.7.2/maintaining/datastore.html#set-permissions) (this is also broken on the master Docker files). If you disable the `datastore` plugin you should go past this error.

As for extensions on the current Docker files I haven't been able to make them work myself. I'm working on an alternative Docker Compose setup that allows to install local extension. I need to test it more in the context of the project I'm working on and hopefully I can update the current setup in master.

**Comment by amercader** [comment]
Closing this for now. Any Vagrant or other development environment setups should be added to separate repos. For the record I've been successfully using https://github.com/okfn/docker-ckan for a while.

**Pull request closed without merging**
