### PR TITLE
group_list performance issues: timeouts on homepage

### PR DESCRIPTION
**Pull request by amercader**
Problems:

1. `group_list` / `organization_list` are calling `group_show` / `orgsanization_show` for all items even when you are just requesting ids/names (the default behaviour)

2. The widgets on the homepage and their associated helpers are calling `group_list` / `organization_list` when they only need to show 1 of each.

This basically means timeouts on the homepage and pages that call `group_list` or `organization_list` on instances that have many groups / orgs (like demo.ckan.org).

demo.ckan.org was running 2.2.x and worked fine, so something along the way went wrong.

### CODE REVIEW

**Comment by amercader** [comment]
As agreed on last dev meeting I've pushed the changes combining all individual patches

@wardi Here are some numbers as promised (running on my laptop, with a DB with ~250 groups and ~450 organizations):

Request                             | Master | + #2584 | + #2580 | + limit/offset | + #2582 |
------------------------------------|--------|---------|---------|----------------|---------|
organization_list sort=="title asc" | 33s    | 5s      | 0.3s    | 0.3s           | 0.3s    |   
homepage                            | 1m28s  | 25s     | 4s      | 4s             | 0.5s    |   
/organization                       | 40s    | 13s     | 12s     | 0.9s           | 0.9s    |  

I still think that #2582 (removing old code in home controller and dropping `c.groups` and `c.group_package_stuff`) is justified for backporting, but happy to be told otherwise.

@davidread It would be great if you could test this against a DGU db

**Comment by davidread** [comment]
Here are the numbers for the real data.gov.uk database (running on my laptop, in paster, with a DB with 0 groups and 1334 organizations):

Request                             | Master | + #2584 | + #2580 | + #2582 |
------------------------------------|--------|---------|---------|----------------|---------|
organization_list sort=title  | 2m01s    | 13s      | 0.8s    | 0.8s    |   
homepage                          | 2m38s  | 38s     | 8s      | 2.9s    |   
/organization                       | 2m33s    | ?     | 2m27s     | 2m28s    |  

I don't have the limit/offset patch that would improve /organization -@amercader could you make it available to me?

Aside from /organization, these are just a bit higher than @amercader 's test numbers and it is pretty clear that CKAN needs all four patches to make sure the homepage is in range.

**Comment by wardi** [comment]
@amercader @davidread that great! Yeah, I agree these all should go in.

**Comment by amercader** [comment]
@davidread limit/offset is the third commit in this PR:

https://github.com/ckan/ckan/commit/9be68909e4225d4593b558bf37d8b8c2cca66231.diff

Glad you are generally happy with this. I'll close the other PR and this is ready for review

**Comment by amercader** [comment]
@davidread will you have time to review and merge this if happy? If not let me know and I'll find someone else. Cheers.

**Comment by davidread** [comment]
Possibly... I'm supposed to be off next week, but can maybe.

**Comment by amercader** [comment]
@davidread no worries enjoy your break, @brew will have a look

**Comment by brew** [comment]
https://github.com/ckan/ckan/blob/8ededef46167e1853b12335e1b198918963e7210/ckan/controllers/home.py#L15 `dirty_cached_group_stuff = None` can be removed, too.

**Comment by brew** [comment]
Apart from those small things, this is good to go!

**Comment by amercader** [comment]
@brew done

**Pull request merged**
