### PR TITLE
Nested columns serialized with json.dumps instead of python str representation

### PR DESCRIPTION
**Pull request by smotornyuk**
Pull request for #3477

### CODE REVIEW

**Comment by wardi** [comment]
This looks good but can we move it into the writer classes instead? It should be possible to dump these objects in a way that is most appropriate for the format being dumped.

**Comment by smotornyuk** [comment]
I've did it and added base tests for all output formats. I have also changed output of xml format, could you take a look at it(you can see in tests, how it supposed to look like)?  If you don't agree, i can change it back, but it more `xml-way`, i think

**Comment by wardi** [comment]
How about using something like https://pypi.python.org/pypi/xmljson for creating the XML from the arbitrary JSON that might be stored?

**Comment by smotornyuk** [comment]
Initially i thought about it, but this solution will give us error for keys like '1' or 'composite key'. So i used tag 'value' with key attribute in order to preserve hint about original structure and treat all keys exactly the same

**Pull request merged**
