### PR TITLE
Update sysadmin-guide.rst for Purging of Organization

### PR DESCRIPTION
**Pull request by iamarnavgarg**
A design document as to how we can perform Purge operation of organization on CKAN GUI

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by amercader** [comment]
@iamarnavgarg It looks like you have already made the changes to allow purging organizations from the UI locally. I think it would be great to have this functionality in core, would you like to submit a pull request with your changes? What you describe in the wiki page sounds great for a patch.

**Comment by iamarnavgarg** [comment]
Hi @amercader thank you for appreciating the work. Meanwhile, I would request you to please merge this PR at the moment. 
Thanks!

**Comment by amercader** [comment]
We'd rather try to avoid linking to wiki pages from the main docs as these can get outdated. And it's much better to add the feature like you did so it'd be great if you could submit it as a PR.

**Comment by iamarnavgarg** [comment]
Hi @amercader actually I had proposed a design as to how purging of organization can be done on GUI. if you think or want me to have this design and its procedure on main docs or elsewhere instead of wiki pages,please advise and let me know and I will have it there.
However, I was thinking till the main docs are not changing, request you to have this design document.
Thanks!

**Comment by kmbn** [comment]
It really would be great if you submitted the feature itself as a PR, @iamarnavgarg, instead of just link to a description of how to implement it. As @amercader wrote, it looks like you've already done the work. Are you interested in submitting it as new PR?

**Comment by smotornyuk** [comment]
Not relevant anymore. CKAN has PurgeUI for datasets, groups and organizations:
image

**Pull request closed without merging**
