### PR TITLE
Replace frontend tests with cypress

### LINKED ISSUE #5170: Replace PhantomJS with something more modern
PhantomJS is no longer maintained https://github.com/ariya/phantomjs/issues/15344 and errors in #5166 are probably related https://github.com/jquery/jquery/issues/4378#issuecomment-488163285

I'll probably do this myself once I figure out how those frontend tests work and find some reasonable supported solution.

### PR DESCRIPTION
**Pull request by Zharktas**
Fixes #5170 

### Proposed fixes:
Replaces frontend tests executed with browser mocha and phantomjs with [Cypress](https://www.cypress.io/). Cypress enables writing full E2E tests executed with actual browser, although current fronted tests only test that the JavaScript functions correctly. 

Example headless run can be found from here https://circleci.com/gh/ckan/ckan/6321#tests/containers/2.

Cypress does not have all sinon assertions in same assert namespace like assert(spy).called, these have been changed to expect(spy).to.be.called syntax.

### Features:

- [ ] includes tests covering changes
- [x] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by Zharktas** [comment]
We can use the dashboard service too which is free for open source projects, example from one our client projects can be viewed in here https://dashboard.cypress.io/projects/ssb2ut/runs/1561/specs

**Comment by amercader** [comment]
All tech team members in favour!

**Comment by wardi** [comment]
+3,026 −19,962 :tada:

**Comment by smotornyuk** [comment]
Perfect. I'm going to merge it, just one quick question. I don't see anything TypeScript related in this PR, but you've included tsconfig.json - was it done intentionally, for some future improvements, or you've just accidetaially added it?

**Comment by Zharktas** [comment]
tsconfig.json was added so that editors know about cypress types and can do autocompletion, it's copy pasted from here https://docs.cypress.io/guides/tooling/intelligent-code-completion.html#Reference-type-declarations-via-tsconfig

**Comment by smotornyuk** [comment]
Thanks, in that case i'm merging it - works perfectly on my local machine

**Pull request merged**
