### PR TITLE
Updated Docstrings for after_update/after_delete

### PR DESCRIPTION
**Pull request by EricSoroos**
Fixes / Related to #6159

### Proposed fixes:

The after_update and after_delete callbacks aren't always called
when the underlying dataset changes. This enumerates the cases where
it happens, and what to do about it.

Not having this documentation led to some headscratching on a site where we're doing some special work with permissions. 

- [ ] includes tests covering changes
- [x] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by EricSoroos** [comment]
Add case for Datapusher / ckanext-xloader

**Comment by EricSoroos** [comment]
Rebased to current master.

**Comment by EricSoroos** [comment]
@wardi This is a doc only fix that should still be valid for 2.11

**Comment by pdelboca** [comment]
Thanks @EricSoroos ! I'm merging this since the new docs seems okay!

**Pull request merged**
