### PR TITLE
Use current CKAN version in cookiecutter tests runner template

### PR DESCRIPTION
**Pull request by amercader**
Replace the hardcoded Docker tags with the actual current version number, so when the extension is generated they point to the correct version.

TODO: create major.minor tags for the ckan images

### CODE REVIEW

**Comment by amercader** [comment]
@kowh-ai I don't think we are pushing `major.minor` tags to Docker Hub (eg `2.10`, `2.10-dev`) for the `ckan/ckan-base` and `ckan/ckan-dev`. I think they are useful for cases like this one where you always want to target the latest patch release.

What do you think?

**Comment by kowh-ai** [comment]
Here is a snaphot of the DockerHub `ckan/ckan-base` repo with the tags currently used:

Screenshot 2023-11-24 at 1 19 25 pm

So you think we should also push extra tags eg: `ckan/ckan-base:2.10` when a new patch version number is released? So a new 2.10 image (built from **2.10.2**) will override the previous 2.10 image (built from **2.10.1**)

Fine by me

**Comment by amercader** [comment]
@kowh-ai precisely, just like [solr](https://hub.docker.com/_/solr), [postgres](https://hub.docker.com/_/postgres), [alpine](https://hub.docker.com/_/alpine), [python](https://hub.docker.com/_/python) etc do it

**Comment by kowh-ai** [comment]
@amercader - created a PR in the ckan-docker-base repo: https://github.com/ckan/ckan-docker-base/pull/37 to address this. Let me know what you think

**Review by kowh-ai — APPROVED** [review]

**Pull request merged**
