### PR TITLE
Add missing routes to IGroupForm

### PR DESCRIPTION
**Pull request by Psykar**
IGroupForm is missing two routes:
_about
_bulk_process

This adds them (and adds a new example plugin with some tests around IGroupForm's with organizations)

### Features:

- [x] includes tests covering changes
- [x] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

### CODE REVIEW

**Comment by Psykar** [comment]
Hrm two of my unit tests depend on #3010 

Worth combining the two PRs? I feel that #3010 will be much easier to accept in it's current state, where as this has some larger changes.

**Comment by amercader** [comment]
The bulk_process and about stuff makes perfect sense, but why do you need to extend the `GroupController` and `OrganizationController` from your plugin? You should only need to extend the `DefaultGroupForm` and `DefaultOrganizationForm` which are already available on the toolkit, and set the appropriate value on their [`group_type`](https://github.com/ckan/ckan/blob/master/ckanext/example_igroupform/plugin.py#L30) method.

This should be of course documented or at least the method should be added to `DefaultOrganizationForm`. I'm not saying that this is working now, but it's how it should be, even if we need to do changes on the controllers.

**Comment by Psykar** [comment]
Kind of?

However, I have needed them myself when adding these custom group types as top level menu items, as `_link_active` in helpers ( https://github.com/ckan/ckan/blob/master/ckan/lib/helpers.py#L483 ) checks if the controller instance and action is active, but if you have multiple group types using the same controller, then both will be active even though you're only viewing one.
One option would be to fix this, but the simpler is to just have a separate controller for each menu item / custom organization / group type (which makes sense)

If you'd prefer to not have these controllers added to the plugin toolkit though, I'll happily remove them (and update the example extension to call `.add_group_type` on the controller) - let me know and I'll update the PR.

**Comment by amercader** [comment]
To be honest, adding these controllers to the toolkit would probably open a can of worms (why not add X as well?). If the `_link_active` issue is not easy to fix, please update the example as you suggested.

**Comment by Psykar** [comment]
No worries, I'll remove them then (extension can always just import the controllers directly even if it's not best practise)
I'll get this done tomorrow sometime :)

**Comment by Psykar** [comment]
@amercader should be good to go.

**Comment by Psykar** [comment]
Missed delete - added in now.

**Pull request merged**
