### PR TITLE
Update deployment.ini_tmpl

### LINKED ISSUE #5622: deployment.ini_tmpl should have all configuration options with their default values
**CKAN version**
2.9

**Describe the bug**
Currently, there's no pattern when a configuration option and its default value is included in the template.
For consistency and ease of maintenance, it'd be better if all configuration options are explicitly set with their default values in the template.

### PR DESCRIPTION
**Pull request by Gauravp-NEC**
Fix for Issue 5622

Fixes #5622 

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by Gauravp-NEC** [comment]
@amercader , I have updated the deployment.ini_tmpl with all the default configurations and as per the sequence in document: https://docs.ckan.org/en/2.9/maintaining/configuration.html#ckan-configuration-file. Please review this PR. Thankyou

**Comment by Gauravp-NEC** [comment]
@amercader ,I have updated the deployment.ini_tmpl with all the default configurations and as per the sequence in document: https://docs.ckan.org/en/2.9/maintaining/configuration.html#ckan-configuration-file. Please review this PR.

**Comment by Gauravp-NEC** [comment]
@amercader ,I have updated the deployment.ini_tmpl with all the default configurations and as per the sequence in document: https://docs.ckan.org/en/2.9/maintaining/configuration.html#ckan-configuration-file. Please review this PR.

**Comment by amercader** [comment]
Thanks @Gauravp-NEC, see https://github.com/ckan/ckan/issues/5622#issuecomment-781385797

**Pull request closed without merging**
