### PR TITLE
Include icon for image data

### PR DESCRIPTION
**Pull request by k-nut**
Fixes #2948, #2910 

### Proposed fixes:
In order to clean up Pull Requests a little I just took the changes from #2948 and applied the to the lastest master. Of course this still does not include the original vector files as I do no have them.

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [x] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

### CODE REVIEW

**Comment by k-nut** [comment]
In #2910 @amercader pointed out that the original files seem to be in this repository: https://github.com/mintcanary/file-types 
That repository does not include the new image-type icon though. Maybe @hknochi can tell us where he got it from or provide the original?

**Comment by k-nut** [comment]
@amercader I think we should merge this rather soon instead of waiting for the original vector files. Waiting for them led to the last PR becoming conflicting with the current master. I could create a separate issue for also including the vector files?

**Comment by hknochi** [comment]
@k-nut : i think to add the vector files in the repo won't be the best idea (may these should be in a other/single one)

**Comment by k-nut** [comment]
Yes. We might want to store them in a separate repo. But at least having something like a link to the original somewhere in the ckan project could prove useful already.

**Comment by hknochi** [comment]
okay i'll add the source . you can move them to a custom path afterwards

**Comment by hknochi** [comment]
please take a look here: https://drive.eccenca.com/d/73541a96f2/

**Comment by k-nut** [comment]
@hknochi cool, thank you! How are the icons licensed?

**Comment by k-nut** [comment]
@amercader do you think we should create a new repository for design assets like this? Or is there something already where we could put this? Or would you just include it in this repository?

**Comment by seebi** [comment]
Fromm eccenca's POV this should not be decided by us but by @smth who originally pushed these files (https://github.com/mintcanary/file-types/commit/1740cd625afc8f0d0f0c9506d41a1caaa3000cae). The work of @hknochi can be licensed under any terms suitable for you.

**Comment by smth** [comment]
I just added a license [here](https://github.com/mintcanary/file-types/blob/master/LICENSE.txt).

**Comment by k-nut** [comment]
Created a first [pull request](https://github.com/ckan/ckan-assets/pull/1) in the new `ckan-assets` repository. Once that is merged this PR should also be good to merge.

**Pull request merged**
