### PR TITLE
package_update performance purge resources approach

### LINKED ISSUE #7119: package_update performance of repeated calls
**CKAN version**
all

**Describe the bug**
Repeated calls to `package_update` with a set of resources w/o consistent resource ids get slower over time

**Steps to reproduce**
For this test I used a dataset with 10 resources repeatedly submitted to `package_update`:
```json
{
  "name": "10res",
  "resources": [
    {"url": "1"}, {"url": "2"}, {"url": "3"}, {"url": "4"}, {"url": "5"},
    {"url": "6"}, {"url": "7"}, {"url": "8"}, {"url": "9"}, {"url": "10"}
  ]
}
```
package_update

- orig: time to complete on original ckan source
- filter: time to complete with filter applied (see below)
- purge: time to complete with resources purged (see below)

**Expected behavior**
ckan shouldn't get slower over time as resources are updated.

**Additional details**
filter patch:
This targets only the source of the slowness (iterating over all the deleted resources in python and resubmitting them with `state='deleted'` to postgres) and maintains the ever-growing list of deleted resources in the db
```patch
diff --git a/ckan/lib/dictization/model_save.py b/ckan/lib/dictization/model_save.py
index f4eff4427..c9cba0cc2 100644
--- a/ckan/lib/dictization/model_save.py
+++ b/ckan/lib/dictization/model_save.py
@@ -66,8 +66,12 @@ def package_resource_list_save(
     if res_dicts is None and allow_partial_update:
         return
 
+    session = context['session']
+    model = context['model']
     resource_list = package.resources_all
-    old_list = package.resources_all[:]
+    old_list = session.query(model.Resource) \
+        .filter(model.Resource.package_id == package.id) \
+        .filter(model.Resource.state != 'deleted')[:]
 
     obj_list = []
     for res_dict in res_dicts or []:
```

purge patch:
This solves the issue by purging resources that are removed in a package_update. This seems like a better solution because I can't think of any value in keeping these deleted resources in the db
```patch
diff --git a/ckan/lib/dictization/model_save.py b/ckan/lib/dictization/model_save.py
index f4eff4427..080e13ecc 100644
--- a/ckan/lib/dictization/model_save.py
+++ b/ckan/lib/dictization/model_save.py
@@ -89,8 +89,7 @@ def package_resource_list_save(
 
     # Mark any left-over resources as deleted
     for resource in set(old_list) - set(obj_list):
-        resource.state = 'deleted'
-        resource_list.append(resource)
+        resource.purge()
 
 
 def package_extras_save(
```

### PR DESCRIPTION
**Pull request by wardi**
Fixes #7119 

### Proposed fixes:

This solves the issue by purging resources that are removed in a package_update. This seems like a better solution because I can't think of any value in keeping these deleted resources in the db

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

### CODE REVIEW

**Comment by smotornyuk** [comment]
@wardi, have you forgotten about this PR? It only needs these 3 errors fixed before merge

**Comment by wardi** [comment]
haven't forgotten, still need to find a good fix for these issues

**Comment by wardi** [comment]
@smotornyuk I combined the two different approaches so now resources are still "soft deleted" then the next time they aren't sent in a package_update they are actually removed. This should maintain compatibility with things that expect them to be saved with state=deleted like the datastore code and still prevents the performance from getting worse over time.

**Comment by wardi** [comment]
@amercader how does this look for an explanation of the resource saving changes [27a64e1](https://github.com/ckan/ckan/pull/7122/commits/27a64e1537af9d29e16d47081bbc616f27c550d3) ?

**Pull request merged**
