### PR TITLE
2478 licenses more specific

### PR DESCRIPTION
**Pull request by davidread**
Issue: #2478 

Default licenses are now more specific. Plus config options for a necessary 'license deprecation' mechanism.
- The default licences is now three well-known open CC licences with version numbers.
- License options offered is now a subset of all of them, to allow deprecation of licenses. Config options added, plus logic in helper.
- Default licenses now in a JSON file for simple customization by copying it. Added extractor to ensure titles are translated.
- Simplified configuring a file with licences in - no more weird file:/// to work out.
- Form CSS marginally improved with a bigger select box for the long license names. Adjusted some other sizings in sympathy.

### CODE REVIEW

**Comment by davidread** [comment]
c.f. https://github.com/ckan/ckan/pull/2452

**Comment by Aaron-M** [comment]
Just checking where things have progressed to with this?

I've looked through various related issues (#2472, #2487, #2478, #2487, #2479) which stemmed from 
https://github.com/ckan/ideas-and-roadmap/issues/153  

How do I implement this so as to get the functionality described above - "License options offered is now a subset of all of them, to allow deprecation of licenses. Config options added, plus logic in helper."

We are again reviewing the versions of some licenses we offer/recommend, and have struck the same issue of a licence changing if a dataset is edited and the licence it was created with is no longer in the pick list, it gets changed to the first on the picklist. (using CKAN v2.7.2)

Happy to help test stuff (I'm not a programmer so sadly can't help in that respect).

**Comment by davidread** [comment]
@Aaron-M yes some work to merge and update these attempts is long overdue. Too many sites simply hack the code in this area on their own fork, which is far from ideal for everyone. It's not an issue for my current clients, which is why I've not done it. So I'm hereby encouraging whichever site next needs work done on licenses, to use the their developer resources to bring this work together and benefit everyone in this area.

**Comment by kmbn** [comment]
We decided to close old pull requests that are not actively worked on so that we can focus our effort and attention on PRs made against the current version of CKAN. A lot has changed in the last several months and many PRs will have gone stale or may now be in conflict with the latest version.

Please note: this isn't a judgement about the quality of your pull request. We just don't have the resources to review older PRs.

If you would like to reopen your PR (and update it if necessary), please do!

**Pull request closed without merging**
