### PR TITLE
Try to fix travis

### PR DESCRIPTION
**Pull request by ggcatu**
### Proposed fixes:

> apt-get install -y build-essential libssl-dev libffi-dev

### CODE REVIEW

**Comment by ggcatu** [comment]
Probably not all 3 libraries are needed. 

Maybe trial and error would give the right one.

**Comment by amercader** [comment]
Thanks @ggcatu!

**Comment by deinok** [comment]
@ggcatu The travis CI only setup a docker instance and tes if it is serving CKAN.

So it seems more a problem with undefined or unmantained libs or a commit that breaks the compatibility with the docker images.

So, this fix only shows a more heavy issue.
Also, nice catch ;)

**Comment by ggcatu** [comment]
@deinok Yep, of course, problem was while trying to build the image, that cryptography was complaining during compilation, because missing dependencies

**Pull request merged**
