### PR TITLE
Updated documentation and tests for Ubuntu 14.04 support

### PR DESCRIPTION
**Pull request by amercader**
This PR overrides any previous ones labelled Ubuntu 14.04 (specially #2020).

This essentially reviews and updates the package install, source install,
source deployment and upgrade docs so they work on both Ubuntu 12.04 and 14.04.

It assumes packages for trusty are available
(see https://github.com/ckan/ckan-packaging/pull/6)

There are a couple of minor fixes on the dev requirements as well that fix
error failures on Ubuntu 14.04

### CODE REVIEW

**Comment by rossjones** [comment]
Once package install is tested, this looks good to go.

**Comment by amercader** [comment]
@rossjones Packages now available on http://packaging.ckan.org/

**Comment by rossjones** [comment]
python-ckan_2.4-trusty_amd64.deb works fine. Will try precise package now, but what is python-ckan_2.4_amd64.deb ?

**Comment by rossjones** [comment]
Happy that this fixes any problems, tests on 14.04, and packages work well.

**Comment by amercader** [comment]
:tada: :sparkles: woo

I have pinged the dev list to ask for help testing as well

**Pull request merged**
