### PR TITLE
4807 remove all remaining pylons code in core

### LINKED ISSUE #4807: Remove all remaining Pylons code in core
This should be done in separate pull requests to make reviews easier

- [x] Remove `requirements.py2.*` files and update documentation to remove py2 mentions
- [x] Remove py2 specific code. Look for `if six.PY2:` and remove what's inside!
- [x] Remove py3 checks. Look for `six.PY3` and make that the standard code run (remove the check if any)
- [ ] Remove usage of six. We should not need the compatibility layer any more. Make all code standard Python 3

This should definitely be done separately

- [ ] Remove unicode literals (eg `my_conf[u"test_key_1"] = u"Test value 1"` -> `my_conf["test_key_1"] = "Test value 1"`

### PR DESCRIPTION
**Pull request by steveoni**
Fixes #4807 

### Proposed fixes:
Remove py2 specific code

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by amercader** [comment]
@steveoni Thanks a lot for your help with this. To keep the git history tidy would you mind combining all similar changes into a single commit with a descriptive title, eg "Remove no longer run py2 specific code"
Also it's better to include unrelated formatting changes like [this one](https://github.com/ckan/ckan/pull/6090/files#diff-99e591024dd20cd60b6dc8fdcc609171fd03af439787f702ea5c62ec66ce6178) separate (different commit or an entirely different PR)

**Comment by steveoni** [comment]
@amercader ok. I will create another pull request containing the changes as requested. For the formatting, whenever I make changes and save, the code is automatically formatted. I will look for a way to stop that.

**Comment by amercader** [comment]
@steveoni thanks, if you can configure as precommit hook that only formats the code that you are changing that would work too

**Comment by steveoni** [comment]
@amercader I've created a new pull request for this here: #6101

**Pull request closed without merging**
