### PR TITLE
Clean isolated Session.close() code.

### PR DESCRIPTION
**Pull request by pdelboca**
All code that opens a connection is responsible for closing it. Having isolated `just-in-case` sessions close is not recommended since it can hide errors in the logic.

This PR also cleans an isolated `model.Session.commit()` that we don't even control what's going to commit.

### CODE REVIEW

**Comment by smotornyuk** [comment]
[Removing the code that refers an issue](https://github.com/ckan/ckan/pull/6710/files#diff-fa05bfb271e2e93a67efbbf10f3a8dc019edd3d6d509a1fc78225225a8a705f6L71-L75), without checking for regressions, is also not recommended:)

**Comment by pdelboca** [comment]
I have been testing it before submitting the PR and I couldn't replicate the original issue. I would gladly suggest a proper fix but it seems that the behavior no longer exist in the system.

Do you have a reproducible example of what's currently causing it? :thinking: 

The only thing I can think of is plugins leaving open connections when loading, but in that case I think it would be safer to `close()` the Session rather than committing. (what are we committing to the database in that line?)

**Comment by smotornyuk** [comment]
I see.. the way of reproducing the issue is not clear from the original issue

So, here is the state of all active connections to the PostgreSQL server, when CKAN starts on the master branch: 
image

And here is the same stats with your PR applied:

image


---

I like your suggestion to `close` the session. 

---
> what are we committing to the database in that line?

The incomplete transaction, that you see on the latter screenshot. Don't ask me, why this query runs in transaction, I don't remember it

**Comment by pdelboca** [comment]
Closing this one since I'm gonna be working on each case individually.

**Pull request closed without merging**
