### PR TITLE
CircleCI v1 to v2

### PR DESCRIPTION
**Pull request by cclauss**
Follows the confusing process documented at https://circleci.com/sunset1-0/#migration-steps

### CODE REVIEW

**Comment by cclauss** [comment]
Good news...  This fails in just the same way as  #4334

**Comment by amercader** [comment]
@cclauss Great to see you started work on this. What's the status of it? Can we help in any way?

**Comment by cclauss** [comment]
@amercader Thanks.   #4335 is the blocker.  If someone can help explain that then I think we will have a Circle CI v2 that is equal to our current Circle CI v1.

**Comment by cclauss** [comment]
Closed in favor of #4345

**Pull request closed without merging**
