### PR TITLE
Split tests across circle CI containers

### PR DESCRIPTION
**Pull request by wardi**

### CODE REVIEW

**Comment by wardi** [comment]
@amercader so, yeah, --segments is revealing some broken tests, and caching the nvm directory is making the restore hugely slower and *still* not helping to prevent the re-download.

What do you think about me switching back to the version before using --segments and adding a hack that will skip the npm install command when there is a cached version found (like http://stackoverflow.com/questions/31766930/circleci-not-caching-my-globally-installed-node-module )

**Comment by wardi** [comment]
#2937 has the phantomjs fix. I'll rebase this PR on to that code

**Comment by amercader** [comment]
The 3 segments failures look easy to fix (just duplicated package names because of tests not cleaning up) and I really like the idea of not having to explicitly define the tests to run and forget about it. The nvm caching hack (which sounds great) is unrelated to using segments or not right?

**Comment by wardi** [comment]
So how do I figure out which tests aren't cleaning up after themselves?

Yes #2937 is the npm caching hack, unrelated to this PR

**Comment by amercader** [comment]
Can we change the dataset name on the 3 failing tests?

**Comment by wardi** [comment]
Aha! here's what I need: https://circle-artifacts.com/gh/ckan/ckan/1171/artifacts/2/tmp/circle-junit.eVfC8te/nose/junit.xml

**Comment by wardi** [comment]
@amercader I think I got it

**Comment by amercader** [comment]
6 minutes! wooo :bullettrain_side: :dash: :dash:

**Comment by amercader** [comment]
Hats off to @kindly for the original segments implementation!

**Comment by wardi** [comment]
@kindly :tophat: :womans_hat:

We could do a little better if we run the JS tests on just one of the containers (number 0 seems to be a good target). I'll have to think about the best way to do that since we need circle's `background` setting

**Comment by wardi** [comment]
@TkTech 's work on #2916 was also huge in getting us down to this number. These tests were running around 10 minutes before I rebased.

**Pull request merged**
