### PR TITLE
DataStore Map preview does not show plot markers

### LINKED ISSUE #3540: DataStore Map preview does not show plot markers from latitude / longitude fields
### CKAN Version if known (or site URL)
2.6.2

### Please describe the expected behaviour
The [DataStore Map](http://docs.ckan.org/en/ckan-2.6.2/maintaining/data-viewer.html#datastore-map) preview function should show plot markers from pairs of latitude / longitude fields.

### Please describe the actual behaviour
The map doesn't show anything. It seems that we don't get those markers.

### What steps can be taken to reproduce the issue? 
1. Upload a CSV file with pairs of latitude / longitude fields.
2. Create a DataStore Map view and specify latitude / longitude fields.
3. See the created map.

### PR DESCRIPTION
**Pull request by Cheomm88**
Fixes #3540 

### Proposed fixes:
Fixes the issues that happens when latitude / longitude fields have a different name.

### Features:

- [X ] includes tests covering changes
- [ ] includes updated documentation
- [x ] includes user-visible changes
- [ ] includes API changes
- [ X] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by amercader** [comment]
Thanks @Cheomm88! can you revert changes in the .min.js file (`git revert 2478b55 `) ? We rebuild these files before a release so no need to update them manually

**Comment by Cheomm88** [comment]
@amercader I think I have done it.

**Comment by amercader** [comment]
@Cheomm88 almost! You pushed the revert changes to your fork's `master` branch, but this pull request uses the `Cheomm88-patch-recline_map` branch in your fork:

screenshot-2018-4-11 datastore map preview does not show plot markers from latitude longitude fields issue 3540 ckan c

You need to do the `git revert` and push to that branch so the commit is included in this pull request. To change to that branch use `git checkout Cheomm88-patch-recline_map`

**Comment by Cheomm88** [comment]
@amercader seems i got it =)

thanks!

**Comment by amercader** [comment]
Great @Cheomm88!

Congratulations on your first pull request 🚀

**Pull request merged**
