### PR TITLE
FIX for the issue 6542

### LINKED ISSUE #6542: layer1.html pushes the Search data form to the roof
When a featured block is too short, the search data form goes under the header.

CKAN CSS glitch
8

This is caused by `col2` class:
https://github.com/ckan/ckan/blob/10aa7c6f92f1dede5f02302e2b6ea4d96aaf4604/ckan/public/base/css/main.css#L10279-L1028

### PR DESCRIPTION
**Pull request by Sunny-NEC**
Fixes #6542 

### Proposed fixes:
Fix the main css and update it. for the issue 6542

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by amercader** [comment]
@Sunny-NEC please provide a descriptive title for the pull request so it's easier to find and add to the changelog.

If you changed the main.css file presumably you changed a sass file as well, this should be committed as part of this PR as well

**Comment by Sunny-NEC** [comment]
@amercader Thankyou for the review. next time I will provide descriptive title. and  their is no changes in a saas file for this issue.
I test it on my local system it working fine.

**Comment by amercader** [comment]
@Sunny-NEC All the changes in the main.css come from compiling the [scss files ](https://github.com/ckan/ckan/tree/master/ckan/public/base/scss). We should never edit the css files directly. Check wich scss files contains the directives you need and edit it, and the run `ckan sass` to compile the `main.css` file(s).

**Comment by Sunny-NEC** [comment]
@amercader I checked main.scss file and This file has only two import statements.   
could you please guide me how i can change the scss file according to the changes which i did in a main.css.

**Comment by Gauravp-NEC** [comment]
> @Sunny-NEC All the changes in the main.css come from compiling the [scss files ](https://github.com/ckan/ckan/tree/master/ckan/public/base/scss). We should never edit the css files directly. Check wich scss files contains the directives you need and edit it, and the run `ckan sass` to compile the `main.css` file(s).

@amercader , **Sunny-NEC** is no longer working on this PR. I will do the rework. Can you guide me how I can change the scss file according to the changes done in main.css (commit https://github.com/ckan/ckan/pull/6553/commits/fbbef00514656d2942e67d6c02d3be08726f6b42)

**Comment by Gauravp-NEC** [comment]
@frafra ,Can you guide me how I can change the scss file according to the changes done in main.css (commit https://github.com/ckan/ckan/pull/6553/commits/fbbef00514656d2942e67d6c02d3be08726f6b42)?

**Comment by frafra** [comment]
@Gauravp-NEC just follow what amercader said. The main scss files import other sccs files and so on. You should find what file you need to modify. It is not easy to understand what you want to modify based on the commit you have made, since there are thousands of lines modified with no effect (whitespaces changes and such).

Can you describe which part of the css file are you trying to modify? Then I can help you in finding which scss file produces such fragment (you can also search across the files).

**Comment by Gauravp-NEC** [comment]
> Can you describe which part of the css file are you trying to modify? Then I can help you in finding which scss file produces such fragment (you can also search across the files).

@frafra , Thankyou for your response. I want to modify main.css file (https://github.com/ckan/ckan/blob/master/ckan/public/base/css/main.css). Can you tell me which scss file produces main.css file?

**Comment by frafra** [comment]
@Gauravp-NEC I cannot, as I need to know which sections of such file you want to modify. As stated in my previous message, your commit makes a lot of changes, thousands of them (I guess your IDE/editor reformatted the whole file), so it is not easy to figure out what you are trying to do.

**Comment by robin-NEC** [comment]
Hi @amercader  https://github.com/ckan/ckan/pull/6860 will fix this issue

**Pull request closed without merging**
