### PR TITLE
disable all caching on _logout URL, #6955

### PR DESCRIPTION
**Pull request by ThrawnCA**
By default, authenticated pages are stored in browser cache, which is secure enough - but we don't want _logout cached at all, because despite being a GET request, it has a crucial side effect (deleting the session cookie).

### Proposed fixes:

Disable all caching on `/user/_logout`

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [X] includes user-visible changes
- [ ] includes API changes
- [X] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by pdelboca** [comment]
Hello @ThrawnCA ! Thanks for reporting this!

I have been reviewing this one and debating it in the tech team meeting. The root cause of this is that the call is still a `GET` when it should be a `POST` request.

Are you interested on changing this PR for an implementation that changes the call to logout to a POST? I'm thinking something like this:
```jinja
<form action="{{ h.url_for('user.logout') }}" method="post">
   <input class="btn btn-link" type="submit" value="Log out">
   {{ h.csrf_input() }}
</form>
```

And then the change in the route registration to accept POST.

**Comment by ThrawnCA** [comment]
> Are you interested on changing this PR for an implementation that changes the call to logout to a POST? I'm thinking something like this:

Done. We have deployed this on our DEV environment, dev.data.qld.gov.au, and it appears to be working correctly. The icon is slightly larger than before, and the button doesn't display a URL on hover; otherwise the user experience is essentially unchanged.

**Comment by pdelboca** [comment]
Thanks @ThrawnCA !

**Comment by ThrawnCA** [comment]
@pdelboca It looks like converting logout to a POST request has had an unfortunate side effect: Since pages are cached too aggressively (see #6955), it is possible for the logout button in the header to have a stale CSRF token.

The whole issue of caching in CKAN 2.10, and how it interacts with logging in and out, needs to be revisited.

**Pull request merged**
