### PR TITLE
Add alpine ckan

### PR DESCRIPTION
**Pull request by caduvieira**
### Proposed fixes:
Add a alpine image to docker ckan.
355M of size

How to test
docker-compose -f docker-compose-alpine.yml build
docker-compose -f docker-compose-alpine.yml up -d

### Features:

- [ ] includes updated documentation
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by caduvieira** [comment]
```console
$ docker-compose -f docker-compose-alpine.yml up ckan
ckan          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
ckan          |     cursor.execute(statement, parameters)
ckan          | sqlalchemy.exc.ProgrammingError: (ProgrammingError) column user.password does not exist
ckan          | LINE 1: SELECT "user".password AS user_password, "user".id AS user_i...
ckan          |                ^
ckan          |  'SELECT "user".password AS user_password, "user".id AS user_id, "user".name AS user_name, "user".openid AS user_openid, "user".fullname AS user_fullname, "user".email AS user_email, "user".apikey AS user_apikey, "user".created AS user_created, "user".reset_key AS user_reset_key, "user".about AS user_about, "user".activity_streams_email_notifications AS user_activity_streams_email_notifications, "user".sysadmin AS user_sysadmin, "user".state AS user_state \nFROM "user" \nWHERE "user".name = %(name_1)s OR "user".id = %(id_1)s ORDER BY "user".name \n LIMIT %(param_1)s' {'name_1': 'default', 'param_1': 1, 'id_1': 'default'}

``
Can anyone help with this error?

**Comment by TkTech** [comment]
Sounds like `paster db init` isn't being run so you have no user table.

**Comment by caduvieira** [comment]
To run CKAN:
```console
cd contrib/docker/
cp .env.template .env
docker-compose -f docker-compose-alpine.yml up ckan
```

**Comment by caduvieira** [comment]
localhost:5000/dataset is exiting with

```console
ckan          | 2017-11-04 14:45:15,755 INFO  [ckan.lib.base]  / render time 4.349 seconds
ckan          | 2017-11-04 14:45:17,019 INFO  [ckan.lib.base]  /api/i18n/en render time 0.017 seconds
ckan exited with code 139
```

**Comment by caduvieira** [comment]
paster --plugin=ckan create-test-data -c /etc/ckan/ckan.ini
exits with:

```console
ckan          | DETAIL:  Key (name)=(david) already exists.
ckan          |  'INSERT INTO "group" (id, name, title, type, description, image_url, created, is_organization, approval_status, state, revision_id) VALUES (%(id)s, %(name)s, %(title)s, %(type)s, %(description)s, %(image_url)s, %(created)s, %(is_organization)s, %(approval_status)s, %(state)s, %(revision_id)s)' {'description': u'These are books that David likes.', 'created': datetime.datetime(2017, 11, 4, 16, 16, 52, 119159), 'title': u"Dave's books", 'approval_status': u'approved', 'is_organization': False, 'state': u'active', 'image_url': u'', 'revision_id': u'3d8eeeef-7f19-4e2c-a10d-e0e78b856c2d', 'type': 'group', 'id': u'57af8ad3-ccbf-401d-b2d8-3a2e9c1991af', 'name': u'david'}
ckan exited with code 1
```

**Comment by caduvieira** [comment]
I really don't know how to debug this error

Found this but I will have to dig further
https://stackoverflow.com/questions/31074240/process-finished-with-exit-code-139-after-updating-from-python-2-7-6-64-bit-to-2

If anyone has a similar problem, please let me know

**Comment by JGulic** [comment]
@caduvieira I think we shouldn't use the alpine:edge image, instead we can use the alpine:3.6. Since we are thinking of making the docker-compose by default to work with alpine, it will be best not to use the edge image.
I know that some packages are missing in the alpine 3.6 image but we can pull them from the testing repository.
For example:
`# build geos-dev
RUN apk add --no-cache --virtual .build-deps-testing \
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
        geos-dev`

Another thing is that for now we don't have support for Postgres10, and if you try to run:

`docker-compose -f docker-compose-alpine.yml up db` 

there is the following error:

`db            | 2017-11-14 13:29:54.241 UTC [1] FATAL:  database files are incompatible with server
db            | 2017-11-14 13:29:54.241 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 9.6, which is not compatible with this version 10.0.
db exited with code 1
`

For the database, probably it's better to use a specific version of postgis, and make changes [here](https://github.com/ckan/ckan/blob/master/contrib/docker/postgresql/Dockerfile#L2).

Can you make the changes for the alpine image and the other changes that are needed?
If you need any help with it, let me know.

**Comment by caduvieira** [comment]
@JGulic done the changes requested. But after the first request the ckan exits silently.

**Comment by Vanuan** [comment]
I've tried using alpine too. Same result: segmentation fault. It looks like CKAN has some pre-built binary dependencies that are linked to GNU C.

I'm not experienced with pip, but I think there should be some option to force rebuild binary packages.

**Comment by Vanuan** [comment]
Questions that needs research:
1. Which package is crashing. All packages
2. Whether it's using wheel or egg format
https://packaging.python.org/discussions/wheel-vs-egg/
3. How to instruct Pip to force rebuild.

**Comment by Vanuan** [comment]
I've investigated briefly and it looks like all packages need to be rebuilt individually and `requirements.txt` needs to be modified to point to those musl-specific packages.

**Comment by caduvieira** [comment]
I will try to make that. Thanks a lot!

**Comment by Vanuan** [comment]
Hey, did no-binary work?
Do we also need no-use+wheel?
https://github.com/pypa/pip/issues/3191

**Comment by amercader** [comment]
@caduvieira did your "non-binary" changes fix the issue?

**Comment by caduvieira** [comment]
Nope...

**Comment by amercader** [comment]
I have a working Alpine-based setup in here: https://github.com/okfn/docker-ckan Perhaps you can find the missing piece comparing the scripts

**Comment by kmbn** [comment]
We decided to close old pull requests that are not actively worked on so that we can focus our effort and attention on PRs made against the current version of CKAN. A lot has changed in the last several months and many PRs will have gone stale or may now be in conflict with the latest version.

Please note: this isn't a judgement about the quality of your pull request. We just don't have the resources to review older PRs.

If you would like to reopen your PR (and update it if necessary), please do!

**Pull request closed without merging**
