### PR TITLE
[WIP] Data package output for CKAN

### PR DESCRIPTION
**Pull request by metaodi**
Fixes https://github.com/ckan/ideas-and-roadmap/issues/15 and https://github.com/ckan/ideas-and-roadmap/issues/37
### Proposed fixes:

Add datapackage.json output for each dataset, so that CKAN can be used as a source of data packages.
### Features:
- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [X] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by amercader** [comment]
@metaodi Have you seen https://github.com/ckan/ckanext-datapackager? It already provides import/export functionality for Data Packages pretty comprehensibly, and there's much room for improvement eg integrating JSON Table Schema and DataStore.
If there is interest we can definitely explore the option of merging it into core.

**Comment by metaodi** [comment]
@amercader yes I've seen it. I guess only a fraction of the datapackager _should_ be part of CKAN core. I thought I start with something easy like the "export", but I'm open to comments or different approaches.

**Comment by amercader** [comment]
Well, the main thing I want to avoid is having two code bases converting CKAN metadata to `datapackage.json` and more generally handling DP/CKAN integration. I personally thing that most if not all of ckanext-datapackager could be part of core (and that was what seemed to be the main view on the original [spec](https://github.com/ckan/ideas-and-roadmap/pull/160#discussion_r43399234)). It will probably make things easier when we approach the work to integrate with the DataStore.

There might be changes needed on ckanext-datapackager to make it easier to merge into core (for instance the UI needs more work to integrate more consistently) and that's totally fine, but I think it make sense to use that code base which is supported by Open Knowledge as part of the wider Frictionless Data project.

**Comment by amercader** [comment]
@metaodi this was discussed on the dev meeting and consensus was that it makes sense to use the existing code on ckanext-datapackager. Would you like to see that merged into core? Do you have any particular issues with the way the extension works or how it integrates with CKAN?

**Comment by kmbn** [comment]
We decided to close old pull requests that are not actively worked on so that we can focus our effort and attention on PRs made against the current version of CKAN. A lot has changed in the last several months and many PRs will have gone stale or may now be in conflict with the latest version.

Please note: this isn't a judgement about the quality of your pull request. We just don't have the resources to review older PRs.

If you would like to reopen your PR (and update it if necessary), please do!

**Pull request closed without merging**
