### PR TITLE
bugfix: persisiting auth attributes

### LINKED ISSUE #5751: Chained auth functions lose anonymous access
**CKAN version**
All
**Describe the bug**
If an auth function is marked as chained, it is transformed into a functools partial. In doing so, no function attributes are persisted to the new function - leaving `auth_allow_anonymous_access` flags out. This means that there is no way for developers to specify that an auth function is both chained and allowed to be accessed anonymously.

**Steps to reproduce**
Create a plugin implementing `IAuthFunctions`, and use both the `@toolkit.auth_allow_anonymous_access` and `@toolkit.chained_auth_function` decorators. The function will be chained, but will return `403` before ever running your function.

**Expected behavior**
The function doesn't automatically get 403'd.

**Additional details**
The error is in the `_build` function for the `AuthFunctions` class in `ckan/ckan/authz.py`. Specifically the `auth_allow_anonymous_access` attributes are managed [here](https://github.com/ckan/ckan/blob/612e0f9ab01b61516399e39a803d8cb66cd3c9cf/ckan/authz.py#L79), but then the chained auth functions are transformed into partials [here](https://github.com/ckan/ckan/blob/612e0f9ab01b61516399e39a803d8cb66cd3c9cf/ckan/authz.py#L118). I don't have my dev environment set up for contributing back at the moment (it's in a private fork) but have this fixed in my local 2.8 version and will get this into master this weekend.

### PR DESCRIPTION
**Pull request by hardingalexh**
Fixes #
Fixes #5751 and (partially) #4597. 

### Proposed fixes:
Because chained authentication functions are wrapped into partials, they lose access to any attributes that may have been set on the functions themselves (like allowing anonymous access). This fix defines a list of attributes, checks them against the original function, then applies them to the new partial function.

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [X] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by smotornyuk** [comment]
This is error prone in the long term because we need to maintain this list as source code changes. And attributes from custom decorators, that can be introduced by 3rd-party code are still ignored. 
What do you think about using `func.__dict__` instead of a predefined list

**Comment by Zharktas** [comment]
This also need to be done on chained actions and then there are two places to maintain decorator lists which is somewhat undesirable.

**Comment by smotornyuk** [comment]
Probably it should be done in separate PR, but just FYI: we also have [chained_helper](https://github.com/ckan/ckan/blob/master/ckan/lib/helpers.py#L147) with a similar block of code [here](https://github.com/ckan/ckan/blob/master/ckan/lib/helpers.py#L2921-L2923)

**Comment by hardingalexh** [comment]
@smotornyuk I've rewritten it to use `func.__dict__` rather than a manual list, that's a good call. Should I also add this pattern to actions/helpers in this PR, or should I make separate PRs for each of them? It's pretty simple to add this snippet to both.

**Comment by smotornyuk** [comment]
Probably, it will be faster if you do it as a part of this PR, as long as you don't mind for some reasons:)

And another notice. You've used `dict.iteritems` which is not available in Python3. We use `six` library for handling such cases, so could you rewrite `dict.iteritems` to `six.iteritems(dict)`?

**Comment by hardingalexh** [comment]
Rewrote to be more python-version-agnostic. A little more verbose, but native. Apologies for that, my CKAN dev environment is stuck in 2.8/python 2.7 land for a little while longer. If you're happy with this syntax, I'll add it to actions/helpers and we can get this going!

**Comment by hardingalexh** [comment]
I've added this functionality to the other uses of `functools.partial`. This should be ready to merge unless anyone objects to syntax/has other concerns. @smotornyuk @Zharktas

**Comment by Zharktas** [comment]
I would have just used six.iteritems(dict) which does dict.iteritems on python2 and iter(dict.items) on python3. It would make it easier to understand what is going on at a glance. Tests would be nice as clearly chaining actions, auths or helpers aren't tested.

**Comment by hardingalexh** [comment]
Rewritten to use six. How would I go about adding tests for this? I'm not really sure the best way to intercept a chained function to check if it has the right attributes.

**Comment by Zharktas** [comment]
For chained auth_functions you could import [_AuthFunctions](https://github.com/ckan/ckan/blob/master/ckan/authz.py#L123) from ckan.auths and call get('some_chained_action') and test the attributes. For actions you could just call get_action and for helpers I think by importing helper_functions from ckan.lib.helpers. 

Might require crafting custom plugin which creates chained functions in the first place though.

**Comment by Zharktas** [comment]
Superseded by #5873 which adds tests.

**Pull request closed without merging**
