### PR TITLE
[#2350] Fix validation of user schema.

### PR DESCRIPTION
**Pull request by davidread**
See issue: https://github.com/ckan/ckan/issues/2350

I've not written any tests for this as it is a reasonably big job to setup a test extension, inherit UserController and setup routes. I don't think we're very happy with how the user schema is customized - it would make sense to convert to an IUserForm, so investing in this old way seems pointless. So I suggest we just fix this as @KrzysztofMadejski suggests and not worry about a test until this area is looked at properly by someone.

BTW @KrzysztofMadejski inherits UserController and adds an extra validator and a couple of new fields:
https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/blob/develop/ckanext/danepubliczne/controllers/user.py#L79

### CODE REVIEW

**Comment by KrzysztofMadejski** [comment]
+1 for *IUserForm* :)

**Comment by davidread** [comment]
I'll just add a basic functional test for editing a user.

**Comment by davidread** [comment]
I've added the test, so ready for review.

**Comment by davidread** [comment]
This is a one-line fix with a test, ready for review, ping @amercader ;-)

**Pull request merged**
