### PR TITLE
[#2345] datastore: only create _table_metadata view if it does not exist yet

### LINKED ISSUE #2345: Datastore _table_metadata view recreated on every startup
We fixed the read/write test having conflicting table names by randomizing them (https://github.com/ckan/ckan/pull/1397, https://github.com/ckan/ckan/issues/2082) but there's still another database call that can cause problems on busy sites: creating the _table_metadata view.
https://github.com/ckan/ckan/blob/b1c12f74b09c4703407563861e089e37ec0e19e2/ckanext/datastore/plugin.py#L80

My understanding of PostgreSQL views was once it's created, they update automatically without any further interaction. And if it's being recreated, all read queries against that view are locked until it is done?

Does this view really need to be created and/or recreated every time the plugin is loaded? 
Could it be done once on installation (either with documentation for a paster command or checking that it does not exist/is not the right structure before proceeding)?

### PR DESCRIPTION
**Pull request by fanderegg**
Fixes #2345
### Features:
- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [x] includes bugfix for possible backport

### CODE REVIEW

**Comment by wardi** [comment]
@fanderegg thanks, this shrinks the race condition we have when a number of workers are starting at the same time, but there's still a race. Would you mind moving the view-creation code to https://github.com/ckan/ckan/blob/master/ckanext/datastore/set_permissions.sql instead? That should completely eliminate the race.

**Comment by fanderegg** [comment]
@wardi I updated the pull request as you suggested.

**Comment by fanderegg** [comment]
Ok that wasn't as easy as i thought. I will check the errors and update the pull request.

**Comment by fanderegg** [comment]
@wardi Now all tests pass.

**Comment by fanderegg** [comment]
@wardi Any updates on this?

**Comment by amercader** [comment]
This is of course the right approach but is there a chance that people with an existing DataStore database will end up with no `_table_metadata` view? I guess that then they need to run the set permissions command to create the view. This sh be mentioned in the Change log.

**Comment by wardi** [comment]
I think the only way a user would end up with a missing `_table_metadata` is if they use an old version of the set permissions script, then upgrade ckan before ever enabling the datastore extension, then enable the datastore extension, right?

**Pull request merged**
