### PR TITLE
Apply env. variables to CKAN config

### PR DESCRIPTION
**Pull request by mattfullerton**
Complements https://github.com/ckan/ckan/pull/3553 by applying the environment variables. I'm not sure if this will really work on its own, but adding the environment variables (DB_PORT_5432_TCP_ADDR etc.) in the docker-compose.yml environment section will definitely work.

### CODE REVIEW

**Comment by wardi** [comment]
IIUC these settings shouldn't need to be in the ini file if they are in the environment when running ckan. Are they getting cleared from the environment in some cases?

**Comment by mattfullerton** [comment]
That's the first time I ever heard of CKAN taking an .ini setting from an environment variable?

**Comment by wardi** [comment]
It is a thing, yes https://github.com/ckan/ckan/blob/c871c719d148027fa54663a3decf428bf0b749d3/ckan/config/environment.py#L117-L136

**Comment by amercader** [comment]
Not relevant here, but there is also ckanext-envvars that allows setting (almost) all settings via environment variables.

**Comment by mattfullerton** [comment]
@wardi I see what you mean. I'm pretty sure we need to pass through the container names into those env. variables; the misleading comments in the script give the impression something will magically happen if the container is linked to one called "db", "solr", etc. but I don't think that's the case. Closing this and put the other change in #3582.

**Pull request closed without merging**
