### PR TITLE
cors: "no content"+access-control-allow-headers response

### LINKED ISSUE #6292: CORS headers for swagger (open api) et. al.
**CKAN version**
all

**Describe the bug**
When developing a customized swagger UI for our CKAN sites [1] I was unable to include POST requests as part of the interface

**Steps to reproduce**
Try using a cross-domain AJAX POST request to a ckan site with `ckan.cors.origin_allow_all` set to `true`

**Expected behavior**
Call should succeed

**Additional details**
POST call is blocked because an initial OPTIONS call is made to the serve and the response the wrong response code and has no `Access-Control-Allow-Headers` header line

[1]: https://open-data.github.io/OpenCanadaAPI/index-en.html (in progress)

### PR DESCRIPTION
**Pull request by wardi**
Fixes #6292 

### Proposed fixes:

respond with "no content" on empty responses and include access-control-allow-headers to make post requests to the API from other sites possible

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [X] includes bugfix for possible backport

### CODE REVIEW

**Comment by wardi** [comment]
probably not best place for the change. Might be better to specifically have a blueprint for API OPTIONS calls. Should have a test too.

**Comment by smotornyuk** [comment]
Just in case.. won't [flask-cors](https://github.com/corydolphin/flask-cors/blob/master/flask_cors/core.py#L203) solve this problem?

**Comment by wardi** [comment]
@smotornyuk not sure if it adds the response code I needed. For my case it might be simpler to add an IBlueprint plugin that does something like the extension you linked.

**Comment by pdelboca** [comment]
Closing due to inactivity. Feel free to reopen it if consider that it is still relevant.

**Pull request closed without merging**
