### PR TITLE
Fix NE locale, which was broken in a bad merge

### PR DESCRIPTION
**Pull request by amercader**
Fix the po file and recompile the mo file. @LinkSDM this needs
to be cherry-picked to the dev-v2.6 branch and perhaps fixed in
Transifex too

### CODE REVIEW

**Comment by amercader** [comment]
@wardi I'm getting two completely unrelated failures that have to do with the permissions labels, can you see what's the problem?

**Comment by amercader** [comment]
@wardi same failures on latest master: https://circleci.com/gh/ckan/ckan/1843

**Comment by wardi** [comment]
This is puzzling. Can't reproduce this locally and these tests used to pass on circle. I wonder if something about the circle image changed.

**Comment by wardi** [comment]
@amercader please merge from master

**Comment by amercader** [comment]
@wardi done

**Comment by amercader** [comment]
Sorry to break the not merging your own PR rule but I needed this to announce the translations for 2.6

**Pull request merged**
