### PR TITLE
Removed `resource` Blueprint; Using Only `<pkg_type>_resource` Blueprint;

### PR DESCRIPTION
**Pull request by JVickery-TBS**
# Fixes
Removed the `resource` blueprint, referred to as `prefixed_resource` in the code.
See https://github.com/ckan/ckan/issues/7372 for more details.

### Proposed fixes:
The helper function `build_nav_icon` fails to resolve active routes for `<package_type>_resource` blueprints. Unless if there is a reason to keep the `resource` blueprint, I propose to just drop it, and have only the `<package_type>_resource` blueprints

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [X] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by smotornyuk** [comment]
Everything is ok, but it's better not to remove the `resource` blueprint. It will exist just in case someone still uses `resource.xxx` routes. But it would be nice to update the changelog record and mention that `dataset_resource.` blueprint is a preferred name and plain `resource.` will be eventually removed

**Comment by JVickery-TBS** [comment]
@smotornyuk Okay the other `resource` blueprint has been brought back in. And the change log has been updated regarding the future removal of it, and the preferred blueprint to use.

**Comment by smotornyuk** [comment]
@JVickery-TBS, if you solve the `_get_package_type` issue that I mentioned earlier(do not import it from `views` into `lib`), I can merge this PR

**Comment by JVickery-TBS** [comment]
@smotornyuk okay I have removed the import from the views module in lib now. I just copied some of the code from the `_get_package_type` so that the dictization has the correct url for the package type. Or is it fine to just force `dataset_resource.read` here?

I merged in master to the branch to fix some merge conflicts as well.

**Comment by smotornyuk** [comment]
@JVickery-TBS, your implementation is better. Even though it won't make much difference if we use `dataset_resource.read` here, some extensions may rely on the actual package type. So it's better to use the real type instead of the `dataset` whenever it's possible

**Pull request merged**
