### PR TITLE
Update the WSGI entrypoint to not use paste.deploy

### LINKED ISSUE #4802: Update the WSGI entrypoint to not use paste.deploy
TODO

paste.deploy loadapp

#### Story points

### PR DESCRIPTION
**Pull request by davidread**
Fixes #4802

With this PR, we update the WSGI script (entrypoint), to get rid of paste-deploy, which is needed when deploying CKAN to a web server (because paste-deploy is Python 2 only).

I decided to move the place where we activate the virtual environment, from the WSGI script to the apache config. Here are some discussion points:

* activate_this.py is part of virtualenv, which we don't use for python3 (we use the built-in venv), it is so not as easily available in our instructions. It could be copied as a single file into our repo - virtualenv is MIT licensed. This would be most similar to the existing CKAN deployment method, so maybe that is easiest for our users to understand, rather than configuring it in mod_wsgi/uwsgi/gunicorn instead.

* However configuring in mod_wsgi/uwsgi/gunicorn seems straightforward - a single option. For uwsgi it's: -H on the command line or 'venv=' in the config. mod_wsgi also prefers you configure the virtualenv in the mod_wsgi options, rather than in the WSGI script itself - source https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html#adding-additional-module-directories Django also directs you to configure the virtualenv in the server config.

* In the WSGI script, as an alternative to activate_this.py, I tried activating the virtualenv in the wsgi file:

      import sys
      import site
      python_venv = '/usr/lib/ckan/default'
      python_version = '.'.join(map(str, sys.version_info[:2]))
      site_packages = python_venv + '/lib/python%s/site-packages' % python_version
      site.addsitedir(site_packages)

  However it adds the virtualenv at the end of the pythonpath, and we end up with problems when the system version of 'yaml' takes priority.

I also fixed a line in the instructions that reloaded nginx, when it should be restarting - need to start nginx before it will let us reload it. (It doesn't start when you install it because apache is listening on port 80 by default when you installed it)

### Features:

- [ ] includes tests covering changes
- [x] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by kowh-ai** [comment]
I'd also like to be part of the testing for this PR :-)

**Comment by amercader** [comment]
I'm +1 on activating the venv at the WSGI server level

@davidread @kowh-ai , FYI @MasaGon has been working on running uwsgi see, https://github.com/ckan/ckan/pull/5204#commitcomment-37418482

**Comment by davidread** [comment]
I've run into a couple of problems with this PR. @ckan/core Some help would be appreciated on either, particular the second one, because I'm stumped.

1. When I restart apache I see this in `/var/log/apache2/ckan_default.error.log`:
```
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f4031bf39d8>
Traceback (most recent call last):
  File "/usr/lib/python3.6/weakref.py", line 117, in remove
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/zope/interface/interface.py", line 523, in __hash__
NameError: name 'hash' is not defined
```
I can't find much about this error on the internet, or really understand it. hash() is built into python2 and python3. I can still make requests of CKAN fine so far, but the message is concerning.

2. I can't run apache2 with multiple threads in Python3. It works running under Python2 multi-threaded or Python3 with `threads=1` in `/etc/apache2/sites-available/ckan_default.conf`. But with Python3 and multiple thread, requests give this error in `/var/log/apache2/ckan_default.error.log`:
```
mod_wsgi (pid=22163): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
Traceback (most recent call last):
  File "/etc/ckan/default/apache.wsgi", line 8, in <module>
    application = make_app(config)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 58, in make_app
    flask_app = make_flask_stack(conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 228, in make_flask_stack
    _register_core_blueprints(app)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 494, in _register_core_blueprints
    module = loader.find_module(name).load_module(name)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/../../views/feed.py", line 10, in <module>
    from feedgen.feed import FeedGenerator
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/feedgen/feed.py", line 17, in <module>
    from lxml import etree  # nosec - not using this for parsing
ImportError: Interpreter change detected - this module can only be loaded into one interpreter per process.
```
As far as I can understand it, lxml.etree is Cython which has some global state and therefore cannot run multi-threaded. However I don't get this error in Python2.

I notice that @MasaGon also used single-threading in his uwsgi version https://github.com/ckan/ckan/pull/5204#commitcomment-37565347 - maybe he encountered the same problem with multi-threading?

**Comment by amercader** [comment]
@davidread I haven't looked at the issues you describe yet but just to avoid confusion, Werkzeug should not be involved at all in a production deployment (and you are not using it in your changes AFAICT). Just mentioning because the PR title confused me.

The goal here is having a generic WSGI script that can be used by different servers (uwsgi, gunicorn, apache + mod_wsgi). The one [currently used](https://github.com/ckan/ckan/blob/master/contrib/docker/apache.wsgi) on the deployment instructions and the Debian package uses `paste.deploy.load_app` as our entrypoint (`make_app()`) used to be a paster one, but that is not the case any more, so we can simplify it as you've done [here](https://github.com/ckan/ckan/pull/5267/files#diff-96c8c3598793a29820d24f367817be5cR88). Looks like you are focusing on Apache here and @kowh-ai did some initial work on uwsgi and nginx, which I've also started reviewing in https://github.com/ckan/ideas-and-roadmap/pull/234

To be honest, if Apache on py3 gives us much trouble perhaps we should just drop support for it. It makes sense to keep support on py2 for 2.9 but going forward uwsgi or gunicorn are much more widely used options.

I'll keep look at this, thanks for your work so far.

**Comment by kowh-ai** [comment]
I'll work on this this week...I'll try to get the same (generic) WSGI script used by different (http) servers (uwsgi, gunicorn, apache + mod_wsgi). Plus get the virtual environment set in each of the Server config files. I'll try to look at the thread issue too

**Comment by kowh-ai** [comment]
@davidread I'm having problems with the WSGI script in this pull request with the WSGI Server
This script has the problem:
```
import os
from ckan.config.middleware import make_app
from ckan.cli import CKANConfigLoader
from logging.config import fileConfig as loggingFileConfig
config_filepath = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'ckan.ini')
loggingFileConfig(config_filepath)
config = CKANConfigLoader(config_filepath).get_config()
application = make_app(config)
```
produces this error:
```
Traceback (most recent call last):
  File "./wsgi.py", line 8, in <module>
    loggingFileConfig(config_filepath)
  File "/usr/lib/python3.6/logging/config.py", line 76, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python3.6/logging/config.py", line 109, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
```
while this WSGI script works:
```
import os
from ckan.config.middleware import make_app as loadapp
from ckan.cli import load_config
config_filepath = '/etc/ckan/default/ckan.ini'
conf = load_config(config_filepath)
application = loadapp(conf)
```
Happens on a new install (from source) of CKAN 2.9 on both Ubuntu 16.04 and 18:04

Looks like (maybe) a path problem? Any idea? 
thanks

**Comment by davidread** [comment]
@kowh-ai So if you're saving it at `/etc/ckan/default/wsgi.py` (check this) then I'd expect it would look for the config in the same folder `/etc/ckan/default/ckan.ini`. I guess you could easily check by putting in a `print config_filepath` and running it directly in python.

The error is about the formatters section, so also check your ckan.ini has that.

**Comment by kowh-ai** [comment]
@davidread - thanks - I had a `chdir` command in my wsgi config file which I didn't need with your wsgi.py - the `chdir` line was needed in a previous life - all good now 👍

**Comment by kowh-ai** [comment]
@davidread - I have created a new PR based on your work here David: https://github.com/ckan/ckan/pull/5406 - It seems I didn't have the same issues with the Apache Server threading problems you had - or I am missing something

**Comment by amercader** [comment]
Closed in favour of #5406

**Pull request closed without merging**
