### PR TITLE
Update changed_group.html

### LINKED ISSUE #5915: Groups Activity Stream do not have detailed "changes" in UI
**CKAN version**
   2.9

**Describe the bug**
If there is any change in Groups, it only logs that the Groups has been updated.

**Steps to reproduce**
   Make changes to a Group and check the Activity Stream.

**Expected behavior**
   The  Groups Activity Stream should show the differences.

**Additional details**
  This is similar to Dataset detailed Activity Stream.

### PR DESCRIPTION
**Pull request by Gauravp-NEC**
Fixes #5915 

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by Gauravp-NEC** [comment]
This PR is related to PR https://github.com/ckan/ckan/pull/5985. The code to develop "Group changes " in activity stream is already merged into CKAN master. Only the GUI "changes" option in activity stream is needed to be developed.

**Comment by Gauravp-NEC** [comment]
@Zharktas , This PR is related to PR https://github.com/ckan/ckan/pull/5985. The code to develop "Group changes " in activity stream is already merged into CKAN master. Only the GUI "changes" option in activity stream is needed to be developed. Please review this PR.

**Review by Zharktas — CHANGES_REQUESTED** [review]
The changes view now assumes that the it is rendering a organization and it generates urls to organization while it should generate them to groups when they are groups.

**Comment by Zharktas** [comment]
And you really should make more descriptive commits, "update changed_group.html" does not tell anything what has changed.

**Comment by Gauravp-NEC** [comment]
@Zharktas , I have completed this PR and now it is generating URLs for group when they are groups. Also all the test cases have been passed and this PR is ready to be merged.

**Comment by Gauravp-NEC** [comment]
@Zharktas ,  I have completed this PR and now it is generating URLs for group when they are groups. Also all the test cases have been passed and this PR is ready to be merged.

**Comment by Gauravp-NEC** [comment]
@Zharktas , I have completed this PR and now it is generating URLs for group when they are groups. Also all the test cases have been passed and this PR is ready to be merged.

**Comment by Gauravp-NEC** [comment]
@Zharktas , I have completed this PR and now it is generating URLs for group when they are groups. Also all the test cases have been passed and this PR is ready to be merged. Thankyou :)

**Review by Zharktas — APPROVED** [review]

**Pull request merged**
