### PR TITLE
Upgrading of SQLalchemy to version 1.3.3

### LINKED ISSUE #4736: Upgrade sqlalchemy
It would be good to upgrade sqlalchemy from 1.1.11 to the latest (1.3.2 currently).

Currently vdm complains with this new version:
```
ValueError: VDM only works with SQLAlchemy versions 0.4 through 0.9, not: 1.3.2
```
(see [Travis for branch upgrade-to-sqlalchemy-1.3.2](https://circleci.com/gh/ckan/ckan/5136) )

vdm won't be required soon, so upgrading sqlalchemy should be easy. Although it might be useful to fix vdm anyway, for the benefit of older installs of CKAN wanting to keep up to date.

### PR DESCRIPTION
**Pull request by iamarnavgarg**
Fixes #4736 

While updating the version of SQLalchemy from 1.1.11 to 1.3.3 , I encountered the following issue while creating a dataset.

image
-----------------------------------------------------------------------------------------------------------------
image

Thus, this PR also fixes the above issue by editing in file- meta.py

### CODE REVIEW

**Comment by amercader** [comment]
cc @frafra 

Thanks @iamarnavgarg! There are still some tests failures caused by the same issue (SQLA now requires strict boolean types when providing values for a boolean field, [more info](https://docs.sqlalchemy.org/en/13/changelog/migration_12.html#boolean-datatype-now-enforces-strict-true-false-none-values)). If you can fix those in the tests or the code they refer to that would be great. We can then merge it and see if more issues come up.

There's a small PEP8 failure as well.

**Comment by davidread** [comment]
@iamarnavgarg I had a quick look and this fixes one test: https://github.com/ckan/ckan/commit/db3e266f794690486976ca4da289b27d1e75f3e2

**Comment by frafra** [comment]
Would it be possible to add that patch and move forward with the pull request? This blocks other pull requests for fixing the "Internal server error" that some users are having (see gitter). Thanks :)

**Comment by davidread** [comment]
@frafra Agreed this is a crucial upgrade. I've not discussed this with @iamarnavgarg but if you have a chance to help fix remaining tests then I'm sure that'd be welcome. You could use the branch I created on the ckan org so that you have permissions to push onto it: https://github.com/ckan/ckan/compare/iamarnavgarg-iamarnavgarg-patch-1

**Comment by iamarnavgarg** [comment]
> @iamarnavgarg I had a quick look and this fixes one test: [db3e266](https://github.com/ckan/ckan/commit/db3e266f794690486976ca4da289b27d1e75f3e2)

Hi @davidread, just a query that did you consider the changed files of my branch as it is showing that "branch has conflicts that must be resolved".?

Also, before submitting the commit for cli.py and creating a user using paster command, I used to get the same error as shown in the travis tool . But, after fixing it in cli.py it successfully creates the user as shown below:

image

**Comment by davidread** [comment]
@iamarnavgarg I created a fresh branch from master, applied your commits and then that commit db3e266 on top. So maybe there's a difference because of us branching from master in different places. Hopefully you can work out how to resolve the conflict with these two lines, or maybe someone will jump in to help.

**Comment by iamarnavgarg** [comment]
Hi @amercader , my PR is ready to be merged. But due to some commits of @davidread , the conflict have arised. However, when i click on resolve conflicts button, the page keeps on uploading and doesn't show the conflicts. So, would request you to please merge it.

**Comment by frafra** [comment]
`requirements.in` has not been updated; `requirements.txt` should not be updated manually.

**Comment by iamarnavgarg** [comment]
> @iamarnavgarg I do not have permissions to push on that branch, I am not a maintainer: I will create mine.
> 
> `requirements.in` has not been updated; `requirements.txt` should not be updated manually.

@frafra The PR raised by me was completed and has fix of #4736  and it was ready to merge. The PR raised by you i.e. #4853  by including this PR,  is not required. Once this PR is merged then you can raise another PR for your changes.

**Comment by frafra** [comment]
> @frafra The PR raised by me was completed and has fix of #4736 and it was ready to merge. The PR raised by you i.e. #4853 by including this PR, is not required. Once this PR is merged then you can raise another PR for your changes.

Your PR is not ready to be merged and it has an error. As I care to have this important update into CKAN I helped fixing that small issues, but as I am not a maintainer I had to open a new PR on a different branch.

If you alter `requirements.txt` manually without generating it from a new version of `requirements.in`, the next time someone will generate it again your modifications will be deleted automatically.

Have a look at the first lines of  `requirements.txt`:
https://github.com/ckan/ckan/blob/49bdec8c3937b132b3b16977edd163aa48047be3/requirements.txt#L1-L6

If my PR gets approved (rebased on master and with the additional fixes) you are still the author of your commits. I do not understand what is the problem here.

**Comment by iamarnavgarg** [comment]
> @iamarnavgarg nice job finishing off the test fixes! You've done all the hard work.
> 
> @frafra has added the requirements.in changes, which is simply a CKAN convention we choose to do, so that's useful and needed to be merged. And his PR fixes that weird conflict thing this one suffers  . I've queried a couple other minor things, but we're pretty much there, so thanks all round.

Alright. @davidread , Thanks for merging the PR, can we close this PR?

**Comment by davidread** [comment]
These comments were merged in https://github.com/ckan/ckan/pull/4853

**Pull request closed without merging**
