### PR TITLE
fix dataset ATOM feed

### PR DESCRIPTION
**Pull request by fanjinfei**
Fixes #
Package ATOM feed was missing by previous commit.
tests are broken too.
### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [X] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by fanjinfei** [comment]
not sure if the fix for test cases is decent.

**Comment by TkTech** [comment]
This should go into 2.8 with the other activity changes, but it's otherwise fine to merge.

**Comment by amercader** [comment]
@fanjinfei @TkTech could you describe what is the goal of this PR or what is trying to solve?
Does it follow work on another PR?

There is no context in the description or a linked issue so it's hard to understand the context. Cheers.

**Comment by fanjinfei** [comment]
There used to be "package ATOM feed". It was removed in this branch. So I was trying to bring to back.

**Pull request closed without merging**
