### PR TITLE
QGOV bug fixes

### PR DESCRIPTION
**Pull request by ThrawnCA**
### Proposed fixes:

- Clean up imports.
- Handle race condition in creating site user, #6631 
- Handle external creation of storage directory with limited permissions, #6521
- Handle missing resources in activity stream (backported)

### CODE REVIEW

**Comment by Zharktas** [comment]
Our process is cherry-pick PR's that are marked as backport pending during the release process instead of making new PR's against dev branched. I marked the other one which did not have those labels so it should be in next 2.9 release. 

It would also be nice to have descriptive titles for PRs and commit messages should be using our conventions http://docs.ckan.org/en/2.9/contributing/commit-messages.html as ticket id's which have no use outside of your project are confusing for others.

I'll close this, as fixes should be cherry-picked unless its something that specifically can't be cherry-picked.

**Comment by ThrawnCA** [comment]
Do these look like changes that would be worth having if they're resubmitted in the right format?

**Comment by amercader** [comment]
Thanks @ThrawnCA 
#6638 and #6578 are marked for backporting, which should cover your second and third points. [7a66123](https://github.com/ckan/ckan/pull/7010/commits/7a66123d1b073e24c5d18ad8da5ff9457743b129) and [f08a72c](https://github.com/ckan/ckan/pull/7010/commits/f08a72c2d7de5c425a93934422a4fecf245c8691) would be definitely nice to have in 2.9. If these are already fixed in master you can submit a PR against `dev-v2.9`, otherwise we should fix them in master first and then backport them.

**Comment by ThrawnCA** [comment]
7a66123 and f08a72c have been addressed in master as part of #5924, although that issue isn't really about them. I guess some cleanup happened as part of it?

**Comment by ThrawnCA** [comment]
> If these are already fixed in master you can submit a PR against `dev-v2.9`

Doesn't that contradict the policy that Zharktas described?

> Our process is cherry-pick PR's that are marked as backport pending during the release process instead of making new PR's against dev branched.

**Pull request closed without merging**
