### PR TITLE
[WIP] - Redis ENV - BugFix

### LINKED ISSUE #3389: [REDIS] - Redis is not using the ENVVAR
REDIS seems like its not reading the ENVVAR from this [https://github.com/ckan/ckan/blob/master/ckan/config/environment.py#L124](https://github.com/ckan/ckan/blob/master/ckan/config/environment.py#L124)

### PR DESCRIPTION
**Pull request by deinok**
Closes #3389

### CODE REVIEW

**Comment by torfsen** [comment]
How does this relate to #3389? All I see are new `u` prefixes :wink: Don't get me wrong, anything that improves Unicode handling is good, I just don't see how this is related to Redis.

You might also want to remove the file from [the white-list in `test_coding_standards.py`](https://github.com/ckan/ckan/blob/07ce1ec4ed368a5258bef1a689ab0c2299da8be8/ckan/tests/test_coding_standards.py#L235).

**Comment by deinok** [comment]
@torfsen At the first moment I think that the error was that the config was searching for an unicode string and only exist a binary string
Ex: u'myString' != 'myString'

**Comment by amercader** [comment]
sorry @deinok is this still relevant? I don't see how changing the strings to unicode would affect the Redis env var?

**Comment by amercader** [comment]
Closing for now feel free to resubmit if this is still needed

**Pull request closed without merging**
