### PR TITLE
[WIP] Switch fq from string to list

### PR DESCRIPTION
**Pull request by morty**
For ticket #2853 

WIP because this is a port of the code I did for data.gov.uk but I'm not sure it doesn't break anything. 

Currently only switches fq of package search. Should all the other times fq is sent to Solr be converted too?

### CODE REVIEW

**Comment by davidread** [comment]
@morty what's the plan with this now?

**Comment by morty** [comment]
@rossjones is looking at using fq_list for the required purpose that might mean that this refactor wouldn't be required.

**Comment by davidread** [comment]
ok thanks

**Comment by rossjones** [comment]
@morty Any objections to me closing this PR now?  I don't think it's going to get finished this way.

**Comment by morty** [comment]
@rossjones I guess not. There are a number of conflicts as the codebase has moved on. This PR will still be referenced in the issue if someone wants to try again.

**Pull request closed without merging**
