### PR TITLE
[6611]Groups should be selectable as Dataset collaborators

### LINKED ISSUE #6611: Groups should be selectable as Dataset collaborators
The Dataset collaborators feature is a great addition in 2.9. However, it only allows to select individual users as collaborators, not groups.
CKAN describes groups as means for _catalogue datasets for a particular project or team_. Having to add all individual users of a team to a dataset as collaborators individually can be error prone for larger teams. Being able to make groups collaborators on Datasets also means a user could just be removed from a group versus having to remove the user from all datasets individually.
Is this maybe planned for the _Dataset collaborators_ feature or is there a solution already?
Thank you!

### PR DESCRIPTION
**Pull request by TomeCirun**
Fixes #6611 

I made a few changes that will allow us to push all the users in a group, on one go.
If you have any suggestions on how to make the code better, please do not hesitate to propose.

Here is the screenshot from the UI:
image

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [x] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by TomeCirun** [comment]
@smotornyuk  can you help with the test ?
Thanks

**Comment by jeverling** [comment]
Hi, thanks for working on this!
This MR iterates through all users of a group, and individually adds them as collaborators on a given dataset, right?
This has the drawback, that it's not going to be updated when users are added or removed from a group later.

Ideally, group membership should just be used to determine whether a user is allowed to access a dataset or not, and it should not be necessary to add all users as collaborators individually.

Check out the extension that was mentioned in the issue: https://github.com/USEPA/ckanext-collaborator_orgs/blob/master/ckanext/collaborator_orgs/logic/auth.py#L62

I think hooking into the auth check to include group memberships when trying to determine whether a given user has access to a dataset or not is more flexible and more future-proof than statically adding all users as collaborators once.

**Comment by TomeCirun** [comment]
> I think hooking into the auth check to include group memberships when trying to determine whether a given user has access to a dataset or not is more flexible and more future-proof than statically adding all users as collaborators once.

Hey @jeverling , yep I agree with that, but then we will have to add another column to  `package_member` table https://github.com/ckan/ckan/blob/9dc138543580e8002b0f34b735a96079307496b6/ckan/model/package.py#L78-L85 that would contain `group_or_org_id` as we need to know which group has been added as a collaborator so we can implement the logic according that...
I could use some help from @pdelboca  to tell me how to refactor `package_member` (if it's even possible to implement it like this)

Thanks

**Comment by pdekraker-epa** [comment]
I would like to see this feature integrated into CKAN, and it looks like this PR has stalled. The last question was how to add it to the database. Being an extension ckanext-collaborator_orgs used a separate table, is that a better approach than adding a column to the existing table? There may be other nuances about capacity that differ as well between user collaborators and organization collaborators, so a separate table may be more flexible in that regard.

**Comment by EricSoroos** [comment]
Closing this, as #6905 a successor to this.

**Pull request closed without merging**
